### PR TITLE
retry local clones without hardlinks if they fail

### LINKED ISSUE #11420: installing git repository ignores UV_LINK_MODE, breaks on some filesystems
### Summary

I am on a cluster with a distributed filesystem (beefgs) which does not support hard links.
I am trying to install a repository directly, but it fails when symlinking the repository between two locations in the uv cache directory.

I would assume that setting `UV_LINK_MODE=symlink` or `UV_LINK_MODE=copy` would fix the error, but it seems that the setting is not applied to the git command in this case

```bash
(base) [filippo.vicentini@cholesky-login02 prova2]$ uv init --no-package
Initialized project `prova2`
(base) [filippo.vicentini@cholesky-login02 prova2]$ uv add git+https://github.com/netket/netket
error: Git operation failed
  Caused by: process didn't exit successfully: `/usr/bin/git clone --local /mnt/beegfs/home/CPHT/filippo.vicentini/.cache/uv/git-v0/db/292f78b3ecf26bf6 /mnt/beegfs/home/CPHT/filippo.vicentini/.cache/uv/git-v0/checkouts/292f78b3ecf26bf6/f1db6bb` (exit status: 128)
--- stdout
Cloning into '/mnt/beegfs/home/CPHT/filippo.vicentini/.cache/uv/git-v0/checkouts/292f78b3ecf26bf6/f1db6bb'...

--- stderr
fatal: failed to create link '/mnt/beegfs/home/CPHT/filippo.vicentini/.cache/uv/git-v0/checkouts/292f78b3ecf26bf6/f1db6bb/.git/objects/pack/pack-384b576a7a115ef20196172649a6bf2ab2b2ab8e.idx': Operation not permitted
fatal: The remote end hung up unexpectedly
(base) [filippo.vicentini@cholesky-login02 prova2]$ ^C
(base) [filippo.vicentini@cholesky-login02 prova2]$ export UV_LINK_MODE=copy
(base) [filippo.vicentini@cholesky-login02 prova2]$ uv add git+https://github.com/netket/netket
error: Git operation failed
  Caused by: process didn't exit successfully: `/usr/bin/git clone --local /mnt/beegfs/home/CPHT/filippo.vicentini/.cache/uv/git-v0/db/292f78b3ecf26bf6 /mnt/beegfs/home/CPHT/filippo.vicentini/.cache/uv/git-v0/checkouts/292f78b3ecf26bf6/f1db6bb` (exit status: 128)
--- stdout
Cloning into '/mnt/beegfs/home/CPHT/filippo.vicentini/.cache/uv/git-v0/checkouts/292f78b3ecf26bf6/f1db6bb'...

--- stderr
fatal: failed to create link '/mnt/beegfs/home/CPHT/filippo.vicentini/.cache/uv/git-v0/checkouts/292f78b3ecf26bf6/f1db6bb/.git/objects/pack/pack-384b576a7a115ef20196172649a6bf2ab2b2ab8e.idx': Operation not permitted
fatal: The remote end hung up unexpectedly
```

### Platform

Linux 3.10.0-1062.el7.x86_64 x86_64 GNU/Linux

### Version

uv 0.5.30

### Python version

Python 3.12.7

### PR DESCRIPTION
**Pull request by Gankra**
Fixes #11420

### CODE REVIEW

**Comment by Gankra** [comment]
I need to setup BeeGFS to check that this really works.

**Comment by PhilipVinc** [comment]
If you give me a built linux executable I can try for you

**Comment by Gankra** [comment]
Oh great! The PR CI already built one:

https://github.com/astral-sh/uv/actions/runs/13266446923/artifacts/2572423342

**Comment by PhilipVinc** [comment]
@Gankra I managed to use the muse builds.

It seems there is a typo:
```bash
  Caused by: process didn't exit successfully: `/usr/bin/git clone --no-hard-links /mnt/beegfs/home/CPHT/filippo.vicentini/.cache/uv/git-v0/db/292f78b3ecf26bf6 /mnt/beegfs/home/CPHT/filippo.vicentini/.cache/uv/git-v0/checkouts/292f78b3ecf26bf6/f1db6bb` (exit status: 129)
--- stderr
error: unknown option `no-hard-links'
usage: git clone [options] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
```

It should be `--no-hardlinks` but you specified `--no-hard-links`

**Comment by charliermarsh** [comment]
You can use the musl wheel, hopefully? It's under https://github.com/astral-sh/uv/actions/runs/13266446923/artifacts/2572463068.

File: crates/uv-git/src/git.rs [hunk 1]
```diff
@@ -422,15 +422,26 @@ impl GitCheckout {
...
             .arg(into.simplified_display().to_string())
-            .exec_with_output()?;
+            .exec_with_output();
+
+        if let Err(e) = res {
+            debug!("Cloning git repo with --local failed, retrying without hardlinks: {e}");
+
+            ProcessBuilder::new(GIT.as_ref()?)
+                .arg("clone")
+                .arg("--no-hard-links")
```
Comment (PhilipVinc) [inline crates/uv-git/src/git.rs:440]:
```suggestion
                .arg("--no-hardlinks")
```

**Comment by charliermarsh** [comment]
Thanks. I triggered a rebuild.

**Comment by charliermarsh** [comment]
The updated musl version is https://github.com/astral-sh/uv/actions/runs/13272737821/artifacts/2574639236.

**Comment by PhilipVinc** [comment]
tested. It works. thanks!

**Review by charliermarsh — APPROVED** [review]

**Comment by charliermarsh** [comment]
Great, thanks! I'll leave to @Gankra to merge.

**Comment by charliermarsh** [comment]
(Confirmed in Discord.)
