### PR TITLE
Propagate project-level conflicts to package extras

### LINKED ISSUE #18015: `tool.uv.conflicts` with package + extra yields unsatisfiable workspace lock
### Summary

I’m seeing a resolver failure in a uv workspace even though I explicitly declared package-level conflicts involving extras.

### Reproduction repository

- Repo: [gautier-cohere/workspace-test-uv-conflict-repro](https://github.com/gautier-cohere/workspace-test-uv-conflict-repro.git)
- Branch: `main`
- Commit: `42f93cd` (current repro commit)
- `uv --version`: `uv 0.10.2 (a788db7e5 2026-02-10)`
- OS: macOS (`darwin 25.2.0`)

```text
workspace-test-uv-conflict-repro/
├── pyproject.toml
├── pkg-a/
│   └── pyproject.toml
└── pkg-b/
    └── pyproject.toml
```

`/pyproject.toml`
```toml
[project]
name = "workspace-test"
version = "0.1.0"
description = "Test uv workspace with conflicting optional groups"
requires-python = ">=3.11,<3.13"

[tool.uv.workspace]
members = [
  "pkg-a",
  "pkg-b",
]

[tool.uv]
conflicts = [
  [
    { package = "pkg-a"},
    { package = "pkg-b", extra = "unsafe" },
  ],
  [
    { package = "pkg-a"},
    { package = "pkg-b", extra = "all" },
  ],
]
```

`/pkg-a/pyproject.toml`
```toml
[project]
name = "pkg-a"
version = "0.1.0"
description = "Package A - depends on pkg-b[safe]"
requires-python = ">=3.11,<3.13"

dependencies = [
  "pkg-b[safe]",
  "datasets<4",
]

[project.optional-dependencies]
all = [
  "pkg_a[foo]",
  "pkg_a[bar]",
]
foo = [
  "numpy"
]
bar = [
  "pandas",
]

[tool.uv.sources]
pkg-b = { workspace = true }
```

`/pkg-b/pyproject.toml`
```toml
[project]
name = "pkg-b"
version = "0.1.0"
description = "Package B"
requires-python = ">=3.11,<3.13"

dependencies = []

[project.optional-dependencies]
all = [
  "pkg_b[safe]",
  "pkg_b[unsafe]",
]
safe = [
  "datasets"
]
unsafe = [
  "datasets>4",
]
```

### Steps to reproduce

```bash
uv lock
```

### Actual behavior

`uv lock` fails with unsatisfiable requirements.  
The resolver reports that `pkg-a` (`datasets<4`) and `pkg-b[unsafe]` / `pkg-b[all]` (`datasets>4`) are incompatible, and that the workspace requirements are unsatisfiable.

### Expected behavior

I expected the declared conflicts in `tool.uv.conflicts` (between `pkg-a` and `pkg-b[unsafe]` / `pkg-b[all]`) to be honored in a way that allows workspace locking (e.g., split handling of incompatible combos), rather than failing the entire lock as unsatisfiable.

### Question

Is this the intended behavior for package-level conflicts with extras in workspaces, or is this a resolver bug? 

What's the recommended way to do this? Imagine I have many more extra groups and many more packages in the workspace, it becomes intractable to enumerate every conflict. I would expect the package level conflict to be enough. 

---
Reference repo link: [https://github.com/gautier-cohere/workspace-test-uv-conflict-repro.git](https://github.com/gautier-cohere/workspace-test-uv-conflict-repro.git)

### Platform

Darwin 25.2.0 arm64

### Version

uv 0.10.2 (a788db7e5 2026-02-10)

### Python version

_No response_

### PR DESCRIPTION
**Pull request by zanieb**
Closes #18015

Project-level conflict items (e.g., `{ package = "pkg-a" }`) were not properly excluding the package's extras and groups from the conflicting fork. When a project-level conflict excludes a package, all of that package's extras  should also be excluded (since they transitively depend on the base package). The alternative seems to be that the user needs to enumerate all of the extra conflicts explicitly in addition to the package conflict, which seems excessive.

### CODE REVIEW

File: crates/uv-resolver/src/resolver/environment.rs [hunk 1]
```diff
@@ -185,7 +189,33 @@ impl ResolverEnvironment {
...
+                // would pull the project's dependencies back in.
+                if !matches!(group.kind(), ConflictKindRef::Project) {
+                    if exclude.contains(&ConflictItemRef::from(group.package())) {
+                        // But if this specific extra/group is explicitly
+                        // included (e.g., in a conflict between a project
+                        // and one of its own groups), respect the inclusion.
+                        if include.contains(&group) {
+                            return true;
+                        }
+                        return false;
```
Comment (zanieb) [inline crates/uv-resolver/src/resolver/environment.rs]: I guess this should be
```suggestion
                        return include.contains(&group);
```

File: crates/uv-resolver/src/resolver/environment.rs [hunk 2]
```diff
@@ -185,7 +189,30 @@ impl ResolverEnvironment {
...
+                ref exclude,
+                ..
+            } => {
+                if exclude.contains(&group) {
+                    return false;
+                }
+                // When a project-level conflict item is excluded, all of
+                // the project's extras and groups should be excluded too,
+                // unless they are explicitly included. This is because
+                // extras/groups transitively depend on the base package,
```
Comment (zanieb) [inline crates/uv-resolver/src/resolver/environment.rs]: Groups do not transitively depend on the base package, that's false.
