### PR TITLE
Respect `NO_COLOR` and always show the command as a header when paging `uv help` output

### LINKED ISSUE #16015: `uv help tool run` fails due to unsupported `less -P` option
#### Description
When running `uv help tool run`, the command fails because the system `less` binary does not support the `-P` option. This happens in environments where `less` is provided by BusyBox.

#### Steps to Reproduce
```bash
podman run --rm -it alpine
> echo -e "https://dl-cdn.alpinelinux.org/alpine/edge/main\nhttps://dl-cdn.alpinelinux.org
/alpine/edge/community" > /etc/apk/repositories
> apk update && apk add python3 uv
> uv -v help tool run
DEBUG uv 0.8.21
/usr/bin/less: unrecognized option: P
BusyBox v1.37.0 (2025-05-26 20:04:45 UTC) multi-call binary.

Usage: less [-EFIMmNSRh~] [FILE]...

View FILE (or stdin) one screenful at a time

	-E	Quit once the end of a file is reached
	-F	Quit if entire file fits on first screen
	-I	Ignore case in all searches
	-M,-m	Display status line with line numbers
		and percentage through the file
	-N	Prefix line number to each line
	-S	Truncate long lines
	-R	Remove color escape codes in input
	-~	Suppress ~s displayed past EOF
```

The issue seems to come from this section of the code where the `-P` flag is passed to less: https://github.com/astral-sh/uv/blob/ade2bdbd2a58c303b23976be3649ac1ed8796716/crates/uv/src/commands/help.rs#L136

### Platform

Linux 6.12.13-200.fc41.aarch64 aarch64 Linux

### Version

0.8.21

### Python version

Python 3.12.11

### PR DESCRIPTION
**Pull request by EliteTK**
## Summary

Fix #16015 and address an additional issue where the pager prompt would be bold
regardless of NO_COLOR.

image

## Test Plan

Ran the test suite and manually verified against less 679 and busybox v1.34.1.
Checked with and without `NO_COLOR` on both less, busybox less, and more.

### CODE REVIEW

File: crates/uv/src/commands/help.rs [hunk 1]
```diff
@@ -87,10 +87,12 @@ pub(crate) fn help(query: &[String], printer: Printer, no_pager: bool) -> Result
             } else {
                 Either::Right(help.clone())
             };
-            pager.spawn(
-                format!("{}: {}", "uv help".bold(), query.join(" ")),
-                &content,
-            )?;
+            // Pager might support colors, but the user might not want them
+            let title = match content {
+                Either::Left(_) => Either::Left("uv help".bold()),
```
Comment (konstin) [inline crates/uv/src/commands/help.rs]: Doing this with a match isn't ideal but that's a pre-existing pattern

Comment (EliteTK) [reply crates/uv/src/commands/help.rs]: Yeah I thought so too. There were a few options but this seemed like the least noisy way of getting this sorted out for now.

I think the way this bit is all handled could be improved but maybe as a separate change.

Comment (zanieb) [reply crates/uv/src/commands/help.rs]: I think this is pretty confusing as a `match`. It took me a while to understand what the comment meant. In what sense is that a pre-existing pattern here?

If you're going to be adding colors to the body like this, I'd do the refactor to make the logic clearer too. If you're hesitant to do that in this pull request, maybe I'd defer using the bold until the subsequent change? It does seem like a distraction from the goal of fixing `-P`.

**Comment by zanieb** [comment]
I'm a little sad to lose `-P` which I think is a strictly better experience for the majority of users (assuming BusyBox is fairly uncommon) since the prompt stays with you as you scroll. I'm not sure I care that it differs from cargo and git, e.g., cargo using `man` by default and has pretty simple handling

https://github.com/rust-lang/cargo/blob/ebd20d2454fb299834f07b8f5f164783b4e24248/src/bin/cargo/commands/help.rs#L82-L100

**Comment by zanieb** [comment]
I'm not tied to keeping `-P` though. I do like the header.

**Comment by EliteTK** [comment]
@zanieb An option to keep `-P` (although I think it would be good to have both in that case) would be to put it in the `LESS` environment variable. `busybox less` silently ignores it then. But I haven't checked if it's possible to smuggle spaces into the prompt in that case. There's also the case of handling user provided LESS values. It's probably fine to just append a space and our `-P` in that case though.

File: crates/uv/src/commands/help.rs (hunk 1 above)
Comment (konstin) [reply crates/uv/src/commands/help.rs]: I was referring to the help_ansi logic above where we first look at stdout and with `Either` and then do a separate check for the pager with `pager.supports_colors()`. Looking into the code some more, the `StyledStr` from clap uses anstream internally, so there seems to be no functional difference between using anstream here directly instead of toggling on `.ansi()` (except maybe buffer allocation, but our help pages shouldn't be that long)?

Comment (zanieb) [reply crates/uv/src/commands/help.rs]: Ah I see. My point was that we weren't matching on the `Either`.

Just to make sure we're on the same page: `pager.supports_colors()` is whether the pager (i.e., `more`) supports colors as opposed to stdout. It's intentionally that these are composed. I don't recall the details of why I implemented it this way though, it's definitely plausible it could be simplified.

**Comment by zanieb** [comment]
Huh, surprised to find out that `echo "hello" | LESS="-P foo bar" less` works. That's kind of fun.

I don't have strong feelings. I'm happy to go with whatever you think is reasonable.

File: crates/uv/src/commands/help.rs (hunk 1 above)
Comment (EliteTK) [reply crates/uv/src/commands/help.rs]: The bold was there already, so I assume you are suggesting just dropping this commit (which fixes the NO_COLOR)?

I can probably re-factor it though. I don't mind going a bit deeper.

Comment (zanieb) [reply crates/uv/src/commands/help.rs]: To me, bold in a pager prompt feels different than bold in the content itself. I think you could just drop the bold entirely when moving it to the header then restore it separately while refactoring color handling? I don't think the sequencing of work is a big deal here though.

Comment (EliteTK) [reply crates/uv/src/commands/help.rs]: @zanieb fair enough. I hadn't thought of it like that.

I've done the refactor now though. I think it looks a lot cleaner overall. Although the commit message is no longer that accurate. I can update the commit message or split it.

I also understand that it's kind of beyond the scope of this one fix too, I'd be happy to split the PRs if you would prefer to keep this one about just adding the title (no bold) and removing `-P`.

**Comment by EliteTK** [comment]
Regarding `-P` in `LESS`. I'd be happy to re-introduce it in a separate PR. I'd just like to spend a little bit of time understanding how that variable works and how dependable that behaviour is, to make sure it doesn't break some other less implementation.

**Comment by zanieb** [comment]
It's not a high priority so you should probably just open an issue to track the idea and move on to something else that'll build context on uv instead.
