### PR TITLE
uv-fs: transparently support reading UTF-16 files

### LINKED ISSUE #1666: Support alternative requirements file encodings
e.g. `UTF16-LE`

> This works, but `poetry export > requirements.txt` creates UTF16-LE file, while `uv pip install -r requirements.txt` expects UTF-8, so I manually need to re-save it in UTF8. It is not a problem, but would be cool if `uv` would detect input file encoding...
> 
> ```
> uv pip install -r .\requirements.txt
> error: failed to read from file `.\requirements.txt`
>   Caused by: stream did not contain valid UTF-8
> ```

_Originally posted by @Warchant in https://github.com/astral-sh/uv/issues/1634#issuecomment-1951402367_

### LINKED ISSUE #2276: uv pip wont accept my requirements file
The command I wrote:
```
uv pip install -r .\requirements.txt
```
The result:
```
error: failed to read from file `.\requirements.txt`
  Caused by: stream did not contain valid UTF-8
```
The requirements file:
```
annotated-types==0.6.0
anyio==4.3.0
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
cryptography==42.0.5
exceptiongroup==1.2.0
fastapi==0.110.0
h11==0.14.0
idna==3.6
pycparser==2.21
pydantic==2.6.3
pydantic-core==2.16.3
python-dotenv==1.0.1
requests==2.31.0
sniffio==1.3.1
starlette==0.36.3
typing-extensions==4.10.0
urllib3==2.2.1
uvicorn==0.27.1
```

Current UV version:
```
Yash ❯❯ uv --version
uv 0.1.15 (a8ac7b1eb 2024-03-05)
```

Operating System: Windows 

This works when I use pip but not with UV. I tried to look for a similar issue but couldn't find one. If this is a duplicate, I apologise. Would you be so kind to give me a link to the issue where the solution for this is discussed? Thanks!

### PR DESCRIPTION
**Pull request by BurntSushi**
This PR tweaks uv to support reading `requirements.txt` regardless of
whether it is encoded as UTF-8 or UTF-16. This is particularly relevant
on Windows where `uv pip freeze > requirements.txt` will likely write a
UTF-16 encoded `requirements.txt` file.

There is some discussion on #1666 where it's suggested that perhaps
we should explicitly not support this. I didn't see that until I
had already put this PR together, but even so, I think it's worth
considering this. UTF-16 is predominant on Windows. It is very easy
to produce a UTF-16 encoded file. Moreover, there is an easy and well
specified way to recognize and transcode UTF-16 encoded data to UTF-8.

I think the downside of this is that it could encourage the use UTF-16
encoded `requirements.txt` files *in addition* to UTF-8 encoded
files, and it would probably be nice to converge and standardize on
one encoding. One possible alternative to this PR is that we provide
a better error message. Another alternative is to ensure that a
`-o/--output` flag exists for all commands (neither `uv pip freeze` nor
`pip freeze` have such a flag) so that users can always write output
to a file without relying on their environment's piping behavior.
(Although this last alternative seems a little sad to me.)

It's also worth noting the [PEP-0508] doesn't seem to mention file
encoding at all. So I think from a "do the standards allow this"
perspective, this change is OK.

Finally, `pip` itself seems to work with UTF-16 encoded
`requirements.txt` files.

I think I personally overall lean towards supporting UTF-16 for
`requirements.txt` files. In part because I think it smoothes out the
UX a little bit, in part because there is no obvious specification
(that I'm aware of) that mandates that these files are UTF-8, and
finally in part because `pip` supports it too.

Fixes #1666, Fixes #2276

[PEP-0508]: https://peps.python.org/pep-0508/

### CODE REVIEW

**Comment by BurntSushi** [comment]
cc @zanieb @mitsuhiko given discussion in #1666 about supporting UTF-16 encoded `requirements.txt` files.

cc @yashranjan1 [per request](https://github.com/astral-sh/uv/issues/2276#issuecomment-1983903059).

**Review by zanieb — APPROVED** [review]
👍 I agree with your principles

**Review by charliermarsh — APPROVED** [review]

**Comment by charliermarsh** [comment]
I think it's wise to support these as long as PowerShell is going to use UTF-16 by default when piping -- that's a very common use-case.

File: crates/uv-fs/src/lib.rs [hunk 1]
```diff
@@ -19,13 +19,22 @@ mod path;
 pub async fn read_to_string(path: impl AsRef<Path>) -> std::io::Result<String> {
```
Comment (MichaReiser) [inline crates/uv-fs/src/lib.rs:19]: Are there call sites to this function for which we may not want to accept UTF-16? 

I suggest to at least document that this function supports UTF16 decoding.

File: Cargo.toml [hunk 2]
```diff
@@ -41,6 +41,7 @@ derivative = { version = "2.2.0" }
 directories = { version = "5.0.1" }
 dunce = { version = "1.0.4" }
 either = { version = "1.9.0" }
+encoding_rs_io = { version = "0.1.7" }
```
Comment (MichaReiser) [inline Cargo.toml:44]: Could you expand your reasoning for using `encoding_rs` (shamelessly adding his own crates ;) ) instead of implementing a "simple" BOM check to determine UTF-16 and using `String::from_utf16`?

File: crates/uv-fs/src/lib.rs [hunk 3]
```diff
@@ -19,13 +19,22 @@ mod path;
...
     if path == Path::new("-") {
         let mut buf = String::with_capacity(1024);
-        std::io::stdin().read_to_string(&mut buf)?;
+        DecodeReaderBytes::new(std::io::stdin()).read_to_string(&mut buf)?;
         Ok(buf)
     } else {
-        fs_err::tokio::read_to_string(path).await
+        let path = path.to_path_buf();
+        tokio::task::spawn_blocking(move || {
+            let mut buf = String::with_capacity(1024);
```
Comment (MichaReiser) [inline crates/uv-fs/src/lib.rs:32]: What's your reasoning behind spawning a background task for reading the file. My understanding of the use case is that a) we read the file as input before there's much async work anyway, b) the files are small text files. That makes me wonder if it's worth to decode and read the file on another thread (scheduling overhead etc).

File: crates/uv-fs/src/lib.rs (hunk 1 above)
Comment (BurntSushi) [reply crates/uv-fs/src/lib.rs:19]: Yeah, I'll probably split this into two functions so that callers can specifically opt into it.

File: Cargo.toml (hunk 2 above)
Comment (BurntSushi) [reply Cargo.toml:44]: `encoding_rs` isn't mine, but `encoding_rs_io` is. The latter puts an automatic BOM sniffing streaming reader on top of the former.

I suppose since we don't actually need streaming here, so this could be done more simply. Note though that `encoding_rs_io` will also seamlessly handle the UTF-8 BOM, which is not uncommon on Windows AFAIK. (Handling the UTF-8 BOM is basically just a matter of detecting it and then dropping it.)

I'll consider just using `std` for this. Honestly we have so many dependencies (including a dependency on `encoding_rs`) that I don't feel too bad about adding another...

File: crates/uv-fs/src/lib.rs (hunk 3 above)
Comment (BurntSushi) [reply crates/uv-fs/src/lib.rs:32]: It's an `async` function and file I/O is blocking. So IMO, that means it should be spawned as a blocking task. Moreover, the code being replaced was also spawning a blocking task (it was just done inside of `tokio`), so this is maintaining that status quo. It's plausible that this isn't necessary in a holistic sense, but this particular routine isn't necessarily limited to use during startup.

**Review by MichaReiser — APPROVED** [review]

File: Cargo.toml (hunk 2 above)
Comment (BurntSushi) [reply Cargo.toml:44]: Yeah it's really about supporting streaming. That's the main win of `encoding_rs_io`.

**Comment by mitsuhiko** [comment]
I _believe_ that Microsoft is slowly phasing out UTF-16 output on the console. On my machine it only outputs UTF-8 (Windows 11). Might be worthwhile figuring out if this is really something that happens regularly and will continue to do so.

**Comment by BurntSushi** [comment]
> I _believe_ that Microsoft is slowly phasing out UTF-16 output on the console. On my machine it only outputs UTF-8 (Windows 11). Might be worthwhile figuring out if this is really something that happens regularly and will continue to do so.
> 
> //EDIT: now I realize that this is because i use `cmd.exe` and not powershell

This is interesting because I think [Rust is the one who is writing UTF-16 to the console](https://github.com/rust-lang/rust/blob/52f8aec14c616387c5f793687f2d9026de6c78ca/library/std/src/sys/pal/windows/stdio.rs#L175-L229). Is that somehow getting transcoded back to UTF-8 for you?

**Comment by mitsuhiko** [comment]
@BurntSushi this is what it does on my machine:

```
C:\Users\armin\Development\foo>cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target\debug\foo.exe`
Fußball

C:\Users\armin\Development\foo>cargo run > foo.txt
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target\debug\foo.exe`

C:\Users\armin\Development\foo>python -c "print(open('foo.txt', 'rb').read())"
b'Fu\xc3\x9fball\n'
```

File: crates/uv-fs/src/lib.rs (hunk 3 above)
Comment (konstin) [reply crates/uv-fs/src/lib.rs:32]: In general, i agree, in this specific place we're not doing anything else in parallel (we're not a webserver where we have other clients meanwhile) and the work is tiny, so i'd go for simplicity. I'd probably do a `fs_err::tokio::read` and then convert it using the other reader, even the double read should be far to small to show up in profiles.

File: crates/uv/tests/pip_install.rs [hunk 4]
```diff
@@ -2419,3 +2419,105 @@ fn no_build_isolation() -> Result<()> {
...
+
+/// This tests that `uv` can read UTF-16LE encoded requirements.txt files.
+///
+/// Ref: <https://github.com/astral-sh/uv/issues/2276>
+#[test]
+fn install_utf16le_requirements() -> Result<()> {
+    let context = TestContext::new("3.12");
+    let requirements_txt = context.temp_dir.child("requirements.txt");
+    requirements_txt.touch()?;
+    requirements_txt.write_binary(&utf8_to_utf16_with_bom_le("black==24.2.0"))?;
```
Comment (konstin) [inline crates/uv/tests/pip_install.rs:2431]: Could you use `tomli`? This should be faster

File: crates/uv/tests/pip_install.rs [hunk 5]
```diff
@@ -2419,3 +2419,105 @@ fn no_build_isolation() -> Result<()> {
...
+
+    uv_snapshot!(command_without_exclude_newer(&context)
+        // This tests what we want because BOTH of the following
+        // are true: `black` is on pypi.org and test.pypi.org, AND
+        // `black==24.2.0` is on pypi.org and NOT test.pypi.org. So
+        // this would previously check for `black` on test.pypi.org,
+        // find it, but then not find a compatible version. After
+        // the fix, `uv` will check pypi.org first since it is given
+        // priority via --extra-index-url.
```
Comment (konstin) [inline crates/uv/tests/pip_install.rs:2440]:
```suggestion
```

File: crates/uv/tests/pip_install.rs [hunk 6]
```diff
@@ -2419,3 +2419,105 @@ fn no_build_isolation() -> Result<()> {
...
+     + black==24.2.0
+     + click==8.1.7
+     + mypy-extensions==1.0.0
+     + packaging==23.2
+     + pathspec==0.12.1
+     + platformdirs==4.2.0
+    "###
+    );
+
+    context.assert_command("import flask").failure();
```
Comment (konstin) [inline crates/uv/tests/pip_install.rs:2460]:
```suggestion
```

**Review by konstin — APPROVED** [review]

**Comment by mitsuhiko** [comment]
> This is interesting because I think [Rust is the one who is writing UTF-16 to the console](https://github.com/rust-lang/rust/blob/52f8aec14c616387c5f793687f2d9026de6c78ca/library/std/src/sys/pal/windows/stdio.rs#L175-L229). Is that somehow getting transcoded back to UTF-8 for you?

So this machine is a few months old and I'm really not sure how any of this works. What I can see on my machine:

* cmd.exe: code page 65001
* powershell.exe: code page 65001
* cmd.exe launched from powershell: code page 1252

No clue why it does that. I tried on a VM and it always shows me code page 1252. No matter though how, powershell always transcodes to UTF-16 but that is also reconfigurable with a flag (that probably nobody ever sets). Whatever API Python and Rust use to write, it clearly transcodes somehow somewhere.

**Comment by MichaReiser** [comment]
> (that probably nobody ever sets).

I did :laughing:

File: crates/uv-fs/src/lib.rs (hunk 3 above)
Comment (BurntSushi) [reply crates/uv-fs/src/lib.rs:32]: I went with @konstin's suggestion.

File: Cargo.toml (hunk 2 above)
Comment (BurntSushi) [reply Cargo.toml:44]: I looked into this, and it turns out the [UTF-16LE and UTF-16BE APIs](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf16be) are actually unstable. Do'h. That means doing this correctly is a fair bit more work than just checking the BOM and calling the right routine. We'd have to flip the byte order for an endian mismatch.

`encoding_rs_io` is a small battle tested dependency and it does the right thing for us automatically here, so I'm going to keep it.

File: crates/uv-fs/src/lib.rs (hunk 1 above)
Comment (BurntSushi) [reply crates/uv-fs/src/lib.rs:19]: I split it into two functions. This was also being used to read `pyproject.toml`, and it's not obvious to me that we should support UTF-16 there. So that behavior remains unchanged.

**Comment by BurntSushi** [comment]
I'm going to bring this in given most folks seem to be in support of it. Moreover, it addresses an easy footgun for an existing common pip workflow: `uv pip freeze > requirements.txt` is likely to produce a UTF-16 file on Windows, although there are perhaps configurations and environments where that is not true. Still, it doesn't cost us much to support UTF-16 here.
