### PR TITLE
Retry request on invalid data error

### LINKED ISSUE #14699: `uv python install` fails to extract archive with "cannot decrypt peer's message"
### Summary

Trying to install python on Windows. My unstable Wi-Fi connection may have something to do with it. It downloads for a few seconds, but randomly fails with this error message. I managed to get lucky running it once where it finished downloading without erroring out and it installed fine, but since then I haven't been able to install another version after trying it 10+ times (it always errored out sometime before it finished)

```
 >uv python install 3.10 -vv
DEBUG uv 0.8.0 (0b2357294 2025-07-17)
TRACE Checking lock for `C:\Users\char\AppData\Roaming\uv\python` at `C:\Users\char\AppData\Roaming\uv\python\.lock`
DEBUG Acquired lock for `C:\Users\char\AppData\Roaming\uv\python`
TRACE Found existing installation cpython-3.13.5-windows-x86_64-none
DEBUG No installation found for request `Python 3.10`
DEBUG Found download `cpython-3.10.18-windows-x86_64-none` for request `Python 3.10`
DEBUG Using request timeout of 30s
DEBUG Downloading https://github.com/astral-sh/python-build-standalone/releases/download/20250712/cpython-3.10.18%2B20250712-x86_64-pc-windows-msvc-install_only_stripped.tar.gz
DEBUG Extracting cpython-3.10.18-20250712-x86_64-pc-windows-msvc-install_only_stripped.tar.gz to temporary location: C:\Users\char\AppData\Roaming\uv\python\.temp\.tmps53RWd
TRACE Handling request for https://github.com/astral-sh/python-build-standalone/releases/download/20250712/cpython-3.10.18%2B20250712-x86_64-pc-windows-msvc-install_only_stripped.tar.gz with authentication policy auto
TRACE Request for https://github.com/astral-sh/python-build-standalone/releases/download/20250712/cpython-3.10.18%2B20250712-x86_64-pc-windows-msvc-install_only_stripped.tar.gz is unauthenticated, checking cache
TRACE No credentials in cache for URL https://github.com/astral-sh/python-build-standalone/releases/download/20250712/cpython-3.10.18%2B20250712-x86_64-pc-windows-msvc-install_only_stripped.tar.gz
TRACE Attempting unauthenticated request for https://github.com/astral-sh/python-build-standalone/releases/download/20250712/cpython-3.10.18%2B20250712-x86_64-pc-windows-msvc-install_only_stripped.tar.gz
Downloading cpython-3.10.18-windows-x86_64-none (download) (21.4MiB)
TRACE Considering retry of error: ExtractError("cpython-3.10.18-20250712-x86_64-pc-windows-msvc-install_only_stripped.tar.gz", Io(Custom { kind: Other, error: TarError { desc: "failed to unpack `\\\\?\\C:\\Users\\char\\AppData\\Roaming\\uv\\python\\.temp\\.tmps53RWd\\python\\Lib\\site-packages\\pip\\_internal\\cli\\__pycache__\\autocompletion.cpython-310.pyc`", io: Custom { kind: Other, error: TarError { desc: "failed to unpack `python/Lib/site-packages/pip/_internal/cli/__pycache__/autocompletion.cpython-310.pyc` into `\\\\?\\C:\\Users\\char\\AppData\\Roaming\\uv\\python\\.temp\\.tmps53RWd\\python\\Lib\\site-packages\\pip\\_internal\\cli\\__pycache__\\autocompletion.cpython-310.pyc`", io: Custom { kind: Other, error: reqwest::Error { kind: Decode, source: reqwest::Error { kind: Body, source: hyper::Error(Body, Error { kind: Io(Custom { kind: InvalidData, error: "cannot decrypt peer's message" }) }) } } } } } } }))
TRACE Cannot retry IO error: not one of `ConnectionReset` or `UnexpectedEof`
TRACE Cannot retry IO error: not one of `ConnectionReset` or `UnexpectedEof`
TRACE Cannot retry IO error: not one of `ConnectionReset` or `UnexpectedEof`
TRACE Cannot retry error: not an IO error
error: Failed to install cpython-3.10.18-windows-x86_64-none
  Caused by: Failed to extract archive: cpython-3.10.18-20250712-x86_64-pc-windows-msvc-install_only_stripped.tar.gz
  Caused by: I/O operation failed during extraction
  Caused by: failed to unpack `\\?\C:\Users\char\AppData\Roaming\uv\python\.temp\.tmps53RWd\python\Lib\site-packages\pip\_internal\cli\__pycache__\autocompletion.cpython-310.pyc`
  Caused by: failed to unpack `python/Lib/site-packages/pip/_internal/cli/__pycache__/autocompletion.cpython-310.pyc` into `\\?\C:\Users\char\AppData\Roaming\uv\python\.temp\.tmps53RWd\python\Lib\site-packages\pip\_internal\cli\__pycache__\autocompletion.cpython-310.pyc`
  Caused by: error decoding response body
  Caused by: request or response body error
  Caused by: error reading a body from connection
  Caused by: cannot decrypt peer's message
DEBUG Released lock at `C:\Users\char\AppData\Roaming\uv\python\.lock`
```                                                                                                                                                                                                                                           

### Platform

Windows 10 x86_64

### Version

uv 0.8.0 (0b2357294 2025-07-17)

### Python version

N/A

### PR DESCRIPTION
**Pull request by konstin**
I also improved the trace logging.

Fixes #14699

### CODE REVIEW

File: crates/uv-client/src/base_client.rs [hunk 1]
```diff
@@ -921,17 +921,29 @@ pub fn is_extended_transient_error(err: &dyn Error) -> bool {
 
     // IO Errors may be nested through custom IO errors.
     for io_err in find_sources::<io::Error>(&err) {
-        if io_err.kind() == io::ErrorKind::ConnectionReset
-            || io_err.kind() == io::ErrorKind::UnexpectedEof
-            || io_err.kind() == io::ErrorKind::BrokenPipe
-        {
-            trace!("Retrying error: `ConnectionReset` or `UnexpectedEof`");
+        let retryable_io_err_kinds = [
```
Comment (jtfmumm) [inline crates/uv-client/src/base_client.rs:926]: Could you also do a match here? Or an `if let`, though maybe that would be harder to read

**Review by jtfmumm — APPROVED** [review]

File: crates/uv-client/src/base_client.rs (hunk 1 above)
Comment (konstin) [reply crates/uv-client/src/base_client.rs:926]: We could, but it should be the same to llvm, it's not performance critical (we hit this branch up to 3 times and only after we've done a network request) and I found it easier to read and format (I added the comments in the `if` originally, but that made Rustfmt give up on the whole block).

File: crates/uv-client/src/base_client.rs [hunk 2]
```diff
@@ -921,17 +921,29 @@ pub fn is_extended_transient_error(err: &dyn Error) -> bool {
...
         }
-        trace!("Cannot retry IO error: not one of `ConnectionReset` or `UnexpectedEof`");
+        trace!(
+            "Cannot retry IO error `{}`, not a retryable IO error kind",
+            io_err.kind()
+        );
     }
 
-    trace!("Cannot retry error: not an IO error");
+    trace!("Cannot retry error: not an extended IO error");
```
Comment (zanieb) [inline crates/uv-client/src/base_client.rs]: Can we only show this last log  if the `for` loop doesn't iterate?

**Comment by zanieb** [comment]
Thank you!

**Comment by konstin** [comment]
It looks like we have caught everything: https://github.com/astral-sh/uv/actions/runs/16370666070/job/46258004849

This should be solved by https://github.com/astral-sh/uv/pull/14718 anyway, but we also had the error handling wrong which I fixed
