### PR TITLE
Don't fail direct URL hash checking with dependency metadata

### LINKED ISSUE #12512: `uv sync` fails when using `dependency-metadata` with a URL dependency
### Summary

When using `tool.uv.dependency-metadata` to override the dependencies for a package acquired from a URL source, `uv sync` fails with the following output:

```
(uv-hash-bug) PS C:\Users\object\uv-hash-bug> uv sync
Resolved 2 packages in 52ms                                                                                                       
error: Since the package `hexdoc-hexal==0.3.0.1.0rc3.dev0 @ direct+https://github.com/vgskye/Hexal/raw/6a8700ec078ec716e368f8e17e32191a0e27bd46/docs/v/latest/remaint/dist/hexdoc_hexal-0.3.0.1.0rc3.dev0-py3-none-any.whl` comes from a direct dependency, a hash was expected but one was not found for wheel
```

### Steps to reproduce

Create a `pyproject.toml` with the following contents:

```toml
[project]
name = "uv-hash-bug"
version = "0.1.0"
requires-python = "~=3.12.0"
dependencies = [
    "hexdoc-hexal",
]

[tool.uv]
dependency-metadata = [
    { name = "hexdoc-hexal", version = "0.3.0.1.0rc3.dev0", requires-dist = [] },
]

[tool.uv.sources]
hexdoc-hexal = { url = "https://github.com/vgskye/Hexal/raw/6a8700ec078ec716e368f8e17e32191a0e27bd46/docs/v/latest/remaint/dist/hexdoc_hexal-0.3.0.1.0rc3.dev0-py3-none-any.whl" }
```

Then run `uv sync`.

If the `dependency-metadata` block is commented out, `uv sync` works as expected.

### Logs

[sync.log](https://github.com/user-attachments/files/19492072/sync.log)

### Platform

Windows 11 Education 24H2 x86_64

### Version

uv 0.6.10 (f2a2d982b 2025-03-25)

### Python version

Python 3.12.9

### PR DESCRIPTION
**Pull request by konstin**
Fixes #12512

### CODE REVIEW

File: crates/uv-distribution/src/distribution_database.rs [hunk 1]
```diff
@@ -443,14 +434,32 @@ impl<'a, Context: BuildContext> DistributionDatabase<'a, Context> {
         // TODO(charlie): Request the hashes via a separate method, to reduce the coupling in this API.
         if hashes.is_generate(dist) {
```
Comment (konstin) [inline crates/uv-distribution/src/distribution_database.rs:435]: I don't understand why index deps works direct deps, but this does fix it?

**Review by charliermarsh — APPROVED** [review]
