### PR TITLE
Ensure virtual environment is compatible with interpreter on sync

### LINKED ISSUE #12461: `uv sync` with upgraded system Python version fails to update `activate_this.py`
### Summary

An uv virtual environment using the system Python version embeds a reference to the Python minor version number in `activate_this.py`.

```console
$ docker run --rm -it ubuntu:22.04
# apt update
# apt install -y curl python3 python3.11
# curl -LsSf https://astral.sh/uv/install.sh | sh
# source $HOME/.local/bin/env
# uv init --no-pin-python app
# cd app
# uv add numpy
# grep site-packages .venv/bin/activate_this.py 
for lib in "../lib/python3.10/site-packages".split(os.pathsep):
```

If we then upgrade the system’s Python version (simulated here by changing the `/usr/bin/python3` symlink, but an OS upgrade has the same effect), `uv sync` correctly installs wheels for the new Python version, but incorrectly leaves `activate_this.py` unchanged.

```console
# ln -nsf python3.11 /usr/bin/python3
# uv sync
# uv run python -c 'import numpy; print(numpy)'
<module 'numpy' from '/app/.venv/lib/python3.11/site-packages/numpy/__init__.py'>
# grep site-packages .venv/bin/activate_this.py
for lib in "../lib/python3.10/site-packages".split(os.pathsep):
```

There are ways to force it to fix `activate_this.py`, e.g. `uv sync -p python3.10; uv sync -p python3.11` (both commands are necessary). However, a simple `uv sync` ought to automatically update `activate_this.py` without further workarounds.

### Platform

Ubuntu 22.04 amd64

### Version

uv 0.6.9

### Python version

Python 3.10.12

### PR DESCRIPTION
**Pull request by jtfmumm**
It was possible that a virtual environment became out of sync with the interpreter it pointed to (for example, if a symlink was changed to an updated Python version). In such a case, `pyvenv.cfg` and `activate_this.py` would no longer be correct. This PR detects when the `version` (`venv` module) or `version_info` (uv and `virtualenv`) field in `pyvenv.cfg` is out of sync with the interpreter. In such a case, uv recreates the virtual environment.

Closes #12461

### CODE REVIEW

File: crates/uv/src/commands/project/mod.rs [hunk 1]
```diff
@@ -804,21 +803,23 @@ impl ProjectInterpreter {
...
-                        true
-                    } else {
-                        debug!(
-                            "The virtual environment's Python version does not satisfy `{}`",
-                            request.to_canonical_string()
-                        );
-                        false
-                    }
-                }) {
+                if venv.matches_interpreter(venv.interpreter())
```
Comment (konstin) [inline crates/uv/src/commands/project/mod.rs:806]: Can we have a dedicated log message for venv-interpreter-version-mismatch?

**Review by konstin — APPROVED** [review]

File: crates/uv/src/commands/project/mod.rs (hunk 1 above)
Comment (jtfmumm) [reply crates/uv/src/commands/project/mod.rs]: Added

File: crates/uv-python/src/environment.rs [hunk 2]
```diff
@@ -355,4 +355,12 @@ impl PythonEnvironment {
                 .unwrap_or(false)
         }
     }
+
+    /// Returns true if the virtual environment has the same `pyvenv.cfg`
+    /// version as the interpreter Python version. Also returns true if
+    /// there is no `pyvenv.cfg` file.
```
[the remark this answers is not in the document]
Comment (jtfmumm) [reply crates/uv-python/src/environment.rs]: I updated the comment to indicate that **if** this is a virtual environment, we compare the `pyvenv.cfg` version. Otherwise, we return `true`.
