### PR TITLE
Fall back to streaming wheel when `Content-Length` header is absent

### LINKED ISSUE #4993: uv requires Content-Length Header on wheels, breaking compatibility with some package repositories
When using uv as a drop-in replacement for pip, I encountered an issue where uv fails to download packages from a custom package repository due to the absence of the Content-Length Header in the response. The registry is getting proxied by nginx and it seems that strips that header(I unfortunately can't change that fact).

## Steps to reproduce:

- Install uv and create a virtual environment.
- Run the command `uv pip install --index-url <custom_repository_url> <package_name>`(You need a server that doesn't send the `Content-Length` header)
- Observe the error message indicating that the Content-Length Header is missing from the response.
* Tested UV platform: Windows, Tried on Linux too
* Used UV version: uv 0.2.24 (527b711bc 2024-07-10)

### Error message:

```
error: Failed to download <package_name>
  Caused by: content-length header is missing from response
```

### Response headers:

The response headers from the custom package repository do not include the Content-Length Header, as shown below:

```
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 11 Jul 2024 14:38:49 GMT
Content-Type: binary/octet-stream
Transfer-Encoding: chunked
Connection: keep-alive
Accept-Ranges: bytes
Cache-Control: max-age=0, private, must-revalidate
Etag: "9b2d35955a25abe3acb5c94aa54ad3b1"
Last-Modified: Thu, 11 Jul 2024 14:34:01 GMT
Vary: Origin
Referrer-Policy: strict-origin-when-cross-origin
Strict-Transport-Security: max-age=31536000; includeSubDomains
```

### Expected behavior:

uv should be able to download packages from custom package repositories even if the Content-Length Header is not present in the response. pip does not require this header, and uv should strive to maintain compatibility with pip.

### Suggested solution:

Consider adding support for downloading packages without the Content-Length Header, or provide an option to disable the requirement for this header. This would allow uv to work seamlessly with custom package repositories that do not provide this header.

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Closes https://github.com/astral-sh/uv/issues/4993

### CODE REVIEW

File: crates/uv-client/src/error.rs [hunk 1]
```diff
@@ -61,6 +61,14 @@ impl Error {
                 return true;
             }
 
+            // The server doesn't support rage requests (it doesn't return the necessary headers).
```
Comment (hoechenberger) [inline crates/uv-client/src/error.rs:64]: I think you meant a range request here 😄

Comment (zanieb) [reply crates/uv-client/src/error.rs:64]: haha :)
