### PR TITLE
Fix patching of `clang` in managed Python sysconfig

### LINKED ISSUE #13236: `uv>=0.6.15` does not replace `clang` in `sysconfig` during installation.
### Summary

#8429
It seems the problem has reappeared in v0.6.15.

```bash
curl -LsSf https://astral.sh/uv/0.16.14/install.sh | sh
uv python install --managed-python 3.13
uv run --python 3.13 --managed-python -m sysconfig | grep "CC ="
#         CC = "cc -pthread"
#         LINKCC = "cc -pthread -fno-pie -no-pie"
uv run --python 3.13 --managed-python -m sysconfig | grep "CXX ="
#         CXX = "c++ -pthread"
uv self update 0.6.15
uv python install --reinstall --managed-python 3.13
uv run --python 3.13 --managed-python -m sysconfig | grep "CC ="
#         CC = "clang -pthread"
#         LINKCC = "cc -pthread -fno-pie -no-pie"
uv run --python 3.13 --managed-python -m sysconfig | grep "CXX ="
#         CXX = "clang++ -pthread"
```

This issue still exists in at least 0.7.1.

### Platform

Ubuntu 20.04

### Version

0.6.15

### Python version

_No response_

### PR DESCRIPTION
**Pull request by zanieb**
Regressed in https://github.com/astral-sh/uv/pull/12239/files#r2069106892 because additional entries override the previous one in the mapping. Now, we can apply multiple patches in-order.

Closes #13236

### CODE REVIEW

File: crates/uv-python/src/sysconfig/mod.rs [hunk 1]
```diff
@@ -296,8 +294,10 @@ fn patch_sysconfigdata(mut data: SysconfigData, real_prefix: &Path) -> Sysconfig
         let patched = update_prefix(value, real_prefix);
         let mut patched = remove_isysroot(&patched);
 
-        if let Some(replacement_entry) = DEFAULT_VARIABLE_UPDATES.get(key) {
-            patched = replacement_entry.patch(&patched);
+        if let Some(replacement_entries) = DEFAULT_VARIABLE_UPDATES.get(key) {
+            for replacement_entry in replacement_entries {
+                patched = replacement_entry.patch(&patched);
```
Comment (charliermarsh) [inline crates/uv-python/src/sysconfig/mod.rs:299]: Should we break on first match?

**Review by charliermarsh — APPROVED** [review]

**Comment by samypr100** [comment]
Thanks for fixing @zanieb 🙌
