### PR TITLE
Fix handling of `python install --default` for pre-release Python versions

### LINKED ISSUE #16696: uv python install <ver> --default works for 3.12 and 3.14 but not 3.15
### Summary

When I run `uv python install 3.12 --default`, it installs `python3.12.exe` and `python.exe` and `python3.exe`.
The same is true for 3.14
But for 3.15, it only installs `python3.15.exe`, not `python.exe` and `python3.exe`.
I couldn't see any warning.
I tried adding --verbose, and there was no hint that it even attempted to link `python3.exe` or `python.exe`.
I couldn't see any information in the docs about some versions being unsuitable for default use.

### Platform

Windows 11 x86_64

### Version

10.0.26100 Build 26100

### Python version

3.12, 3.14, 3.15

### PR DESCRIPTION
**Pull request by nooscraft**
## Summary

Fixes `--default` not creating default executable links for pre-release Python versions.

When using `--default` with a pre-release version like `3.15.0a1`, the code was checking `matches_installation()` against the download request instead of the original user request. This caused the check to fail since the download request doesn't match pre-release versions the same way.

Changed it to use `installation.satisfies(&first_request.request)` when `--default` is used, which checks against the original user request.

Fixes #16696

## Test Plan

Added `python_install_default_prerelease` test that installs Python 3.15 with `--default` and verifies all three executable links (`python3.15`, `python3`, `python`) are created. The test skips gracefully if 3.15 isn't available.

All existing tests pass.

### CODE REVIEW

File: crates/uv/src/commands/python/install.rs [hunk 1]
```diff
@@ -774,10 +774,21 @@ fn create_bin_links(
...
+            // When --default is used, check if the installation satisfies the original user request.
+            // This allows pre-release versions (e.g., 3.15.0a1) to be set as default when the user
+            // explicitly requested that version (e.g., "3.15"), even though the download request
+            // may not allow pre-releases.
+            installation.satisfies(&first_request.request)
+        } else {
+            // For is_default_install, use the download request matching to ensure consistency
+            // with the download selection logic.
+            first_request.matches_installation(installation)
+        };
```
Comment (zanieb) [inline crates/uv/src/commands/python/install.rs]: When `--default` is used, we'll only allow one request anyway, right? so we could skip the check entirely?

Comment (nooscraft) [reply crates/uv/src/commands/python/install.rs]: @zanieb you're right. Since `--default` only allows one request, all installations in the loop already match that request, so the check is redundant. I've simplified it to skip the check when default is true. All tests still pass.

**Comment by zanieb** [comment]
Sorry another question here... isn't the entire `first_request` matching meaningless then? Can we just remove that.. ?

**Comment by nooscraft** [comment]
> Sorry another question here... isn't the entire `first_request` matching meaningless then? Can we just remove that.. ?

Yes, When is_default_install is true, there's only one request and all installations in the loop already match it, so the check was redundant.
I've removed the `first_request.matches_installation(installation)` check and the unused `first_request` variable. The code now just checks `default || (is_default_install && preview.is_enabled(...))`.

File: crates/uv/tests/it/python_install.rs [hunk 2]
```diff
@@ -2255,6 +2255,56 @@ fn python_install_broken_link() {
...
+    let Ok(output) = context
+        .python_install()
+        .arg("--default")
+        .arg("--preview-features")
+        .arg("python-install-default")
+        .arg("3.15")
+        .output()
+    else {
+        return; // Skip test if command fails
+    };
```
Comment (zanieb) [inline crates/uv/tests/it/python_install.rs]: We should `.assert().success()` here instead. 3.15 _is_ available, we shouldn't let the test silently fail.

File: crates/uv/tests/it/python_install.rs [hunk 3]
```diff
@@ -2255,6 +2255,56 @@ fn python_install_broken_link() {
...
+        .bin_dir
+        .child(format!("python{}", std::env::consts::EXE_SUFFIX));
+
+    // Verify that all three executables are created when --default is used with a pre-release version
+    bin_python_minor_15.assert(predicate::path::exists());
+    bin_python_major.assert(predicate::path::exists());
+    bin_python_default.assert(predicate::path::exists());
+
+    // Clean up
+    let _ = context.python_uninstall().arg("--all").output();
```
Comment (zanieb) [inline crates/uv/tests/it/python_install.rs]: We don't need this, the tests run in isolated contexts

File: crates/uv/tests/it/python_install.rs [hunk 4]
```diff
@@ -2255,6 +2255,56 @@ fn python_install_broken_link() {
     });
 }
 
+#[test]
+fn python_install_default_prerelease() {
+    // Test that --default works with pre-release versions (e.g., 3.15.0a1).
+    // This test verifies the fix for issue #16696 where --default didn't create
+    // python.exe and python3.exe links for pre-release versions.
```
Comment (zanieb) [inline crates/uv/tests/it/python_install.rs]: This belongs in a doc comment `/// ` above the function

File: crates/uv/tests/it/python_install.rs (hunk 2 above)
Comment (nooscraft) [reply crates/uv/tests/it/python_install.rs]: Yup, fixed this!

File: crates/uv/tests/it/python_install.rs (hunk 3 above)
Comment (nooscraft) [reply crates/uv/tests/it/python_install.rs]: Done!

File: crates/uv/tests/it/python_install.rs (hunk 4 above)
Comment (nooscraft) [reply crates/uv/tests/it/python_install.rs]: Moved to doc comment

**Review by zanieb — APPROVED** [review]

**Comment by zanieb** [comment]
Thanks!
