### PR TITLE
Use a global build concurrency semaphore

### LINKED ISSUE #15307: UV_BUILD_CONCURRENCY not working
### Summary

Hi, my goal is to have uv build only a single package at a time to prevent out of memory bugs.

```
export UV_CONCURRENT_BUILDS=1
uv sync --locked
```

However uv spawns multiple build processes (bdist_wheel, setuptools)
```
pstree $$
uv─┬─python───python───python───cmake───ninja───sh───x86_64-linux-gn───cc1plus
   ├─python───cmake───gmake───gmake───gmake───sh───c++───cc1plus
   └─22*[{uv}]
```

```
uv self version
uv 0.8.8
uname -a
Linux ubuntu 6.8.0-71-generic #71-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 22 16:52:38 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
```

Am I misunderstanding the setting or might this be a bug?

### Platform

Linux 6.8.0-71-generic x86_64 GNU/Linux

### Version

uv 0.8.8

### Python version

Python 3.12.3

### PR DESCRIPTION
**Pull request by konstin**
Previously, each build was using its own build concurrency limit, effectively rendering the limit useless.

Fixes #15307

### CODE REVIEW

File: crates/uv-build-frontend/src/lib.rs [hunk 1]
```diff
@@ -214,11 +213,23 @@ impl Pep517Backend {
     }
 }
 
-/// Uses an [`Rc`] internally, clone freely.
-#[derive(Debug, Default, Clone)]
+/// Uses an [`Arc`] internally, clone freely.
```
Comment (konstin) [inline crates/uv-build-frontend/src/lib.rs:216]: Using an `Arc` in the expectation that we want to share the currency limits globally, and its cost wrt to `Rc` is negligible.

File: crates/uv-build-frontend/src/lib.rs [hunk 2]
```diff
@@ -214,11 +213,23 @@ impl Pep517Backend {
...
+#[derive(Debug, Clone)]
 pub struct SourceBuildContext {
     /// An in-memory resolution of the default backend's requirements for PEP 517 builds.
-    default_resolution: Rc<Mutex<Option<Resolution>>>,
+    default_resolution: Arc<Mutex<Option<Resolution>>>,
+    /// A shared semaphore to limit the number of concurrent builds.
+    concurrency: Arc<Semaphore>,
```
Comment (EliteTK) [inline crates/uv-build-frontend/src/lib.rs]: Somewhat of a nitpick maybe: I think `concurrency` is a bit confusing for a name for this. There's `PythonRunner` where this is called `control`. While I'm not a fan of `control` either, it seems a bit less confusing. I'd maybe suggest something like `build_job_slots` or something. We use `concurrency` in a bunch of places to refer to `uv_configuration::Concurrency`.

**Review by EliteTK — APPROVED** [review]
The change on its own is fine. But seeing this spread out all over the place I kind of worry about the potential of accidentally ending up with a deadlock. But that's maybe a topic for a different issue/PR.
