### PR TITLE
Respect installed packages in `uv run`

### LINKED ISSUE #3601: uv run can install two versions of the same package (and forces upgrades)
I was trying out different versions of pytest with a pytest plugin to see when it was broken. I mentally was thinking of `uv run` as the Python launcher for UNIX, a way to avoid activating a venv (`py` instead of `.venv/bin/python`). It seems to do some installing automatically - including three strange things:

```console
$ uv venv
$ uv pip install -e .
$ uv pip install 'pytest==7.0.*'
$ uv run pytest
warning: `uv run` is experimental and may change without warning.
Resolved 5 packages in 8ms
   Built pytest-github-actions-annotate-failures @ file:///Users/henryschreiner/git/software/pytest-github-actions-annotate-failures                                                                    Downloaded 1 package in 1.25s
Installed 2 packages in 33ms
 - pytest==7.0.1
 + pytest==8.2.0
 - pytest-github-actions-annotate-failures==0.2.0 (from file:///Users/henryschreiner/git/software/pytest-github-actions-annotate-failures)
 + pytest-github-actions-annotate-failures==0.2.0 (from file:///Users/henryschreiner/git/software/pytest-github-actions-annotate-failures)
... pytest output ...
```

At this point, I hadn't noticed it had forcibly upgraded the pytest I was testing to the latest version, so I thought 7.0.x worked. (Some else in parallel found it was 7.4 that broke us).

Then the next line caught me by surprise, it uninstalls two pytests:

```console
$ uv pip install 'pytest==6.*'
Resolved 7 packages in 145ms
Downloaded 2 packages in 68ms
Installed 2 packages in 6ms
 - pytest==7.0.1
 - pytest==8.2.0
 + pytest==6.2.5
 + toml==0.10.2
```

And finally, the final `uv run` actually works just fine, and doesn't upgrade pytest:

```console
$ uv run pytest
... pytest output ...
```

### PR DESCRIPTION
**Pull request by charliermarsh**
Closes #3601.

### CODE REVIEW

File: crates/uv/src/commands/project/lock.rs [hunk 1]
```diff
@@ -40,6 +41,9 @@ pub(crate) async fn lock(
     // Discover or create the virtual environment.
     let venv = project::init(&project, cache, printer)?;
 
+    // Determine the set of installed packages.
+    let site_packages = SitePackages::from_executable(&venv)?;
```
Comment (zanieb) [inline crates/uv/src/commands/project/lock.rs:45]: Should locking prefer installed packages? We don't do this in `pip compile`.

**Review by zanieb — APPROVED** [review]

File: crates/uv/src/commands/project/lock.rs (hunk 1 above)
Comment (charliermarsh) [reply crates/uv/src/commands/project/lock.rs:45]: Not sure...

Comment (charliermarsh) [reply crates/uv/src/commands/project/lock.rs:45]: Removed.
