### PR TITLE
Noisily allow redundant entries in `tool.uv.build-backend.module-name`

### LINKED ISSUE #16906: `invalid Zip archive: Duplicate filename` on duplicated `module-name`
### Summary

`uv init --lib test`

Edit `pyproject.toml`:
```
...
[tool.uv.build-backend]
module-name = ["test_lib", "test_lib"]
```

```
❯ uv build
Building source distribution (uv build backend)...
Building wheel from source distribution (uv build backend)...
  × Failed to build `/var/tmp/pote-lib`
  ├─▶ Failed to write wheel zip archive
  ╰─▶ invalid Zip archive: Duplicate filename
```

It took me some time to find the issue during an internal migration to uv. Printing the module name in the error message would greatly improve the experience. 

### Platform

Linux 6.8.0-47-generic x86_64 GNU/Linux

### Version

uv 0.9.11

### Python version

_No response_

### PR DESCRIPTION
**Pull request by EliteTK**
## Summary

Fix #16906 by pruning modules or submodules which are already included (either directly, or through a parent).

Generates warnings when this happens.

Example:

```bash session
$ uv build
Building source distribution (uv build backend)...
warning: Ignoring redundant module name(s): test_lib.bar test_lib test_lib.bar.baz test_lib.baz
Building wheel from source distribution (uv build backend)...
Successfully built dist/test-0.1.0.tar.gz
Successfully built dist/test-0.1.0-py3-none-any.whl
```

## Test Plan

Added some unit tests for the pruning function and one for the whole build backend. Added an integration test for the warnings. Ran the full test suite. Manually tested.

The unit test for the function doesn't cater for the fact that it doesn't guarantee an order at the moment. I think this is fine.

## Outstanding/Questions

* Figure out how to only present warnings when appropriate (when building something the user controls).

### CODE REVIEW

File: crates/uv-build-backend/src/lib.rs [hunk 1]
```diff
@@ -191,6 +192,49 @@ fn check_metadata_directory(
...
+            if name == *last {
+                warn_user_once!("Ignoring duplicate module name {name}");
+                continue;
+            }
+            // This is a more specific (narrow) module name than what came before
+            if name
+                .strip_prefix(last)
+                .is_some_and(|suffix| suffix.starts_with('.'))
+            {
+                warn_user_once!("Ignoring module name {name}: already including {last}");
```
Comment (konstin) [inline crates/uv-build-backend/src/lib.rs]: We only show this warning if it's a source distribution the user controls, not for e.g. arbitrary packages from PyPI. The best proxy to use for this is `SourceStrategy`, if it's enabled we consider it something to warn about.

File: crates/uv-build-backend/src/lib.rs [hunk 2]
```diff
@@ -1414,4 +1458,136 @@ mod tests {
         simple_namespace_part-1.0.0.dist-info/WHEEL
         ");
     }
+
+    /// `prune_redundant_modules` should remove modules which are already
+    /// included (either directly or via their parent)
+    #[test]
+    fn test_prune_redundant_modules() {
+        fn svec(v: &[&str]) -> Vec<String> {
```
Comment (konstin) [inline crates/uv-build-backend/src/lib.rs]: We don't usually use single character names for functions. An easier approach here would be a function with two arguments that does the assert inside it.

Comment (EliteTK) [reply crates/uv-build-backend/src/lib.rs]: Thanks for the suggestion. I've changed this.

File: crates/uv-build-backend/src/lib.rs (hunk 1 above)
Comment (EliteTK) [reply crates/uv-build-backend/src/lib.rs]: Does `uv-build` have enough information to determine the `SourceStrategy`?

Comment (konstin) [reply crates/uv-build-backend/src/lib.rs]: Every time we call `uv-build`, the caller knows the sources strategy, which we can use, see also https://github.com/astral-sh/uv/pull/15750 for slightly different case that also checks the source strategy.

File: crates/uv-build-backend/src/lib.rs [hunk 3]
```diff
@@ -191,6 +194,56 @@ fn check_metadata_directory(
...
+    pruned
+}
+
+/// Wraps `prune_redundant_modules` with a warning when modules are ignored
+fn prune_redundant_modules_warn(names: &[String]) -> Vec<String> {
+    let pruned = prune_redundant_modules(names.to_vec());
+    if names.len() != pruned.len() {
+        let mut pruned: HashSet<_> = pruned.iter().collect();
+        let ignored = names.iter().filter(|name| !pruned.remove(name)).join(" ");
+        warn_user_once!("Ignoring redundant module name(s): {ignored}");
```
Comment (zanieb) [inline crates/uv-build-backend/src/lib.rs]: This is a nit, but we like to get the detail right instead of using "(s)"; so split the message into plural and singular forms based on the number of items. e.g., https://github.com/astral-sh/uv/blob/fd7e6d0a057f7db56b124565c92d847d411fd39e/crates/uv/src/commands/mod.rs#L197

File: crates/uv-build-backend/src/lib.rs [hunk 4]
```diff
@@ -191,6 +194,56 @@ fn check_metadata_directory(
...
+            {
+                continue;
+            }
+        }
+        pruned.push(name);
+    }
+    pruned
+}
+
+/// Wraps `prune_redundant_modules` with a warning when modules are ignored
```
Comment (zanieb) [inline crates/uv-build-backend/src/lib.rs]:
```suggestion
/// Wraps [`prune_redundant_modules`] with a warning when modules are ignored
```

File: crates/uv-build-backend/src/lib.rs (hunk 1 above)
Comment (EliteTK) [reply crates/uv-build-backend/src/lib.rs]: Alright, I've implemented this in [Make warnings conditional](https://github.com/astral-sh/uv/pull/16928/commits/9e68685882e2c579c356efa4067ee3e79ec10be2).

There are two cases where there isn't enough information for this: the hidden build-backend subcommand and the uv-build binary. So I just pass false there (and in a bunch of tests).

File: crates/uv-build-backend/src/lib.rs [hunk 5]
```diff
@@ -191,6 +194,60 @@ fn check_metadata_directory(
...
+/// Wraps [`prune_redundant_modules`] with a conditional warning when modules are ignored
+fn prune_redundant_modules_warn(names: &[String], show_warnings: bool) -> Vec<String> {
+    let pruned = prune_redundant_modules(names.to_vec());
+    if show_warnings && names.len() != pruned.len() {
+        let mut pruned: HashSet<_> = pruned.iter().collect();
+        let ignored: Vec<_> = names.iter().filter(|name| !pruned.remove(name)).collect();
+        let s = if ignored.len() == 1 { "" } else { "s" };
+        warn_user_once!(
+            "Ignoring redundant module name{s}: {}",
+            ignored.into_iter().join(" ")
```
Comment (konstin) [inline crates/uv-build-backend/src/lib.rs]:
```suggestion
            "Ignoring redundant module name{s} in `tool.uv.build-backend.module-name`: `{}`",
            ignored.into_iter().join("`, `")
```
