### PR TITLE
Adjust the process ulimit to the maximum allowed on startup

### LINKED ISSUE #16999: Bytecode compilation can fail with "too many open files" on default Ubuntu settings
### Summary

I tried to do `sudo python3 -m uv pip install --compile <a ton of packages>` and got
```
Prepared 688 packages in 51.95s
Uninstalled 13 packages in 51ms
Installed 688 packages in 571ms
error: Failed to bytecode-compile Python file in: /usr/twix/python3.12/lib/python3.12/site-packages
  Caused by: Failed to start Python interpreter to run compile script
  Caused by: Too many open files (os error 24)
```
Open files limit at this time was 1024. `ulimit -n 65536` fixed the issue but it would be nice for uv to check the limit, maybe try to increase it by itself if hard limit permits so.

### Platform

Ubuntu 20.04

### Version

uv 0.9.15

### Python version

Python 3.12.11

### PR DESCRIPTION
**Pull request by zanieb**
Closes #16999

See the commentary at https://github.com/astral-sh/uv/issues/16999#issuecomment-3641417484 for precedence in other tools.

This is non-fatal on error, but there are various scary behaviors from increased ulimit sizes so I've gated this with preview.

### CODE REVIEW

File: crates/uv-unix/src/resource_limits.rs [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+
+/// Maximum file descriptor limit to request.
+///
+/// We cap at 0x100000 (1,048,576) to match the typical Linux default (`/proc/sys/fs/nr_open`)
+/// and to avoid issues with extremely high limits.
+///
+/// `OpenJDK` uses this same cap because:
+///
+/// 1. Some code breaks if `RLIMIT_NOFILE` exceeds `i32::MAX` (despite the type being `u64`)
+/// 2. Code that iterates over all possible FDs to close them can timeout with very high limits
```
Comment (zanieb) [inline crates/uv-unix/src/resource_limits.rs]:
```suggestion
/// 2. Code that iterates over all possible FDs, e.g., to close them, can timeout
```

File: crates/uv-unix/src/resource_limits.rs [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+///
+/// `OpenJDK` uses this same cap because:
+///
+/// 1. Some code breaks if `RLIMIT_NOFILE` exceeds `i32::MAX` (despite the type being `u64`)
+/// 2. Code that iterates over all possible FDs, e.g., to close them, can timeout
+///
+/// See: <https://bugs.openjdk.org/browse/JDK-8324577>
+/// See: <https://github.com/oracle/graal/issues/11136>
+///
+/// Note: `rlim_t` is platform-specific (`u64` on Linux/macOS, `i64` on FreeBSD).
```
Comment (konstin) [inline crates/uv-unix/src/resource_limits.rs:53]: :100: for the extensive comment

File: crates/uv-unix/src/resource_limits.rs [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+const MAX_NOFILE_LIMIT: rlim_t = 0x0010_0000;
+
+/// Attempt to raise the open file descriptor limit to the maximum allowed.
+///
+/// This function tries to set the soft limit to `min(hard_limit, 0x100000)`. If the operation
+/// fails, it silently ignores the error since the default limits may still be sufficient for
+/// the current workload.
+///
+/// Returns the new soft limit on success, or the current soft limit if adjustment failed.
```
Comment (konstin) [inline crates/uv-unix/src/resource_limits.rs]: This should return an Option (or nothing, we're not using the value)

Comment (zanieb) [reply crates/uv-unix/src/resource_limits.rs]: I imagine we might use it to tune concurrency limits in the future? I think that's the general idea in the other packages.

Comment (zanieb) [reply crates/uv-unix/src/resource_limits.rs]: Returning `0` is dumb though
