### PR TITLE
Generalize detected FP environment handling on ARMv7

### LINKED ISSUE #19137: Unable to use `uv self update` on armv7 host after 0.11.0
### Summary

After 0.11.0, attempting to upgrade `uv` via `uv self update` on a 32-bit ARM host fails with:

```
$ uv self update
info: Checking for updates...
error: Failed to resolve the latest uv version
  Caused by: No version of uv found for platform `armv7-unknown-linux-gnueabihfeabihf`
```

This is reproducible on an `aarch64` host that can run 32-bit code in a fresh Debian Trixie container.

```
$ podman run --arch arm -it --rm docker.io/debian:trixie-slim /bin/sh -c 'set -x &&
	dpkg --print-architecture &&
	apt-get update >/dev/null &&
	apt-get upgrade -y >/dev/null &&
	apt-get install -y curl >/dev/null &&
	curl -LsSf https://astral.sh/uv/0.10.12/install.sh | sh &&
	. $HOME/.local/bin/env &&
	uv --version &&
	uv self update &&
	uv --version &&
	uv self update'
+ dpkg --print-architecture
armhf
+ apt-get update
+ apt-get upgrade -y
+ apt-get install -y curl
...
+ curl -LsSf https://astral.sh/uv/0.10.12/install.sh
+ sh
downloading uv 0.10.12 armv7-unknown-linux-gnueabihf
no checksums to verify
installing to /root/.local/bin
  uv
  uvx
everything's installed!

To add $HOME/.local/bin to your PATH, either restart your shell or run:

    source $HOME/.local/bin/env (sh, bash, zsh)
    source $HOME/.local/bin/env.fish (fish)
+ . /root/.local/bin/env
+ export PATH=/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ uv --version
uv 0.10.12 (armv7-unknown-linux-gnueabihf)
+ uv self update
info: Checking for updates...
success: Upgraded uv from v0.10.12 to v0.11.7! https://github.com/astral-sh/uv/releases/tag/0.11.7
+ uv --version
uv 0.11.7 (armv7-unknown-linux-gnueabihf)
+ uv self update
info: Checking for updates...
error: Failed to resolve the latest uv version
  Caused by: No version of uv found for platform `armv7-unknown-linux-gnueabihfeabihf`
```

### Platform

Linux 6.12.74+deb13+1-armmp-lpae armv7l GNU/Linux

### Version

uv 0.11.7 (armv7-unknown-linux-gnueabihf)

### Python version

Python 3.14.4

### PR DESCRIPTION
**Pull request by woodruffw**
## Summary

This is an attempt at fixing #19137. See https://github.com/astral-sh/uv/pull/19139#issuecomment-4320889645 for my understanding of the situation and motivation for this approach (versus the simpler approach in #19139).

TL;DR: we were unconditionally appending `eabihf` to all libc variants when constructing `cargo dist`-style triplets. This was incorrect for a long time, but didn't surface on hot user paths until #18674 reused that pathway for uv's own self-upgrade logic. The fix is as simple as not doing that, _except_ that we _do_ want to do it in the bare `Gnu` and `Musl` cases, since those signal FP detection errors (and we optimistically assume the user really has a hardfloat environment). So now we emit the appropriate `Musleabi`/`Musleabihf` variants and specialize the append to just the FP detection failure cases for both `Gnu` and `Musl` explicitly.

Closes #19137. Closes #19139.

## Test Plan

Added a unit test demonstrating the new `as_cargo_dist_triple` behavior.

### CODE REVIEW

**Comment by zsol** [comment]
Gotta update the docs for the `UV_LIBC` env var accordingly

File: crates/uv-platform/src/lib.rs [hunk 1]
```diff
@@ -161,8 +162,12 @@ impl Platform {
...
             (OperatingSystem::Windows, _) => Some("msvc".to_string()),
             (OperatingSystem::Linux, Libc::Some(env)) => Some({
-                // Special suffix for ARM with hardware float
-                if matches!(arch.family(), Architecture::Arm(ArmArchitecture::Armv7)) {
+                // If we've detected a bare `gnu` or `musl` environment on ARMv7,
+                // that means our floating point environment detection failed.
+                // We currently assume hard-float in that case.
+                if matches!(arch.family(), Architecture::Arm(ArmArchitecture::Armv7))
+                    && matches!(env, Environment::Gnu | Environment::Musl)
+                {
```
Comment (zanieb) [inline crates/uv-platform/src/lib.rs]: Why do we want to assume hard-float in this case?

Comment (woodruffw) [reply crates/uv-platform/src/lib.rs]: That matches the previous behavior -- `Gnu` and `Musl` signal a FP detection failure and we only offer hard-float binaries for Ruff and uv anyways, so we assume that the user really does have hard-float support and send them a binary. I _think_ that's pretty reasonable, since the number of soft-float ABI ARMv7 hosts out there (that are capable of running uv itself) should be pretty small.

The failure mode for that is that a user who _is_ running a soft-float ABI will get a SIGILL or similar when they try to run the fetched binary. But that's what already happens in the (ARMv7, musl) scenario.

Comment (woodruffw) [reply crates/uv-platform/src/lib.rs]: (But note: we could change that into a warning or a hard failure here instead, and conservatively fail. No strong opinion from me!)

Comment (zanieb) [reply crates/uv-platform/src/lib.rs]: I think we'd at least want to make the comment clear that we assume hard-float because that's the binary we provide. Unfortunately we do provide soft-float armv7 builds in python-build-standalone, so I don't think this is universally correct.

Can a hard-float host run a soft-float binary?

Why don't we do this when we handle the `Err` variant from the detection instead of here?

Comment (woodruffw) [reply crates/uv-platform/src/lib.rs]: > Unfortunately we do provide soft-float armv7 builds in python-build-standalone, so I don't think this is universally correct.

Yep, but IIUC this pathway doesn't get used for PBS, only for the `uv format` and uv self update flows. I can update the comments to cover that nuance too.

> Can a hard-float host run a soft-float binary?

I believe so -- my understanding is that `eabihf` is a superset of `eabi`, so any binary that targets EABI (with soft-float) will work on a hard-float host. But the performance will be terrible 🙂 

> Why don't we do this when we handle the `Err` variant from the detection instead of here?

I think we could, but it might also be a layering violation. Right now libc detection is shared across all three pathways (uv upgrade / `uv format` / PBS), and I _think_ we want the PBS pathway to be able to make different decisions (since as you note there _is_ a soft-float build available). 

Another option there would be to turn FP detection errors into hard errors, rather than leaving it to each downstream layer to try and suss out an appropriate decision. I think that would be fine to do, although it'd be a blind change in terms of how many users are currently getting the right binary despite FP detection failure because we currently fall-through to hard-float on ARMv7.

Comment (zanieb) [reply crates/uv-platform/src/lib.rs]: Ah I see we're just doing this in `as_cargo_dist_triple`.

I think my original request to update the comment is all I need then.

**Review by zanieb — APPROVED** [review]

File: crates/uv-platform/src/lib.rs (hunk 1 above)
Comment (zanieb) [reply crates/uv-platform/src/lib.rs]: I don't think we should fail if we can't read the procfs file to detect fp features. It seems unfixable for users.

Comment (woodruffw) [reply crates/uv-platform/src/lib.rs]: Yeah, makes sense. I suspect users will hit that semi-frequently in container environments (or in environments that do weird IDS things like blocking procfs reads).

Comment (jjhelmus) [reply crates/uv-platform/src/lib.rs]: > Can a hard-float host run a soft-float binary?

No, at least in the general case. Hard float (armhf) and soft float (armel) use different dynamic loaders (/lib/ld-linux.so.3 vs /lib/ld-linux-armhf.so.3) so a hard float distribution will not have the necessary loader (or dynamic libraries) to run a soft float binary. 

Some/many distribution support multi-arch, so a soft-float (armel) loader and libraries can be installed allowing soft-float binaries to be run on a hard-float system but this is the exception and should not be expected.
