### PR TITLE
Respect comma-separated extras in `--with`

### LINKED ISSUE #8918: fail to run  `uvx --with="psycopg[binary,pool]" pgcli --help` after upgrade to 0.5.0
```
❯ uvx --with="psycopg[binary,pool]" pgcli --help
error: Failed to parse: `psycopg[binary`
  Caused by: Missing closing bracket (expected ']', found end of dependency specification)
psycopg[binary
❯ uv --version 
uv 0.5.0 (Homebrew 2024-11-07)
```

it works at 0.4.x

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

We need to treat `flask,anyio` as two requirements, but `psycopg[binary,pool]` as a single requirement.

Closes #8918.

### CODE REVIEW

**Review by zanieb — APPROVED** [review]

File: crates/uv-cli/src/comma.rs [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+                ',' if depth == 0 => {
+                    let requirement = input[start..i].trim().to_string();
+                    if !requirement.is_empty() {
+                        requirements.push(requirement);
+                    }
+                    start = i + 1;
+                }
+                _ => {}
+            }
+        }
```
Comment (zanieb) [inline crates/uv-cli/src/comma.rs:38]: You always write these so nice
