### PR TITLE
Use symlinks instead of junctions on Wine

### LINKED ISSUE #19187: can't install python in wine
### Summary

when I tried to install python with uv in wine, it says:
```
error: Failed to create Python minor version link directory
  Caused by: 请求不被支持。 (os error 50)
```

### Platform

wine-10.0 (Debian 10.0~repack-6) / Linux 6.12.74+deb13+1-amd64 x86_64 GNU/Linux

### Version

0.11.8 (0e961dd9a 2026-04-27 x86_64-pc-windows-msvc)

### Python version

_No response_

### PR DESCRIPTION
**Pull request by zanieb**
Integration test coverage added in https://github.com/astral-sh/uv/pull/19214
Closes https://github.com/astral-sh/uv/issues/19187

On Wine, we're compiled for Windows but junctions are not available. Here, we switch to symlinks when we can detect Wine.

### CODE REVIEW

File: crates/uv-fs/src/lib.rs [hunk 1]
```diff
@@ -111,11 +127,43 @@ pub fn replace_symlink(src: impl AsRef<Path>, dst: impl AsRef<Path>) -> std::io:
...
+}
+
+/// Read the target of a Windows directory link created by [`create_symlink`] or
+/// [`replace_symlink`].
+///
+/// On Windows, uv normally creates junctions for directory links, but creates
+/// directory symbolic links under Wine. This function reads the appropriate link
+/// type for the current environment.
+#[cfg(windows)]
+pub fn read_junction(path: impl AsRef<Path>) -> std::io::Result<PathBuf> {
```
Comment (zanieb) [inline crates/uv-fs/src/lib.rs]: Should this just be `read_link` instead?

File: crates/uv-windows/src/wine.rs [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+}
+
+/// Detect Wine by probing `ntdll.dll` for the `wine_get_version` export, which
+/// is present in Wine's `ntdll` but not in the genuine Windows DLL.
+#[allow(unsafe_code)]
+fn detect_wine() -> bool {
+    // SAFETY: `GetModuleHandleA` is safe to call with a static, NUL-terminated
+    // ASCII module name. It returns an error if the module isn't loaded; we
+    // treat that as "not Wine" and bail out.
+    let Ok(ntdll) = (unsafe { GetModuleHandleA(s!("ntdll.dll")) }) else {
```
Comment (woodruffw) [inline crates/uv-windows/src/wine.rs]: Nit: pretty minor, but it might be slightly safer (in a multithreaded context) to use `GetModuleHandleExA` with `GET_MODULE_HANDLE_EX_FLAG_PIN` to ensure that the DLL never gets unloaded. 

(In practice I suspect that *can't* happen since this is `ntdll.dll`.)

**Review by woodruffw — APPROVED** [review]

**Comment by Winand** [comment]
Thanks! Interestingly, junctions used to work with 6.6.87.2-microsoft-standard-WSL2 kernel but on CentOS 7 I had to create a symlink in ~/.wine/drive_c/users/wine/AppData/Roaming/uv/python
