### PR TITLE
Fix double self-dependency

### LINKED ISSUE #13344: Resolver panics when adding qlmaas as dependency
### Summary

To reproduce execute `uv init test_env`, `cd test_env`, `uv add qlmaas`.

On windows:

```powershell
PS > uv --version
uv 0.7.3 (3c413f74b 2025-05-07)
```

```powershell
PS > uv add myqlm
Using CPython 3.12.9 interpreter at: C:\Users\%USER%\AppData\Local\Programs\Python\Python312\python.exe
Creating virtual environment at: .venv
⠼ qlmaas==1.11.2
thread 'uv-resolver' panicked at C:\Users\runneradmin\.cargo\git\checkouts\pubgrub-e6d66ebc0e28e95d\a3b4db3\src\term.rs:89:18:
Positive term cannot unwrap negative set
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: The channel closed unexpectedly
```

And on debian:

```bash
$ uv --version
uv 0.7.3
```

```bash
$ uv add qlmaas
Using CPython 3.11.12
Creating virtual environment at: .venv
⠙ qlmaas==1.11.2
thread 'uv-resolver' panicked at /root/.cargo/git/checkouts/pubgrub-e6d66ebc0e28e95d/a3b4db3/src/term.rs:89:18:
Positive term cannot unwrap negative set
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: The channel closed unexpectedly
```

### Platform

Linux 6.12.21-amd64 x86_64 GNU/Linux

### Version

uv 0.7.3

### Python version

3.11 and 3.12

### PR DESCRIPTION
**Pull request by konstin**
The fix itself and its documentation live in pubgrub: https://github.com/astral-sh/pubgrub/pull/44

Fixes #13344

### CODE REVIEW

**Review by charliermarsh — APPROVED** [review]

File: crates/uv/tests/it/pip_compile.rs [hunk 1]
```diff
@@ -17403,3 +17403,45 @@ fn compile_broken_active_venv() -> Result<()> {
...
+    context
+        .temp_dir
+        .child("pyproject.toml")
+        .write_str(indoc! {r#"
+        [project]
+        name = "foo"
+        version = "0.1.0"
+        dependencies = [
+            "foo",
+            "foo",
```
Comment (cthoyt) [inline crates/uv/tests/it/pip_compile.rs:17420]: just for completeness sake, can you imagine a scenario where you have `foo` and a double self dependency `foo[extra-bar]` that also has an extra with it?
