### PR TITLE
Make an empty string behave like the default

### LINKED ISSUE #2129: Support setting empty UV_INDEX_URL
Currently, if I set `UV_INDEX_URL` to the empty string with `UV_INDEX_URL=`, `uv` complains with:

```
error: invalid value '' for '--index-url <INDEX_URL>': relative URL without a base
```

To reproduce:

```bash
mkdir repro
cd repro
uv venv --seed
. .venv/bin/activate
UV_INDEX_URL= uv pip install griffe
```

pip supports it:

```
PIP_INDEX_URL= pip install griffe
```

As I understand it, setting the index URL to an empty string through the environment variable means "no index URL specified".

My use-case: I'm using a local index to serve private (insiders) versions of packages. Sometimes, I don't want to use these private versions, but the ones from PyPI.org. So to make this flexible, my shell by default `export UV_INDEX_URL="http://localhost:31411/simple/"`, and when I want to directly use PyPI.org, I do `UV_INDEX_URL= uv pip install ...`. Better yet, I declare a `no-insiders` alias (or similar name) as `alias no-insiders='env PDM_PYPI_URL= PIP_INDEX_URL= UV_INDEX_URL='`, since uv is not the only tool I'm using, and then use it with `no-insiders uv pip install ...`, or `no-insiders any-other-command-installing-packages-with-pip-pdm-uv`.

### PR DESCRIPTION
**Pull request by yasufumy**
## Summary

Resolve  #2129

I changed the behavior to parse an empty string for `--index-url` to be the same as the default.

### CODE REVIEW

File: crates/uv/src/main.rs [hunk 1]
```diff
@@ -201,6 +201,17 @@ fn date_or_datetime(input: &str) -> Result<DateTime<Utc>, String> {
...
+/// Clap parser for the index url
+fn parse_index_url(mut arg: &str) -> Result<IndexUrl, String> {
+    if arg.is_empty() {
+        arg = "https://pypi.org/simple";
+    }
+    match IndexUrl::from_str(arg) {
+        Ok(url) => Ok(url),
+        Err(err) => Err(err.to_string()),
+    }
+}
```
Comment (charliermarsh) [inline crates/uv/src/main.rs:213]: I think empty should probably map to `None` rather than PyPI. The difference is subtle but if a user has an `--index-url` in a `requirements.txt`, and they specify `UV_INDEX_URL=`, we should probably respect the index URL in the `requirements.txt` rather than overriding to PyPI (which will be accomplished by mapping this to `None`).

Comment (charliermarsh) [reply crates/uv/src/main.rs:213]: Playing around with this myself and Clap doesn't make it easy.
