### PR TITLE
Better missing self update feature

### LINKED ISSUE #8318: Let User Know Self Update is Disabled
I had installed `uv` from `brew` and was trying to run `uv self update`. However, that won't work (and it shouldn't, so kudos)!
The only thing was that the error message could be improved a bit.

```
mahyar@lioness vivaldi % uv self update
error: unrecognized subcommand 'self'

Usage: uv [OPTIONS] <COMMAND>

For more information, try '--help'.
mahyar@lioness vivaldi % uv --version
uv 0.4.18 (Homebrew 2024-10-01)
```

I would like to see something along the lines of "Hey, it looks like you're trying to self-update. However, `uv` was installed from <source> and cannot be updated in this way. Please use your package manager to update." or something along those lines.

Thanks for a great and fast tool.

### PR DESCRIPTION
**Pull request by konstin**
Show the user a proper error message when built without self-update instead of pretending the feature doesn't exist.

```
error: uv was installed through an external package manager, and self-update is not available. Please use your package manager to update uv.
```

Fixes #8318

### CODE REVIEW

**Review by zanieb — APPROVED** [review]

File: crates/uv-cli/src/lib.rs [hunk 1]
```diff
@@ -449,21 +448,18 @@ pub struct HelpArgs {
...
 
 #[derive(Subcommand)]
-#[cfg(feature = "self-update")]
 pub enum SelfCommand {
     /// Update uv.
     Update(SelfUpdateArgs),
 }
 
 #[derive(Args, Debug)]
-#[cfg(feature = "self-update")]
```
Comment (SteveLauC) [inline crates/uv-cli/src/lib.rs:466]: Hi there, may I ask why these `#[cfg(feature = "self-update")]` changes were reverted?

Comment (konstin) [reply crates/uv-cli/src/lib.rs:466]: With those guards and `--no-default-features`, uv pretends the subcommands doesn't exist; with this change, it shows an error message hinting the user to upgrade using their package manager.
