### PR TITLE
Avoid `uv cache clean` errors due to Win32 path normalization

### LINKED ISSUE #16586: `uv cache clean` fails on Windows when sdist contains special filenames
### Summary

Moved from https://github.com/astral-sh/uv/issues/15569#issuecomment-3477947525

## Description

On Windows, when running `uv add uwsgi`, the build process fails (which is expected as uwsgi cannot compile on Windows). However, when subsequently running uv cache clean, the command fails because the cached sdist contains a file with a Windows-incompatible name (ending with a period).

## Steps to Reproduce

On Windows, create a new project and add `uwsgi`.

```shell
uv init
uv add uwsgi
```

The build fails as expected since `uwsgi` is not supported on Windows.

Then run:

```shell
uv cache clean
```

## Expected Behavior

`uv cache clean` should remove cached source distributions (sdists).

## Actual Behavior

```text
Clearing cache at: AppData\Local\uv\cache
error: Failed to clear cache at: AppData\Local\uv\cache
  Caused by: failed to remove file `C:\Users\root\AppData\Local\uv\cache\sdists-v9\index\3ba65c4f41aac3a1\uwsgi\2.0.31\l1w3t3Nrz8OnzxF6ri3eg\src\core\logging.`: The system cannot find the file specified. (os error 2)
```

## Suggested Fix

Use logic similar to Python’s [isreserved](https://github.com/python/cpython/blob/947bb4642c612b66de7cae815aaf9c570a93882a/Lib/ntpath.py#L311-L316) to detect and handle reserved or invalid Windows filenames before deletion.

When removing such files, use the extended `\\?\` path prefix to bypass Win32 path normalization, which allows operations on paths exceeding `MAX_PATH` or containing characters normally restricted by the Win32 API (such as trailing dots or spaces).

### Platform

Windows 11 24H2

### Version

uv 0.9.7 (0adb44480 2025-10-30)

### Python version

Python 3.13.5

### PR DESCRIPTION
**Pull request by samypr100**
## Summary

Closes #16586

Adds a public function to `uv-fs` crate called `verbatim_path` which is now leveraged by `rm_rf` in `uv-cache` crate for cleaning paths that require verbatim composition to avoid failures seen in #16586.

## Test Plan

Tested locally on Windows 10 and 11 by setting `UV_CACHE_DIR` to a local directory and then running `uv init`, `uv add uwsgi`, and `uv cache clean` to ensure there is no failures.

Additionally unit and integration tests were added to avoid future regressions.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Awesome. Maybe @konstin or @EliteTK can review the verbatim path code?

File: crates/uv-fs/src/path.rs [hunk 1]
```diff
@@ -332,6 +333,99 @@ pub fn try_relative_to_if(
...
+///   * <https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats>
+pub fn verbatim_path(path: &Path) -> Cow<'_, Path> {
+    if !cfg!(windows) {
+        return Cow::Borrowed(path);
+    }
+
+    // Attempt to resolve a fully qualified path just like Win32 path normalization would.
+    // std::path::absolute calls GetFullPathNameW which defeats the purpose of this function
+    // as it results in Win32 default path normalization.
+    let resolved_path = if path.is_relative() {
```
Comment (konstin) [inline crates/uv-fs/src/path.rs:389]: Would it make sense to instead require the caller to pass an absolute path, given that there are no relative verbatim paths? We can `debug_assert!` that the given path is absolute?

File: crates/uv-fs/src/path.rs [hunk 2]
```diff
@@ -332,6 +333,99 @@ pub fn try_relative_to_if(
...
+/// function will attempt to perform path normalization similar to Win32 default normalization
+/// without triggering the existing Win32 limitations.
+///
+/// Only [`Prefix::UNC`] and [`Prefix::Disk`] conversion compatible components are supported.
+///   * [`Prefix::UNC`] `\\server\share` becomes `\\?\UNC\server\share`
+///   * [`Prefix::Disk`] `DriveLetter:` becomes `\\?\DriveLetter:`
+///
+/// Other representations do not yield a `verbatim` path. The following cases are returned as-is:
+///   * Non-Windows systems.
+///   * Device paths such as those starting with `\\.\`.
```
Comment (konstin) [inline crates/uv-fs/src/path.rs:367]: This took me some confusion to realize that `\\.\` is a prefix for virtual paths, not the UNC-version of `.`

File: crates/uv-fs/src/path.rs [hunk 3]
```diff
@@ -332,6 +333,99 @@ pub fn try_relative_to_if(
...
+            Prefix::DeviceNS(_)
+            // return as-is as its already verbatim
+            | Prefix::Verbatim(_)
+            | Prefix::VerbatimDisk(_)
+            | Prefix::VerbatimUNC(..) => return Cow::Borrowed(path)
+        }
+    }
+
+    // Resolve relative directory components while avoiding default Win32 path normalization
+    let normalized_path = normalized(&resolved_path);
```
Comment (konstin) [inline crates/uv-fs/src/path.rs:409]: TIL that UNC allow `.` and `..`, they just don't resolve them, nor does it handle forward slashes.

File: crates/uv-fs/src/path.rs [hunk 4]
```diff
@@ -332,6 +333,99 @@ pub fn try_relative_to_if(
...
+        // `\\server\share` -> `\\?\UNC\server\share`
+        Prefix::UNC(server, share) => {
+            let mut result = OsString::from(r"\\?\UNC\");
+            result.push(server);
+            result.push(r"\");
+            result.push(share);
+            for component in components {
+                match component {
+                    Component::RootDir => {} // being cautious
+                    Component::Prefix(_) => unreachable!("prefix already consumed"),
```
Comment (konstin) [inline crates/uv-fs/src/path.rs]: You can put `debug_assert!`s into those branches, they make those cases show up while developing, while not panicking in production (which for those cases is worse than continuing)

File: crates/uv-fs/src/path.rs [hunk 5]
```diff
@@ -332,6 +333,99 @@ pub fn try_relative_to_if(
...
+                    Component::Normal(_) | Component::CurDir | Component::ParentDir => {
```
Comment (konstin) [inline crates/uv-fs/src/path.rs]: current and parent dir also shouldn't be reachable anymore after normalization.

File: crates/uv-fs/src/path.rs [hunk 6]
```diff
@@ -564,4 +658,59 @@ mod tests {
...
+            ),
+            // Verbatim Disk
+            (r"\\?\C:\path\to\logging.", r"\\?\C:\path\to\logging."),
+            // Verbatim UNC
+            (
+                r"\\?\UNC\127.0.0.1\c$\path\to\logging.",
+                r"\\?\UNC\127.0.0.1\c$\path\to\logging.",
+            ),
+            // Device Namespace
+            (r"\\.\PhysicalDrive0", r"\\.\PhysicalDrive0"),
```
Comment (konstin) [inline crates/uv-fs/src/path.rs:763]: Can you add a test for my favourite file, `NUL`?

File: crates/uv-fs/src/path.rs (hunk 1 above)
Comment (samypr100) [reply crates/uv-fs/src/path.rs:389]: It's a breaking devex trade-off and one that I considered heavily before settling on this approach.

I think "requiring an absolute path" can be easily misconstrued by a future developer to pass it through `std::path::absolute` or equivalent before calling this function. In my mind, that can be a landmine easy to trip on as you effectively are subject to Windows normalization rules at that stage, making a "verbatim" representation worthless and prone to the same errors as reported in the original issue.

My goal for the current behavior of this function was that you didn't have to think if it was absolute or not. My only warning was that you shouldn't use this to "create" files with.

I based some of these tradeoffs similar to how Node does it in [path.toNamespacedPath](https://nodejs.org/docs/latest-v24.x/api/path.html#pathtonamespacedpathpath) in their [source](https://github.com/nodejs/node/blob/7cf913fadd599405e160f1cedd6733094b376a61/src/path.cc#L282-L327).

For example say I have a `PathBuf::from("C:\\foo\\bar\\logging.")` which I then call `std::path::absolute` with would yield `C:\\foo\\bar\\logging`
If I later call `verbatim_path`  it would yield `\\?\C:\\foo\\bar\\logging` rather than `\\?\C:\\foo\\bar\\logging.`

File: crates/uv-fs/src/path.rs (hunk 4 above)
Comment (samypr100) [reply crates/uv-fs/src/path.rs]: Makes sense, done in 0b31b5388624b3b2aee61733926375c84ab6721f / a64644c

File: crates/uv-fs/src/path.rs (hunk 5 above)
Comment (samypr100) [reply crates/uv-fs/src/path.rs]: I hade a previous impl in which I normalized "after" the iteration hence why I left this here, removed in 0b31b5388624b3b2aee61733926375c84ab6721f / a64644c

File: crates/uv-fs/src/path.rs (hunk 6 above)
Comment (samypr100) [reply crates/uv-fs/src/path.rs:763]: lol, done in 0b31b5388624b3b2aee61733926375c84ab6721f / a64644c

File: crates/uv-fs/src/path.rs (hunk 1 above)
Comment (konstin) [reply crates/uv-fs/src/path.rs:389]: > For example say I have a `PathBuf::from("C:\\foo\\bar\\logging.")` which I then call `std::path::absolute` with would yield `C:\\foo\\bar\\logging` If I later call `verbatim_path` it would yield `\\?\C:\\foo\\bar\\logging` rather than `\\?\C:\\foo\\bar\\logging.`

Oh no, I didn't realize that, it makes much more sense this way!
