### PR TITLE
Fix handling of `--allow-existing` with minor version links on Windows

### LINKED ISSUE #17963: `uv venv --allow-existing` regression in `0.10.2`
### Summary

Looks to be a regression of #14249; opening as a new issue as I do not have permission to reopen the existing one.
```cmd
>uv venv -v
DEBUG uv 0.10.2 (a788db7e5 2026-02-10)
DEBUG Acquired shared lock for `C:\Users\user\AppData\Local\uv\cache`
DEBUG No Python version file found in ancestors of working directory: C:\My Files\Workspaces\Personal\Projects\test
DEBUG Using request connect timeout of 10s and read timeout of 30s
DEBUG Searching for default Python interpreter in managed installations, search path, or registry
DEBUG Searching for managed installations at `C:\Users\user\AppData\Roaming\uv\python`
DEBUG Found managed installation `cpython-3.14.3-windows-x86_64-none`
DEBUG Found `cpython-3.14.3-windows-x86_64-none` at `C:\Users\user\AppData\Roaming\uv\python\cpython-3.14-windows-x86_64-none\python.exe` (managed installations)
Using CPython 3.14.3
Creating virtual environment at: .venv
DEBUG Using base executable for virtual environment: C:\Users\user\AppData\Roaming\uv\python\cpython-3.14-windows-x86_64-none\python.exe
DEBUG Using junction C:\Users\user\AppData\Roaming\uv\python\cpython-3.14-windows-x86_64-none instead of base Python path: C:\Users\user\AppData\Roaming\uv\python\cpython-3.14-windows-x86_64-none\python.exe
Activate with: .venv\Scripts\activate
DEBUG Released lock at `C:\Users\user\AppData\Local\uv\cache\.lock`

>uv venv --allow-existing -v
DEBUG uv 0.10.2 (a788db7e5 2026-02-10)
DEBUG Acquired shared lock for `C:\Users\user\AppData\Local\uv\cache`
DEBUG No Python version file found in ancestors of working directory: C:\My Files\Workspaces\Personal\Projects\test
DEBUG Using request connect timeout of 10s and read timeout of 30s
DEBUG Searching for default Python interpreter in managed installations, search path, or registry
DEBUG Searching for managed installations at `C:\Users\user\AppData\Roaming\uv\python`
DEBUG Found managed installation `cpython-3.14.3-windows-x86_64-none`
DEBUG Found `cpython-3.14.3-windows-x86_64-none` at `C:\Users\user\AppData\Roaming\uv\python\cpython-3.14-windows-x86_64-none\python.exe` (managed installations)
Using CPython 3.14.3
Creating virtual environment at: .venv
DEBUG Using base executable for virtual environment: C:\Users\user\AppData\Roaming\uv\python\cpython-3.14-windows-x86_64-none\python.exe
DEBUG Allowing existing virtual environment due to `--allow-existing`
DEBUG Using junction C:\Users\user\AppData\Roaming\uv\python\cpython-3.14-windows-x86_64-none instead of base Python path: C:\Users\user\AppData\Roaming\uv\python\cpython-3.14-windows-x86_64-none\python.exe
DEBUG Released lock at `C:\Users\user\AppData\Local\uv\cache\.lock`
error: Failed to create virtual environment
  Caused by: Failed to create Python executable link at .venv\Scripts\python.exe from C:\Users\user\AppData\Roaming\uv\python\cpython-3.14-windows-x86_64-none\python.exe
  Caused by: The file exists. (os error 80)
```

### Platform

Windows 11 x86_64

### Version

uv 0.10.2

### Python version

Python 3.14.3

### PR DESCRIPTION
**Pull request by zanieb**
Closes #17963

### CODE REVIEW

File: crates/uv-python/src/managed.rs [hunk 1]
```diff
@@ -1002,6 +1002,44 @@ pub fn create_link_to_executable(link: &Path, executable: &Path) -> Result<(), E
...
+/// If a file already exists at the link path, it will be atomically replaced.
+pub fn replace_link_to_executable(link: &Path, executable: &Path) -> Result<(), Error> {
+    let link_parent = link.parent().ok_or(Error::NoExecutableDirectory)?;
+    fs_err::create_dir_all(link_parent).map_err(|err| Error::ExecutableDirectory {
+        to: link_parent.to_path_buf(),
+        err,
+    })?;
+
+    if cfg!(unix) {
+        // Use `replace_symlink` which atomically replaces via a temporary symlink and rename.
```
Comment (zanieb) [inline crates/uv-python/src/managed.rs]: I don't think we need to explain what `replace_symlink` does

File: crates/uv-python/src/managed.rs [hunk 2]
```diff
@@ -1002,6 +1002,44 @@ pub fn create_link_to_executable(link: &Path, executable: &Path) -> Result<(), E
...
+        // Note: on Unix, the venv code path uses `replace_symlink` directly, so this branch
+        // exists primarily for compilation purposes.
```
Comment (zanieb) [inline crates/uv-python/src/managed.rs]: Why aren't we using this same code path on Unix too instead?

File: crates/uv-python/src/managed.rs [hunk 3]
```diff
@@ -1002,6 +1002,44 @@ pub fn create_link_to_executable(link: &Path, executable: &Path) -> Result<(), E
...
+        })
+    } else if cfg!(windows) {
+        use uv_trampoline_builder::windows_python_launcher;
+
+        let launcher = windows_python_launcher(executable, false)?;
+
+        // Write to a temporary file then atomically replace the target via
+        // `persist` (which uses `MoveFileEx` with `MOVEFILE_REPLACE_EXISTING`).
+        // This avoids "file exists" errors when recreating venvs with
+        // `--allow-existing` and ensures the link is never partially written.
```
Comment (zanieb) [inline crates/uv-python/src/managed.rs]: I don't think we need to explain atomic writes when the function is clearly for atomic writes

File: crates/uv-python/src/managed.rs [hunk 4]
```diff
@@ -1002,6 +1002,44 @@ pub fn create_link_to_executable(link: &Path, executable: &Path) -> Result<(), E
     }
 }
 
+/// Create or replace a link to a managed Python executable.
+///
+/// If a file already exists at the link path, it will be atomically replaced.
```
Comment (zanieb) [inline crates/uv-python/src/managed.rs:1007]: Should we have a `[...]` ref to `create_link_to_executable`? Are there cases where we wouldn't use `replace_..`?

File: crates/uv-python/src/managed.rs [hunk 5]
```diff
@@ -1002,6 +1002,39 @@ pub fn create_link_to_executable(link: &Path, executable: &Path) -> Result<(), E
...
+///
+/// See [`create_link_to_executable`] for a variant that errors if the link already exists.
+pub fn replace_link_to_executable(link: &Path, executable: &Path) -> Result<(), Error> {
+    let link_parent = link.parent().ok_or(Error::NoExecutableDirectory)?;
+    fs_err::create_dir_all(link_parent).map_err(|err| Error::ExecutableDirectory {
+        to: link_parent.to_path_buf(),
```
Comment (konstin) [inline crates/uv-python/src/managed.rs:1013]: The fs_err error should already include the path, we don't need to repeat it.

Comment (zanieb) [reply crates/uv-python/src/managed.rs:1013]: This seems like a critique of an existing code pattern — I'm happy to fix it separately, but I didn't introduce that error variant here.

Comment (konstin) [reply crates/uv-python/src/managed.rs:1013]: Makes sense, I didn't realize this was pre-existing.

**Review by konstin — APPROVED** [review]
