### PR TITLE
fix(tests): Refactor uv format tests

### LINKED ISSUE #15458: Move `uv format` unformatted test file into const
> There are a lot of duplicated code among these tests (mainly, the same `pyproject.toml`, and the formatted/unformatted code snippets). I preferred to maintain the previous style and copypaste the mock data. I'm not sure what approach do you usually follow here (to extract into constants/fixtures vs always copypaste)

_Originally posted by @jorgehermo9 in https://github.com/astral-sh/uv/pull/15438#discussion_r2292327872_

### PR DESCRIPTION
**Pull request by pposca**
Closes #15458

## Summary

Refactor uv format tests to reduce noise.

### CODE REVIEW

File: crates/uv/tests/it/format.rs [hunk 1]
```diff
@@ -55,34 +50,27 @@ fn format_project() -> Result<()> {
...
-    let context = TestContext::new_with_versions(&[]);
+fn assert_file_not_formatted<P: AsRef<Path>>(path: P) -> Result<()> {
+    let formatted_content = fs_err::read_to_string(path)?;
+    assert_snapshot!(formatted_content, @r#"
+    import sys
+    def   hello():
+        print(  "Hello, World!"  )
+    if __name__=="__main__":
+        hello(   )
+    "#);
```
Comment (zanieb) [inline crates/uv/tests/it/format.rs]: Should this be `assert_snapshot`? Shouldn't we just be asserting the string matches this exact content?

Comment (zanieb) [reply crates/uv/tests/it/format.rs]: If we're moving these out into utilities that make assertions about it being formatted or not, it seems weird to use snapshots.

**Comment by zanieb** [comment]
I'm a little worried that this diverges from the rest of the test suite, in which a `pyproject.toml` is always explicitly constructed and snapshots are generally used rather than assertions. I'm not sure if that's a big deal or not though.

I'd probably chase making the Python file much simpler first, e.g., `x     = 1`, so there's less noise.

File: crates/uv/tests/it/format.rs (hunk 1 above)
Comment (pposca) [reply crates/uv/tests/it/format.rs]: My first idea was to use assert_eq, which would allow to use const &str instead of @"string literal" and the function, but I've never used test snapshots and I didn't know if I would break anything.

What is the role of the snapshots here? As far as I've understood, the common use requires running the test more than one to compare snapshots; but what it seems like is that they are being used like assert_eq in these tests.

Comment (zanieb) [reply crates/uv/tests/it/format.rs]: Snapshots work like string matching assertions that we can automatically update instead of failing when there's a mismatch. I don't even know what will happen if you share it across multiple tests like this, probably bad things in the long-term.

**Review by zanieb — APPROVED** [review]

**Comment by zanieb** [comment]
Thank you!
