### PR TITLE
fix: Add a hint on `uv pip install` failure if the `--system` flag is used to select an externally managed interpreter

### LINKED ISSUE #15639: On externally managed errors, hint why a system interpreter was selected
e.g., in https://github.com/astral-sh/uv/issues/15635 we could hint that the system interpreter was selected because of the `--system` flag.

### PR DESCRIPTION
**Pull request by cmnemoi**
Hello,

# Summary
This PR makes the error message clearer when you try to install packages into an externally managed Python environment with the `--system` flag. 
Now, instead of just failing, the error explains that you're hitting this because you explicitly used `--system`.

This closes #15639.

# Test plan

- I added a new integration test (`install_with_system_interpreter` in `pip_install.rs`) that checks the error message includes the hint.
- I tried to run `uv pip install --system -r requirements.txt` to see the actual error message in action, but had permission issues.

### CODE REVIEW

File: crates/uv/tests/it/pip_install.rs [hunk 1]
```diff
@@ -12990,3 +12990,43 @@ fn pip_install_no_sources_editable_to_registry_switch() -> Result<()> {
...
+
+    // Add a custom filter to replace the system Python path (works on Unix-like systems, Windows and for CPython, PyPy and GraalPy implementations)
+    let filters: Vec<_> = context
+        .filters()
+        .into_iter()
+        .chain(std::iter::once((
+            r"([\\/]).+([\\/])python([\\/])(?:cpython|pypy|graalpy)-\d+\.\d+\.\[X\][^\s]+",
+            "[PYTHON-PATH]",
+        )))
+        .collect();
```
Comment (cmnemoi) [inline crates/uv/tests/it/pip_install.rs]: I am not sure if this is the best way to do this, or if this should be added to  `context.filters` directly.

File: crates/uv/src/commands/pip/install.rs [hunk 2]
```diff
@@ -236,18 +236,23 @@ pub(crate) async fn pip_install(
...
-                Err(anyhow::anyhow!(
+                    if system {
+                        "\nhint: This happens because you used the `--system` flag, which selects the system Python interpreter."
+                    } else {
+                        ""
+                    }
+                ),
+                None => anyhow::anyhow!(
                     "The interpreter at {} is externally managed. Instead, create a virtual environment with `uv venv`.",
                     environment.root().user_display().cyan()
```
Comment (konstin) [inline crates/uv/src/commands/pip/install.rs:247]: We should show the hint in both branches

File: crates/uv/src/commands/pip/install.rs [hunk 3]
```diff
@@ -236,18 +236,23 @@ pub(crate) async fn pip_install(
...
+            let error = match externally_managed.into_error() {
+                Some(error) => anyhow::anyhow!(
+                    "The interpreter at {} is externally managed, and indicates the following:\n\n{}\n\nConsider creating a virtual environment with `uv venv`.{}",
                     environment.root().user_display().cyan(),
                     textwrap::indent(&error, "  ").green(),
-                ))
-            } else {
-                Err(anyhow::anyhow!(
+                    if system {
+                        "\nhint: This happens because you used the `--system` flag, which selects the system Python interpreter."
```
Comment (konstin) [inline crates/uv/src/commands/pip/install.rs]: What about the following hint:

> The `--system` flag was used

We usually use indirect language instead of "you used"

Comment (konstin) [inline crates/uv/src/commands/pip/install.rs]: We style the hint with:

```
"hint".bold().cyan(),
":".bold(),
```
