### PR TITLE
Track retry counts originating from early middleware errors

### LINKED ISSUE #17266: 0.9.20: DNS failures take ~4x longer due to nested retries
## Summary

DNS failures that took ~4 seconds in 0.9.18 now take ~17-19 seconds in 0.9.20. Looking at debug logs, it appears the retry logic is running at two layers now (middleware + cached client), causing way more retries than expected I think?

This was caught from our CI specs because we have a 10 second timeout waiting for a Python harness to start when dealing malformed PyPi clients or similar. 

## Minimal reproduction

```bash
# Setup
mkdir -p /tmp/uv-test && cd /tmp/uv-test
mkdir -p packages
pip download six==1.17.0 --dest packages -q

cat > uv.toml << 'EOF'
[pip]
find-links = ["./packages"]
index-url = "http://invalid-hostname-xyz123"
EOF

echo "six==1.17.0" > requirements.txt
uv venv .venv -q

# Time it
time UV_CONFIG_FILE=./uv.toml uv pip install -r requirements.txt --python .venv/bin/python
```

**0.9.18:** ~4 seconds
**0.9.20:** ~17-19 seconds

## What I'm seeing

With `RUST_LOG=debug`, 0.9.18 shows the expected pattern - middleware retries 3 times, then fails:

```
WARN Retry attempt #0. Sleeping 494ms before the next attempt
WARN Retry attempt #1. Sleeping 1.27s before the next attempt
WARN Retry attempt #2. Sleeping 1.57s before the next attempt
error: Request failed after 3 retries
```

But 0.9.20 shows the middleware retrying, then the cached client layer triggers _another_ round:

```
WARN Retry attempt #0. Sleeping 897ms before the next attempt
WARN Retry attempt #1. Sleeping 1.18s before the next attempt
WARN Retry attempt #2. Sleeping 1.41s before the next attempt
DEBUG Transient failure while handling response...; retrying after 0.1s...   <-- starts over
WARN Retry attempt #0. Sleeping 981ms before the next attempt
...
DEBUG Transient failure while handling response...; retrying after 0.1s...   <-- and again
WARN Retry attempt #0. Sleeping 815ms before the next attempt
...
DEBUG Transient failure while handling response...; retrying after 2.6s...   <-- and again
...
error: Request failed after 3 retries
```

Ends up doing 16+ attempts instead of 4.

## Platform

macOS 14.3.0 arm64

## Version

Tested on:

- uv 0.9.18 (0cee76417 2025-12-16) - works as expected
- uv 0.9.20 (765a96723 2025-12-29) - regression?
## Version

Tested on:

- uv 0.9.18 (0cee76417 2025-12-16) - works as expected
- uv 0.9.20 (765a96723 2025-12-29) - regression

## Likely cause

The timing lines up with #17104 and #17105 which unified retry handling. It looks like both the middleware (`RetryTransientMiddleware`) and the cached client (`RetryState::should_retry`) now independently retry transient errors, creating nested retry loops.

## Potential fix

I've tested locally that having `RetryState::should_retry` return `None` for transient errors (since middleware already handles those) fixes the issue while keeping all existing tests passing. Happy to submit a PR if helpful.

### Platform

macOS 14.3.0 arm64, Ubuntu/Debian

### Version

uv 0.9.20

### Python version

Python 3.14.0

### PR DESCRIPTION
**Pull request by EliteTK**
## Summary

Fixes #17266.

The retry count was getting dropped by `ErrorKind::from_retry_middleware` and `<Error as From<ErrorKind>>::from` so we were doing more retries than we should have.

## Test Plan

Added a testcase for the specific error path in the issue. Added an expect to the other retry test too.

### CODE REVIEW

**Comment by EliteTK** [comment]
@zanieb do you think its worth waiting on @konstin?

File: crates/uv/tests/it/network.rs [hunk 1]
```diff
@@ -455,6 +456,40 @@ async fn install_http_retries() {
...
 
+#[tokio::test]
+async fn install_http_retry_low_level() {
+    let context = TestContext::new("3.12");
+
+    let server = MockServer::start().await;
+
+    // Create a server that fails with a more fundamental error so we trigger
+    // earlier error paths
+    Mock::given(method("GET"))
```
Comment (konstin) [inline crates/uv/tests/it/network.rs:467]: Can you move this to a helper too, with a doc comment about which error path this checks?
