### PR TITLE
Recreate project environment if `--python` or `requires-python` doesn't match

### LINKED ISSUE #3895: Project's virtualenv initialization needs to respect `Requires-Python`
See: `project::init_environment`.

### LINKED ISSUE #4131: `uv lock` fails if the default python version doesn't match project python version
I have an environment where `python` is 3.12 and a project with `requires-python = "==3.11.*"`. This makes `uv lock` fail:

```console
$ cargo run -q -- lock --preview
  × No solution found when resolving dependencies:
  ╰─▶ Because the current Python version (3.12.3) does not satisfy Python>=3.11.dev0,<3.12.dev0 and warehouse==1.0.0 depends on
      Python>=3.11.dev0,<3.12.dev0, we can conclude that warehouse==1.0.0 cannot be used.
      And because only warehouse==1.0.0 is available and warehouse depends on warehouse, we can conclude that the requirements are
      unsatisfiable.
```

The better behavior would be `uv lock` finding the python 3.11 that i have in path.

### PR DESCRIPTION
**Pull request by konstin**
Fixes #4131
Fixes #3895

### CODE REVIEW

**Comment by konstin** [comment]
I have to check windows is-satisfied detection but otherwise this is ready for review

File: crates/uv-toolchain/src/discovery.rs [hunk 1]
```diff
@@ -934,6 +935,72 @@ impl ToolchainRequest {
...
+            ToolchainRequest::Version(version_request) => {
+                version_request.matches_interpreter(interpreter)
+            }
+            ToolchainRequest::Directory(directory) => {
+                // `sys.prefix` points to the venv root.
+                is_same_file(directory, interpreter.sys_prefix()).unwrap_or(false)
+            }
+            ToolchainRequest::File(file) => {
+                // The interpreter satisfies the request both if it is the venv ...
+                if is_same_file(interpreter.sys_executable(), file).unwrap_or(false) {
```
Comment (charliermarsh) [inline crates/uv-toolchain/src/discovery.rs:952]: Nit: can we reverse the order of these arguments to match the `ToolchainRequest::Directory` case?

File: crates/uv/src/commands/project/mod.rs [hunk 2]
```diff
@@ -81,42 +82,94 @@ pub(crate) fn find_environment(
...
+    )?
+    .into_interpreter();
+
+    if let Some(requires_python) = requires_python {
+        if !requires_python.contains(interpreter.python_version()) {
+            warn_user!(
+                "The Python {} you requested with {} is incompatible with the requirement of the \
+                project of {}",
+                interpreter.python_version(),
+                python.unwrap_or("(default)"),
```
Comment (charliermarsh) [inline crates/uv/src/commands/project/mod.rs:146]: Can we `if`-`else` this warning? `you requested with (default) is incompatible...` is confusing and it's trivial for us to use a better message here.

File: crates/uv/src/commands/project/mod.rs [hunk 3]
```diff
@@ -81,42 +82,94 @@ pub(crate) fn find_environment(
...
+        preview,
+        cache,
+    )?
+    .into_interpreter();
+
+    if let Some(requires_python) = requires_python {
+        if !requires_python.contains(interpreter.python_version()) {
+            warn_user!(
+                "The Python {} you requested with {} is incompatible with the requirement of the \
+                project of {}",
```
Comment (charliermarsh) [inline crates/uv/src/commands/project/mod.rs:144]: Nit: `: {}` instead of `of {}`.

File: crates/uv-toolchain/src/discovery.rs [hunk 4]
```diff
@@ -19,6 +19,7 @@ use crate::virtualenv::{
 use crate::{Interpreter, PythonVersion};
 use std::borrow::Cow;
 
+use same_file::is_same_file;
```
Comment (charliermarsh) [inline crates/uv-toolchain/src/discovery.rs:22]: Import sections here are all over the place lol.

**Review by charliermarsh — APPROVED** [review]

File: crates/uv-toolchain/src/discovery.rs (hunk 4 above)
Comment (zanieb) [reply crates/uv-toolchain/src/discovery.rs:22]: Sorry that's probably my fault I use the editors "add import" feature a lot and things can get out of hand.

File: crates/uv/src/commands/project/lock.rs [hunk 5]
```diff
@@ -41,9 +42,23 @@ pub(crate) async fn lock(
...
     let interpreter = match project::find_environment(&workspace, cache) {
-        Ok(environment) => environment.into_interpreter(),
+        Ok(environment) => {
+            let interpreter = environment.into_interpreter();
+            if let Some(python) = python.as_deref() {
+                let request = ToolchainRequest::parse(python);
+                if request.satisfied(&interpreter) {
+                    interpreter
+                } else {
+                    Toolchain::find_requested(python, SystemPython::Allowed, preview, cache)?
```
Comment (zanieb) [inline crates/uv/src/commands/project/lock.rs:52]: I guess I should update this API to take the `ToolchainRequest` instead of a string.

File: crates/uv/tests/run.rs [hunk 6]
```diff
@@ -0,0 +1,121 @@
...
+use indoc::indoc;
+
+use crate::common::get_toolchain;
+use common::{uv_snapshot, TestContext};
+
+mod common;
+
+/// Run with different python versions, which also depend on different dependency versions.
+#[test]
+fn run_with_python_version() -> Result<()> {
```
Comment (zanieb) [inline crates/uv/tests/run.rs:14]: Thanks for writing a test!

**Review by zanieb — APPROVED** [review]

**Comment by charliermarsh** [comment]
I am debugging the Windows failure, since I want to merge this for today's release.

**Comment by charliermarsh** [comment]
Hopefully fixed? Fixed it locally, at least.
