### PR TITLE
Don't preserve timestamp in streaming unzip

### LINKED ISSUE #1748: Source installs fail due to timestamps/zip for `flit`-based sdists
(Some?) sdists created with `flit` (e.g. `cloudpathlib`, `tomli`, `typer`) include a `PKG-INFO` file with a timestamp of Jan 1 1970, which raises an error when building from source. `pip` installs without errors.

Command, using `uv` 0.1.5:

```shell
uv pip install cloudpathlib==0.17.0 --no-binary cloudpathlib --no-cache --reinstall
```

Output:

```none
Resolved 2 packages in 392ms
error: Failed to download distributions
  Caused by: Failed to fetch wheel: cloudpathlib==0.17.0
  Caused by: Failed to build: cloudpathlib==0.17.0
  Caused by: Build backend failed to build wheel through `build_wheel()`:
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "/tmp/.tmplPwcVh/.tmp6SwAEy/.venv/lib/python3.8/site-packages/flit_core/buildapi.py", line 72, in build_wheel
    info = make_wheel_in(pyproj_toml, Path(wheel_directory))
  File "/tmp/.tmplPwcVh/.tmp6SwAEy/.venv/lib/python3.8/site-packages/flit_core/wheel.py", line 224, in make_wheel_in
    wb.build(editable)
  File "/tmp/.tmplPwcVh/.tmp6SwAEy/.venv/lib/python3.8/site-packages/flit_core/wheel.py", line 210, in build
    self.copy_module()
  File "/tmp/.tmplPwcVh/.tmp6SwAEy/.venv/lib/python3.8/site-packages/flit_core/wheel.py", line 164, in copy_module
    self._add_file(full_path, rel_path)
  File "/tmp/.tmplPwcVh/.tmp6SwAEy/.venv/lib/python3.8/site-packages/flit_core/wheel.py", line 111, in _add_file
    zinfo = zipfile.ZipInfo.from_file(full_path, rel_path)
  File "/usr/lib/python3.8/zipfile.py", line 539, in from_file
    zinfo = cls(arcname, date_time)
  File "/usr/lib/python3.8/zipfile.py", line 362, in __init__
    raise ValueError('ZIP does not support timestamps before 1980')
ValueError: ZIP does not support timestamps before 1980
```

This looks like the same issue as #579, but it doesn't appear to be fixed by #634?

### PR DESCRIPTION
**Pull request by konstin**
## Summary

Don't preserve mtime to work around alexcrichton/tar-rs#349. Same as #634 except for the streaming unzip.

Fixes #1748.

## Test Plan

Added the tomli source dist as test case.

### CODE REVIEW

File: crates/uv-extract/src/stream.rs [hunk 1]
```diff
@@ -93,6 +93,7 @@ pub async fn untar<R: tokio::io::AsyncBufRead + Unpin>(
     let decompressed_bytes = async_compression::tokio::bufread::GzipDecoder::new(reader);
     let mut archive = tokio_tar::ArchiveBuilder::new(decompressed_bytes)
         .set_preserve_permissions(false)
```
Comment (konstin) [inline crates/uv-extract/src/stream.rs:95]: @charliermarsh Do you remember why we have that her but not in the sync impl? Docs say "This flag is disabled by default" in both impls.

Comment (charliermarsh) [reply crates/uv-extract/src/stream.rs:95]: I think this is a mistake / typo. I probably meant for this to be mtime.

Comment (charliermarsh) [reply crates/uv-extract/src/stream.rs:95]: We probably should be preserving permissions, right?

**Review by charliermarsh — APPROVED** [review]

File: crates/uv-extract/src/stream.rs (hunk 1 above)
Comment (konstin) [reply crates/uv-extract/src/stream.rs]: After https://github.com/astral-sh/uv/pull/1743, i think we should preserve the execute permission, but everything else (read, write and owner, as far as i can tell) should always be set to os defaults. We can adapt the same logic as for wheel for tars (#1743).

Comment (charliermarsh) [reply crates/uv-extract/src/stream.rs]: Yeah I was wondering if we were missing that for tars.
