### PR TITLE
Running `uv lock --check` with outdated lockfile will print that `--check` was passed, instead of `--locked` 

### LINKED ISSUE #14105: confusing error message for `uv lock --check`
### Summary

When running `uv lock --check` the error message for an out of date lock file is a bit confusing:
```python
➜ uv lock --check
Resolved 288 packages in 1.77s
error: The lockfile at `uv.lock` needs to be updated, but `--locked` was provided. To update the lockfile, run `uv lock`.
```
It says `--locked` was provided but it obviously wasn't.. `--check` was!

Given the docs [here](https://docs.astral.sh/uv/concepts/projects/sync/#checking-if-the-lockfile-is-up-to-date) the message is somewhat understandable I guess?
  > You can check if the lockfile is up-to-date by passing the --check flag to uv lock:
  > `uv lock --check`
  > This is equivalent to the --locked flag for other commands.

Even though the error message makes some sense given the context of the docs I feel like a better error message should be provided.

### Platform

Linux 5.15.0-141-generic x86_64 GNU/Linux

### Version

uv 0.7.3

### Python version

Python 3.12.9

### PR DESCRIPTION
**Pull request by cmnemoi**
Hello,

# Summary

This PR fixes the confusing error message when running `uv lock --check` with an outdated lockfile.

Previously, the error message incorrectly stated that `--locked` was provided, even when the user used `--check`.

Now, the error message correctly indicates which flag was used: either `--check` or `--locked`.

This closes #14105.

# Test plan

- I updated the existing integration test (`check_outdated_lock` in `lock.rs`) to verify the new error message includes the correct flag.
- I ran existing tests to ensure I have no introduced regressions for other commands.

### CODE REVIEW

**Comment by zanieb** [comment]
I was imaging instead setting up a type like `Mode::Lock | Mode::Check(CheckSource::Check | CheckSource::Locked)` instead  of a `bool` so we can report this value appropriately?

sort of like https://github.com/astral-sh/uv/blob/b4168e665e585dff4e21cef352aa2c8a438c4f29/crates/uv/src/commands/tool/run.rs#L65-L72 or https://github.com/astral-sh/uv/blob/13a976a89763442c5fb13e1db3804c9e9920968c/crates/uv/src/commands/python/install.rs#L153-L176

**Comment by cmnemoi** [comment]
@zanieb Thanks for the review, I applied necessary changes.

File: crates/uv-cli/src/lib.rs [hunk 1]
```diff
@@ -3719,20 +3719,34 @@ pub struct LockArgs {
...
+    #[arg(long, env = EnvVars::UV_LOCKED, value_parser = clap::builder::BoolishValueParser::new(), conflicts_with_all = ["check_exists", "upgrade", "locked"])]
     pub check: bool,
 
+    /// Check if the lockfile is up-to-date.
+    ///
+    /// Asserts that the `uv.lock` would remain unchanged after a resolution. If the lockfile is
+    /// missing or needs to be updated, uv will exit with an error.
+    ///
+    /// Equivalent to `--check`.
+    #[arg(long, env = EnvVars::UV_LOCKED, value_parser = clap::builder::BoolishValueParser::new(), conflicts_with_all = ["check_exists", "upgrade", "check"])]
```
Comment (zanieb) [inline crates/uv-cli/src/lib.rs]: We should hide this one, I think.

File: crates/uv/src/commands/project/add.rs [hunk 2]
```diff
@@ -177,7 +177,7 @@ pub(crate) async fn add(
                 "`--package` is a no-op for Python scripts with inline metadata, which always run in isolation"
             );
         }
-        if locked {
+        if matches!(lock_check, LockCheck::Enabled(_)) {
             warn_user_once!(
                 "`--locked` is a no-op for Python scripts with inline metadata, which always run in isolation"
             );
```
Comment (zanieb) [inline crates/uv/src/commands/project/add.rs]: Shouldn't we use the source in this warning message?

File: crates/uv/src/commands/project/add.rs [hunk 3]
```diff
@@ -977,8 +977,8 @@ async fn lock_and_sync(
     preview: Preview,
 ) -> Result<(), ProjectError> {
     let mut lock = project::lock::LockOperation::new(
-        if locked {
-            LockMode::Locked(target.interpreter())
+        if matches!(lock_check, LockCheck::Enabled(_)) {
+            LockMode::Locked(target.interpreter(), lock_check.source().unwrap())
```
Comment (zanieb) [inline crates/uv/src/commands/project/add.rs]: We should use `if let LockCheck::Enabled(source) = lock_check {` so you can avoid the `unwrap`

Comment (zanieb) [reply crates/uv/src/commands/project/add.rs]: (there are some more instances of this following)

File: crates/uv/src/commands/project/add.rs (hunk 2 above)
Comment (zanieb) [reply crates/uv/src/commands/project/add.rs]: (there are some more instances of this following)

File: crates/uv/tests/it/lock.rs [hunk 4]
```diff
@@ -13140,51 +13140,32 @@ fn check_no_lock() -> Result<()> {
 /// Checks the output of `uv lock --check` when the lock is outdated
 #[test]
 fn check_outdated_lock() -> Result<()> {
+    // Given a test context with a pyproject.toml
     let context = TestContext::new("3.12");
```
Comment (zanieb) [inline crates/uv/tests/it/lock.rs:13143]: I'm a bit confused that the setup for this test case changed. Why did it?

**Comment by zanieb** [comment]
Nice! That's what I had in mind :)

File: crates/uv/tests/it/lock.rs (hunk 4 above)
Comment (cmnemoi) [reply crates/uv/tests/it/lock.rs:13143]: This is from my old implementation. 

I badly reverted the test case I added for that, I will fix that.

**Comment by cmnemoi** [comment]
@zanieb Thanks for the insightful review again, I applied needed changes :+1:

**Review by zanieb — APPROVED** [review]
