### PR TITLE
Expand Windows shim detection to include `python3.12.exe`

### LINKED ISSUE #2208: Ignore Windows shims for (e.g.) `python3.12.exe`
```
AppData\Local\Temp
❯ uv --version
uv 0.1.14 (c525fdf2b 2024-03-04)

AppData\Local\Temp
❯ uv venv -p 3.12 vvv
  × failed to canonicalize path `C:\Users\...\AppData\Local\Microsoft\WindowsApps\python3.12.exe`
  ╰─▶ The file cannot be accessed by the system. (os error 1920)
```

_Originally posted by @madig in https://github.com/astral-sh/uv/issues/2105#issuecomment-1978399748_

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Our Windows shim detection wasn't catching shims like `python3.12.exe`.

Closes #2208.

## Test Plan

Installed Python 3.12 via the Windows Store; verified that `cargo run venv --python 3.12` failed before but passes after this change.

### CODE REVIEW

File: crates/uv-interpreter/src/python_query.rs [hunk 1]
```diff
@@ -412,17 +412,58 @@ mod windows {
     /// does not want us to do this as the format is unstable.  So this is a best effort way.
     /// we just hope that the reparse point has the python redirector in it, when it's not
     /// pointing to a valid Python.
-    pub(super) fn is_windows_store_shim(path: &std::path::Path) -> bool {
+    ///
+    /// Matches against paths like:
+    ///     `C:\Users\crmar\AppData\Local\Microsoft\WindowsApps\python.exe`
+    pub(super) fn is_windows_store_shim(path: &Path) -> bool {
```
Comment (charliermarsh) [inline crates/uv-interpreter/src/python_query.rs:418]: I structured this to look similar to `is_windows_store_python`.
