### PR TITLE
`uvx` warn when executable is not part of `--from PKG`

### LINKED ISSUE #5017: `uvx` should warn or error when an executable outside of `--from` is used
As mentioned at https://github.com/astral-sh/uv/pull/4997#discussion_r1675091857

e.g. in this invocation:

```
uvx --from fastapi fastapi
```

`fastapi` is actually provided by a `fastapi` dependency `fastapi-cli`. If a user later runs `uv tool install fastapi` it will fail saying no executables are available. We should try to have a smooth transition from `uv tool run` to `uv tool install`. If the invoked executable does not belong to the `--from` package, I think we should _at least_ warn and maybe hard-error unless some opt-in is given e.g. `--include-from fastapi-cli`.

See https://github.com/astral-sh/uv/issues/4994 for more discussion on the opt-in flags.

### PR DESCRIPTION
**Pull request by blueraft**
## Summary

Resolves #5017.

Note: This re-uses the same function defined in #5019 to find matching packages.

## Test Plan

`cargo test`

```console
❯ ./target/debug/uvx --from fastapi fastapi
warning: `uvx` is experimental and may change without warning.
Resolved 33 packages in 427ms
warning: The fastapi executable is not part of the fastapi package. It is provided by the fastapi-cli package. Use `uvx --from fastapi-cli fastapi` instead.
Usage: fastapi [OPTIONS] COMMAND [ARGS]...
Try 'fastapi --help' for help.
```

### CODE REVIEW

File: crates/uv/src/commands/tool/run.rs [hunk 1]
```diff
@@ -139,6 +139,50 @@ pub(crate) async fn run(
         command.to_string_lossy(),
         args.iter().map(|arg| arg.to_string_lossy()).join(" ")
     );
+    if has_from {
```
Comment (charliermarsh) [inline crates/uv/src/commands/tool/run.rs:142]: I think this should probably run regardless of whether the user explicitly passed `--from`. E.g., `uv tool run fastapi` should also show this warning, right?

**Comment by zanieb** [comment]
Some small changes in https://github.com/astral-sh/uv/pull/5071/commits/a169aae0dd710263a23cb699f2325be8511bb342 — as before lmk if you have questions.
