### PR TITLE
Skip over broken tool Python on Windows too

### LINKED ISSUE #16252: If I remove the base Python interpreter, `uv tool list` doesn't work
### Summary

I uninstalled Python 3.13 from my system, and reinstalled it using the new Python Manager. As a result, the old `python.exe` no longer exists. Now, when I run `uv tool list` I get:

```
warning: Querying Python at `C:\Users\Gustav\AppData\Roaming\uv\tools\nox\Scripts\python.exe` failed with exit status exit code: 103

[stderr]
did not find executable at 'C:\Users\Gustav\AppData\Local\Programs\Python\Python313\python.exe': The system cannot find the path specified.
 (run `uv tool install nox --reinstall` to reinstall)
```

This is reasonable (although it would be nice if the error was handled better, maybe by listing `nox` but with a note that the Python executable wasn't found, rather than a raw error). But what *isn't* OK is that the recommended action, `uv tool install nox --reinstall`, fails with the same error. Reinstalling a broken tool should work, not fail with the same error that is the reason you're trying to reinstall!

Uninstalling nox (and then installing it from scratch) did work, although I'd prefer it if reeinstalling could be made to work, rather than changing the recommendation to uninstall and then reinstall.

As a side note, if I had been able to reinstall nox, it's not obvious to me whether I'd expect it to be updated to use Python 3.14, or to still try to use Python 3.13 (and fail because I don't have Python 3.13 installed) - although I'm fine if it worked like uninstall/reinstall and used the default system Python (3.14). I definitely *wouldn't* want it to install a uv-managed copy of Python, though - I'm careful to manage my persistent Python installations via the standard Python installer, not via uv, and I wouldn't want that to change.

### Platform

Windows 11 x86_64

### Version

uv 0.9.2 (141369ce7 2025-10-10)

### Python version

Python 3.14.0 (although nox was installed using Python 3.13)

### PR DESCRIPTION
**Pull request by konstin**
Fixes #16252

### CODE REVIEW

**Comment by zanieb** [comment]
I wonder if we should just accept the possibility of TOCTOU in this edge case and on Windows

1. Check if the canonicalized path exists
2. If it's a trampoline, check if the pointer path exists
3. Invoke the interpreter
4. On exit code 103, if (1) or (2) was false, return the proper error variant

We could also change the order to check (1) and (2) after (4)

**Comment by konstin** [comment]
~~Parsing the trampoline is just what I've been looking for!~~

I'm not worried about TOCTOU bugs, if you're (un)installing Python interpreters in parallel to (un)install a tool using that very Python version, you're already on an error path. Our behavior does not escape, you can't into a half state that otherwise couldn't exist, you always end up with a regularly working tool or with a tool with a regularly broken Python interpreter (with the variant that you could fail mid-installation with a build that needs to call Python if the underlying Python disappeared). Overall, the behavior doesn't get worse if you get into one of you observe a TOCTOU race.

File: crates/uv-python/src/interpreter.rs [hunk 1]
```diff
@@ -15,6 +15,13 @@ use serde::{Deserialize, Serialize};
 use thiserror::Error;
 use tracing::{debug, trace, warn};
 
+use crate::implementation::LenientImplementationName;
+use crate::managed::ManagedPythonInstallations;
+use crate::pointer_size::PointerSize;
+use crate::{
+    Prefix, PyVenvConfiguration, PythonInstallationKey, PythonVariant, PythonVersion, Target,
+    VersionRequest, VirtualEnvironment,
+};
```
Comment (charliermarsh) [inline crates/uv-python/src/interpreter.rs]: I think this should maybe not move?
