### PR TITLE
Elevate configuration errors to `required-version` mismatches

### LINKED ISSUE #17609: tool.uv.required-version should be handled before parsing rest of pyproject.toml file
### Summary

`tool.uv.required-version` (#8605) allows specifying uv version constraints in the `pyproject.toml` file. uv commands should fail if the user's uv version does not match the constraint.

But parsing the `pyproject.toml` file can fail if it uses settings that are not yet present in the user's version of uv. In this case uv will only show a warning instead and ignore the version mismatch:

 ```bash
warning: Failed to parse `pyproject.toml` during settings discovery:
```

## Example

`pyproject.toml` file with a setting introduced in `0.9.25`:

```toml
[tool.uv]
required-version = ">=0.9.26"

[tool.uv.exclude-newer-package]
numpy = false
````

Running then e.g. `uv pip install numpy` with uv version `0.9.24` will show this warning but still continue:

```bash
warning: Failed to parse `pyproject.toml` during settings discovery:
TOML parse error at line 5, column 9
|
5 | numpy = false
|         ^^^^^
data did not match any variant of untagged enum Helper

Using Python 3.11.9 environment at: /home/fellhorn/somewhere/somewhere
Audited 1 package in 5ms
```

But running it with uv `0.9.25` will throw an error and exit:

```bash
error: Required uv version `>=0.9.26` does not match the running version `0.9.25`. Update `uv` by running `uv self update`.
```

### Platform

Linux 6.8.0-90-generic x86_64 GNU/Linux

### Version

uv 0.9.24

### Python version

_No response_

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

If we fail to parse a `pyproject.toml` or `uv.toml` due to unsupported settings, we now do a post-validation check to see if we're _not_ running a required version, so that the error message reflects that mismatch.

Closes https://github.com/astral-sh/uv/issues/17609.

### CODE REVIEW

File: crates/uv-settings/src/settings.rs [hunk 1]
```diff
@@ -40,6 +40,41 @@ pub(crate) struct Tools {
...
+}
+
+/// A `uv.toml` containing only the fields required for `required-version` discovery.
+#[derive(Debug, Clone, Default, Deserialize)]
+#[serde(rename_all = "kebab-case")]
+pub(crate) struct UvRequiredVersionToml {
+    pub(crate) required_version: Option<RequiredVersion>,
+    #[expect(
+        dead_code,
+        reason = "Captures and ignores all other top-level `uv.toml` keys"
```
Comment (konstin) [inline crates/uv-settings/src/settings.rs]: Why do we need to capture those keys?

**Review by konstin — APPROVED** [review]
