### PR TITLE
Use suffix on uvx binary when searching for uv binary

### LINKED ISSUE #11637: uvx does not work when installed with `pipx install --suffix=... uv`
### Summary

When you install uv using `pipx install --suffix=... uv`, trying to run `uvx` results in the following:

```
❯ pipx install --suffix=@0.6.2 uv==0.6.2
  installed package uv 0.6.2 (uv@0.6.2), installed using Python 3.13.2
  These apps are now globally available
    - uv@0.6.2
    - uvx@0.6.2
done! ✨ 🌟 ✨
❯ uv@0.6.2
An extremely fast Python package manager.

Usage: uv@0.6.2 [OPTIONS] <COMMAND>
...
❯ uvx@0.6.2
error: Could not find the `uv` binary at: /Users/me/.local/bin/uv
```

We want to utilize the `--suffix=...` option with pipx to enable side-by-side installation of uv for multiple projects that have been tested against different versions of uv without constantly warring over what global version of uv is installed.

### Platform

MacOS 15.3.1

### Version

uv 0.6.2 (6d3614eec 2025-02-19), pipx 1.7.1

### Python version

Python 3.8.20

### PR DESCRIPTION
**Pull request by Gankra**
This is a rebased and updated version of #11925 based on my review (I didn't have permission to push to their branch).

For posterity I've preserved their commits but my final commit essentially rewrites the whole thing anyway.

Fixes #11637

### CODE REVIEW

File: crates/uv/src/bin/uvx.rs [hunk 1]
```diff
@@ -22,6 +23,56 @@ fn exec_spawn(cmd: &mut Command) -> std::io::Result<Infallible> {
...
+            Err(err) => {
+                // We don't know if `uv@1.2.3` exists, something errored when checking.
+                // We *could* blindly use `uv@1.2.3` in this case, as the code below does, however
+                // in this extremely narrow corner case it's *probably* better to default to `uv`,
+                // since we don't want to mess up existing users who weren't using suffixes?
+                eprintln!(
+                    "warning: failed to determine if `{}` exists, trying `uv` instead: {err}",
+                    uv_with_suffix.display()
+                );
+            }
```
Comment (Gankra) [inline crates/uv/src/bin/uvx.rs:52]: I'm not 100% certain on this decision!

Comment (zanieb) [reply crates/uv/src/bin/uvx.rs:52]: Seems reasonable to me

Comment (cliebBS) [reply crates/uv/src/bin/uvx.rs:53]: I updated my branch to emit warnings, if you want to take a look.
