### PR TITLE
Linker copies files as a fallback when ref-linking fails

### LINKED ISSUE #1444: Add copy fallback for reflink-based linker
See: https://twitter.com/mpr0010/status/1758299951254388875.

### PR DESCRIPTION
**Pull request by snowsignal**
## Summary

Fixes #1444.

In situations where the installer fails to perform a reflink, a regular file copy is also attempted, as a fallback. This circumvents issues with linking files across filesystems or volumes.

## Test Plan
N/A

### CODE REVIEW

**Review by konstin — APPROVED** [review]

**Comment by charliermarsh** [comment]
Oh nice, I didn't know this existed.

File: crates/install-wheel-rs/src/linker.rs [hunk 1]
```diff
@@ -302,7 +302,7 @@ fn clone_recursive(site_packages: &Path, wheel: &Path, entry: &DirEntry) -> Resu
     debug!("Cloning {} to {}", from.display(), to.display());
 
     // Attempt to copy the file or directory
-    let reflink = reflink_copy::reflink(&from, &to);
+    let reflink = reflink_copy::reflink_or_copy(&from, &to);
```
Comment (charliermarsh) [inline crates/install-wheel-rs/src/linker.rs:305]: I think we need our own version of this that behaves differently when the error is `std::io::ErrorKind::AlreadyExists`.

Comment (charliermarsh) [reply crates/install-wheel-rs/src/linker.rs:305]: In that case, copying isn't the right fallback, I think?

Comment (charliermarsh) [reply crates/install-wheel-rs/src/linker.rs:305]: Hence the test failure. Notice that we have a branch for `AlreadyExists` below, where we recurse.

Comment (charliermarsh) [reply crates/install-wheel-rs/src/linker.rs:305]: Oh, it looks like `reflink_or_copy` also doesn't fallback properly when the target is a directory.

Comment (konstin) [reply crates/install-wheel-rs/src/linker.rs:305]: We need a `reflink_or_copy_all`, but if we need to handle `AlreadyExists` with a no-fallback path we probably can't do it upstream in the `reflink_copy` crate.

Comment (charliermarsh) [reply crates/install-wheel-rs/src/linker.rs:305]: Yeah, we should just write our own here.

Comment (snowsignal) [reply crates/install-wheel-rs/src/linker.rs:305]: I could contribute an upstream PR to add a `reflink_or_copy_all` function.

File: crates/install-wheel-rs/src/linker.rs [hunk 2]
```diff
@@ -302,22 +302,37 @@ fn clone_recursive(site_packages: &Path, wheel: &Path, entry: &DirEntry) -> Resu
     debug!("Cloning {} to {}", from.display(), to.display());
 
     // Attempt to copy the file or directory
-    let reflink = reflink_copy::reflink(&from, &to);
+    let mut reflink = reflink_copy::reflink_or_copy(&from, &to);
```
Comment (charliermarsh) [inline crates/install-wheel-rs/src/linker.rs:305]: Can we try this without using `reflink_or_copy`? The workaround here feels like it's not quite the right tradeoff. `reflink_or_copy` just calls reflink and then, if it fails, it calls copy. Can we just mimic that here? We should be able to tell from the error directly without having to do the additional `reflink` call.

The other problem with the current approach is that we're going to try and `reflink` for every file, even though we _know_ it won't work. (If the first reflink fails for any reason other than `AlreadyExists`, then all of the subsequent reflinks will fail too.) In `hardlink_wheel_files`, we avoid this by _just_ copying once we know we can't hardlink.

For example, can you try something like: still using `reflink_copy::reflink` here, then adding another branch below, where if the error is anything other than `AlreadyExists`, we fall back to recursively copying the directory.

Comment (snowsignal) [reply crates/install-wheel-rs/src/linker.rs:305]: You're right, this could probably be a lot simpler. Technically, `reflink_copy::reflink_or_copy` works a bit differently than separate `reflink_copy::reflink` + `std::fs::copy` calls, but it's not that important of a difference.

And yes, we should definitely try to avoid doing extra work here.

File: crates/install-wheel-rs/src/linker.rs [hunk 3]
```diff
@@ -280,53 +280,93 @@ fn clone_wheel_files(
...
+                        reflink_copy::reflink(from, &tempfile)?;
+                        fs::rename(&tempfile, to)?;
+                    }
+                } else {
+                    return Err(Error::Reflink { to, from, err });
+                }
+            }
+        }
+        CloneAttempt::UseCopyFallback => {
+            fs::copy(&from, &to)?;
```
Comment (charliermarsh) [inline crates/install-wheel-rs/src/linker.rs:368]: Does this need to recursively copy? Does it work if `from` is a directory? (I notice that in `copy_wheel_files`, we use `walkdir`.)

**Review by konstin — COMMENTED** [review]
I wonder what the right strategy to test this is, can we create a ram disk or a virtual filesystem as non-root?

**Comment by charliermarsh** [comment]
I would suggest just stubbing out `reflink` with a method that always errors.

**Comment by konstin** [comment]
How you implement this rust-wise, without `unittest.mock`?

**Comment by charliermarsh** [comment]
@konstin - Oh sorry, I meant for manual testing (while implementing).

File: crates/install-wheel-rs/src/linker.rs (hunk 3 above)
Comment (snowsignal) [reply crates/install-wheel-rs/src/linker.rs:368]: This does need to recursively copy, my mistake.

**Review by charliermarsh — APPROVED** [review]
Nice, thanks!

File: crates/install-wheel-rs/src/linker.rs [hunk 4]
```diff
@@ -280,55 +281,118 @@ fn clone_wheel_files(
...
-        reflink.map_err(|err| Error::Reflink {
-            from: from.clone(),
-            to: to.clone(),
-            err,
-        })?;
     }
 
+    if *attempt == Attempt::Initial {
+        *attempt = Attempt::Subsequent;
+    }
```
Comment (charliermarsh) [inline crates/install-wheel-rs/src/linker.rs:395]: Is this different than including it as an `else` in the `Attempt::Initial` arm?

E.g.:

```diff
diff --git a/crates/install-wheel-rs/src/linker.rs b/crates/install-wheel-rs/src/linker.rs
index 6275994f..69eff653 100644
--- a/crates/install-wheel-rs/src/linker.rs
+++ b/crates/install-wheel-rs/src/linker.rs
@@ -356,6 +356,9 @@ fn clone_recursive(
                     *attempt = Attempt::UseCopyFallback;
                     clone_recursive(site_packages, wheel, entry, attempt)?;
                 }
+            } else {
+                // If the first reflink succeeded, we'll use reflink for the rest of the install.
+                *attempt = Attempt::Subsequent;
             }
         }
         Attempt::Subsequent => {
@@ -390,9 +393,6 @@ fn clone_recursive(
         }
     }

-    if *attempt == Attempt::Initial {
-        *attempt = Attempt::Subsequent;
-    }
     Ok(())
 }
```

Comment (snowsignal) [reply crates/install-wheel-rs/src/linker.rs:395]: It would be, because we also want to update the attempt value in the case of an `AlreadyExists` error that we handle. For example, if we have to overwrite a file, but don't need to fall-back to copying, this `else` branch would not be hit.
