### PR TITLE
Don't enforce that requirements files are "files"

### LINKED ISSUE #3944: `uv pip compile <(echo foobar)` reports "file not found", but it should work
Example:

```
$ uv-0.1.24 pip compile <(echo example)
Resolved 2 packages in 527ms
# This file was autogenerated by uv via the following command:
#    uv pip compile /proc/self/fd/11
example==0.1.0
six==1.16.0
    # via example
$ uv pip compile <(echo example)
error: File not found: `/proc/self/fd/11
```

`git bisect` suggests this was introduced in https://github.com/astral-sh/uv/commit/081f20c53ef6849c816cbe12e5dcf4bb7de575e1.

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This was just an opportunistic guard but it broke some use-cases.

Closes #3944.

### CODE REVIEW

File: crates/uv-requirements/src/specification.rs [hunk 1]
```diff
@@ -109,14 +109,6 @@ impl RequirementsSpecification {
                 }
             }
             RequirementsSource::RequirementsTxt(path) => {
-                if !(path == Path::new("-")
-                    || path.starts_with("http://")
-                    || path.starts_with("https://")
-                    || path.is_file())
-                {
-                    return Err(anyhow::anyhow!("File not found: `{}`", path.user_display()));
-                }
```
Comment (charliermarsh) [inline crates/uv-requirements/src/specification.rs:118]: @BurntSushi - The test we want here is: can we `fs::read` this? But it's fine, we just error later (see changed fixture).

**Review by BurntSushi — COMMENTED** [review]
Makes sense to me.
