### PR TITLE
Encode mutually-incompatible pairs of markers

### LINKED ISSUE #7760: Incorporate knowledge of disjoint markers into simplification
There are some markers that we "know" cannot be true at the same time, despite the fact that it's not encoded in the grammar or schema at all.

For example, this is never true: `platform_system == 'Linux' and sys_platform == 'darwin'`.

If we encode knowledge about the markers that we "know" are disjoint, we can omit more forks, wheels, etc.

### LINKED ISSUE #9275: Ignore irrelevant platform-specific packages during resolution
Hi,

I've noticed that `uv`  still tries to resolve packages that are supposed to be irrelevant for the configured environment. I'm working on a server with a private registry where we don't have Darwin packages. When I try to install `ipykernel`, however, I see it still tries to resolve a Darwin-specific package, which then fails as it isn't available in our registry. Specifically, it's about `appnope`, which is configured as `'appnope>=0.1.2;platform_system=="Darwin"'` in ipykernel' s pyproject.toml.(https://github.com/ipython/ipykernel/blob/8c4901d691b1f309da3b80eefad5af13d7418185/pyproject.toml#L32C6-L32C13)

I'm using `uv` 0.5.2 on RHEL.

```toml
[project]
name = "test-project"
version = "0.1.0"
description = "My test project"
readme = "README.md"

dependencies = [
    "ipykernel ; sys_platform == 'linux'"
]

[tool.uv]
environments = [
    "sys_platform == 'linux'"
]
```  

```
$ uv lock -v 2>&1 | grep Darwin
DEBUG Solving split (python_full_version == '3.10'and platform_system == 'Darwin' and sys_platform == 'linux') ...
DEBUG Adding transitive dependency for ipykernel==x.x.x: appnope{platform_system == 'Darwin'}*
DEBUG Adding transitive dependency for ipykernel==x.x.x: appnope{platform_system == 'Darwin'}*
```

I think it might be related to https://github.com/astral-sh/uv/issues/9051#issuecomment-2470334438

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This is an alternative to #9344. If accepted, I need to audit the codebase and call sites to apply it everywhere, but the basic idea is: rather than encoding mutually-incompatible pairs of markers in the representation itself, we have an additional method on `MarkerTree` that expands the false-y definition to take into account assumptions about which markers can be true alongside others. We then check if the the current marker implies that at least one of them is true.

So, for example, we know that `sys_platform == 'win32'` and `platform_system == 'Darwin'` are mutually exclusive. When given a marker expression like `python_version >= '3.7'`, we test if `python_version >= '3.7'` and `sys_platform != 'win32' or platform_system != 'Darwin'` are disjoint, i.e., if the following can't be satisfied:

```
python_version >= '3.7' and (sys_platform != 'win32' or platform_system != 'Darwin')
```

Since, if this can't be satisfied, it implies that the left-hand expression requires `sys_platform == 'win32'` and `platform_system == 'Darwin'` to be true at the same time.

I think the main downsides here are:

1. We can't _simplify_ markers based on these implications. So we'd still write markers like `sys_platform == 'win32' and platform_system != 'Darwin'`, even though we know the latter expression is redundant.
2. It might be expensive? I'm not sure. I don't think we test for falseness _that_ often though.

Closes #7760.
Closes #9275.

### CODE REVIEW

File: crates/uv-resolver/src/resolver/environment.rs [hunk 1]
```diff
@@ -494,7 +494,7 @@ impl<'d> Forker<'d> {
         let mut envs = vec![];
         {
             let not_marker = self.marker.negate();
-            if !env_marker.is_disjoint(&not_marker) {
+            if !env_marker.is_disjoint(&not_marker) && !env_marker.is_conflicting() {
```
[the remark this answers is not in the document]
Comment (charliermarsh) [reply crates/uv-resolver/src/resolver/environment.rs:497]: It might be a pain... Right now, `env_marker.is_disjoint(&not_marker)` returns `true` if either of the expressions are false, but that doesn't include the `is_conflicting` definition here -- it only looks at the `FALSE` node.

[the remark this answers is not in the document]
Comment (konstin) [reply crates/uv-resolver/src/resolver/environment.rs:497]: You could make `is_conflicting` into `simplify_conflicting(...) -> MarkerTree` that returns a FALSE node if it matched one of the impossible cases, that might simplify

[the remark this answers is not in the document]
Comment (charliermarsh) [reply crates/uv-resolver/src/resolver/environment.rs:497]: Do you think the approach makes sense though?

**Review by konstin — APPROVED** [review]

File: crates/uv-resolver/src/resolver/environment.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (konstin) [reply crates/uv-resolver/src/resolver/environment.rs:497]: we'd have to try it out, but it does sound more elegant in theory

**Review by BurntSushi — COMMENTED** [review]
I think the idea here is sound.

My main concern is probably what you might expect: that you have to remember to call this in a bunch of places around the code. I suppose the mitigation to that is that this isn't a correctness issue but a simplification issue.

Is there any way to do this simplification via `MarkerTree`'s smart constructors? Before @ibraheemdev's work, we had this problem of markers possibly being simplified or not, and we'd call the simplification routine in various spots. But now we have a nice guarantee that markers are always simplified, as guaranteed by the smart constructors. Maybe we can do that in our `MarkerTree::and` and `MarkerTree::or` methods?

**Comment by charliermarsh** [comment]
Yeah I like that idea.

File: crates/uv-resolver/src/resolver/environment.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (konstin) [reply crates/uv-resolver/src/resolver/environment.rs:497]: andrew's idea is even better than that

File: crates/uv-pep508/src/marker/tree.rs [hunk 2]
```diff
@@ -685,6 +687,186 @@ impl MarkerTree {
...
+                    MarkerExpression::String {
+                        key: MarkerValueString::PlatformSystem,
+                        operator: MarkerOperator::Equal,
+                        value: "Windows".to_string(),
+                    },
+                ),
+            ] {
+                let mut a = MarkerTree::expression(a);
+                let b = MarkerTree::expression(b);
+                a.and(b);
```
[the remark this answers is not in the document]
Comment (ibraheemdev) [reply crates/uv-pep508/src/marker/tree.rs:861]: This is in a `OnceCell` so it should be good.

File: crates/uv-pep508/src/marker/tree.rs [hunk 3]
```diff
@@ -695,12 +697,14 @@ impl MarkerTree {
     #[allow(clippy::needless_pass_by_value)]
     pub fn and(&mut self, tree: MarkerTree) {
         self.0 = INTERNER.lock().and(self.0, tree.0);
```
Comment (charliermarsh) [inline crates/uv-pep508/src/marker/tree.rs:699]: Is it better to hold the lock and re-use it in `simplify`, or re-`lock()` as I'm doing here?

Comment (ibraheemdev) [reply crates/uv-pep508/src/marker/tree.rs:699]: Probably re-use it, these are pretty much only used by a single thread.

**Comment by charliermarsh** [comment]
I think what I have here works, but I'm worried about the performance costs and complexity.

File: crates/uv-pep508/src/marker/tree.rs [hunk 4]
```diff
@@ -716,6 +720,23 @@ impl MarkerTree {
...
+    /// For example, while the marker specification and grammar do not _forbid_ it, we know that
+    /// both `sys_platform == 'win32'` and `platform_system == 'Darwin'` will never true at the
+    /// same time.
+    ///
+    /// This method thus encodes assumptions about the environment that are not guaranteed by the
+    /// PEP 508 specification alone.
+    fn simplify(&mut self) {
+        if !self.0.is_false() {
+            let mutex = &*MUTUAL_EXCLUSIONS;
+            if INTERNER.lock().is_disjoint(self.0, mutex.0) {
```
Comment (konstin) [inline crates/uv-pep508/src/marker/tree.rs:734]: Took me a while to understand that this is `is_disjoint` and not `!is_disjoint` because `MUTUAL_EXCLUSIONS` is the negated exclusions, so it's the valid space.

image

Plus when reading the code you need to consider we call this every time while building the marker, so when only B from `A or B` lies in the excluded area, we still get A because B was converted to FALSE upon construction.

Comment (charliermarsh) [reply crates/uv-pep508/src/marker/tree.rs:734]: Should I be changing something in response to this comment? :)

Comment (konstin) [reply crates/uv-pep508/src/marker/tree.rs:734]: Could you add an inline comment like:

> `MUTUAL_EXCLUSIONS` is the possible space, if the markers are `is_disjoint` with it, they are solely in the impossible space.

Comment (konstin) [reply crates/uv-pep508/src/marker/tree.rs:734]: (I'll leave the smart constructor review to andrew/ibraheem)

**Comment by charliermarsh** [comment]
Ok, I think _this_ version should have a minimal performance hit. I moved the logic into the algebra itself, and we now only perform this check when merging nodes that could yield a conflict (i.e., two marker trees that contain variables that could conflict). Per @ibraheemdev suggestion, I made those variables "highest-priority", so if they aren't present at the top of the marker tree, we know they aren't present anywhere beneath it.

File: crates/uv-pep508/src/marker/algebra.rs [hunk 5]
```diff
@@ -421,6 +489,245 @@ impl InternerGuard<'_> {
...
+                }
+            };
+
+            // Create the output node.
+            guard.create_node(func, children)
+        }
+
+        if let Some(exclusions) = self.state.exclusions {
+            return exclusions;
+        }
```
Comment (charliermarsh) [inline crates/uv-pep508/src/marker/algebra.rs:562]: I assume it's fine to just use an `Option` here rather than a `OnceCell`?

File: crates/uv-pep508/src/marker/algebra.rs [hunk 6]
```diff
@@ -328,6 +333,11 @@ impl InternerGuard<'_> {
 
         let (x, y) = (self.shared.node(xi), self.shared.node(yi));
 
+        // Determine whether the conjunction _could_ contain a conflict. As an optimization, we only
+        // have to perform this check at the top-level, since these variables are given higher
+        // priority in the tree. In other words, if they're present, they _must_ be at the top.
+        let conflicts = x.var.conflicts() && y.var.conflicts();
```
Comment (charliermarsh) [inline crates/uv-pep508/src/marker/algebra.rs:339]: The idea is to give the "possibly-conflicting" markers highest priority, so they're always at the top of the tree.

As such, when we AND two expressions, we only have to perform the "possibly-conflicting" check if they both have a conflicting variable at the very top.

**Comment by charliermarsh** [comment]
Ok, I added some sorting to the DNF to minimize the amount of churn in the expressions.

File: crates/uv-pep508/src/marker/tree.rs [hunk 7]
```diff
@@ -493,6 +494,19 @@ pub enum MarkerExpression {
     },
 }
 
+/// The kind of a [`MarkerExpression`].
+#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, PartialOrd, Ord)]
+pub(crate) enum MarkerExpressionKind {
```
Comment (BurntSushi) [inline crates/uv-pep508/src/marker/tree.rs:499]: Is this _only_ used for backcompat sorting? If so, it might be useful to add a comment indicating as such. And that the order here matters?

File: crates/uv-pep508/src/marker/algebra.rs [hunk 8]
```diff
@@ -380,17 +402,63 @@ impl InternerGuard<'_> {
...
+        // `X` and `X` are not disjoint.
+        if xi == yi {
+            return false;
+        }
+        // `X` and `not X` are disjoint by definition.
+        if xi.not() == yi {
+            return true;
+        }
+
+        let (x, y) = (self.shared.node(xi), self.shared.node(yi));
```
[the remark this answers is not in the document]
Comment (BurntSushi) [reply crates/uv-pep508/src/marker/algebra.rs:456]: Yeah I feel like a little copying here is probably the way to go. I don't see a simple way of unifying them without making it more obscure.

Might be worth moving this comment into the code, for future wranglers wondering about it.

File: crates/uv-pep508/src/marker/algebra.rs [hunk 9]
```diff
@@ -421,6 +489,245 @@ impl InternerGuard<'_> {
...
+                    let children = x
+                        .children
+                        .apply(xi, &y.children, yi, |x, y| conjunction(guard, x, y));
+                    (x.var.clone(), children)
+                }
+            };
+
+            // Create the output node.
+            guard.create_node(func, children)
+        }
```
[the remark this answers is not in the document]
Comment (BurntSushi) [reply crates/uv-pep508/src/marker/algebra.rs:566]: Makes sense.

File: crates/uv-pep508/src/marker/algebra.rs (hunk 5 above)
Comment (BurntSushi) [reply crates/uv-pep508/src/marker/algebra.rs:570]: Yeah. Rust wouldn't let you mess this up.

**Review by BurntSushi — APPROVED** [review]
I think this makes sense to me. And I like that this doesn't require any sort of knowledge on the callers part to explicitly simplify the markers. Nice work. :-)
