### PR TITLE
Fix Python variant tagging in the Windows registry

### LINKED ISSUE #18795: When install the same number of python versions, GIL and no-GIL, installation record  is missing.
### Question

step1, run commands `uv python install 3.14` and `uv python list`, the result is below
```
cpython-3.14.3-windows-x86_64-none                   AppData\Roaming\uv\python\cpython-3.14.3-windows-x86_64-none\python.exe
cpython-3.14.3-windows-x86_64-none                   .local\bin\python3.14.exe
cpython-3.14.3-windows-x86_64-none                   AppData\Roaming\uv\python\cpython-3.14-windows-x86_64-none\python.exe
```
step 2, then, run commands `uv python install 3.14t` and `uv python list`, the result is below
```
cpython-3.14.3-windows-x86_64-none                   .local\bin\python3.14.exe
cpython-3.14.3-windows-x86_64-none                   AppData\Roaming\uv\python\cpython-3.14-windows-x86_64-none\python.exe
cpython-3.14.3+freethreaded-windows-x86_64-none      AppData\Roaming\uv\python\cpython-3.14.3+freethreaded-windows-x86_64-none\python.exe
cpython-3.14.3+freethreaded-windows-x86_64-none      .local\bin\python3.14t.exe
cpython-3.14.3+freethreaded-windows-x86_64-none      AppData\Roaming\uv\python\cpython-3.14+freethreaded-windows-x86_64-none\python.exe
```

**QUESTION**: 
After the preceding 2 steps, below record is missing.
```
cpython-3.14.3-windows-x86_64-none                   AppData\Roaming\uv\python\cpython-3.14.3-windows-x86_64-none\python.exe
```

If navigate to directory `AppData\Roaming\uv\python`,  we can find that the directory `cpython-3.14.3+freethreaded-windows-x86_64-none` is still exists.

Is this a feature or a bug?

More comments:

1. If we reverse the commands in steps 1 and 2, we will obtain similar results.
2. The above is only an operation performed on version 3.14, and a similar situation also exists in version 3.13.

Image

### Platform

windows 11 home

### Version

uv 0.11.2 (02036a8ba 2026-03-26 x86_64-pc-windows-msvc)

### PR DESCRIPTION
**Pull request by woodruffw**
## Summary

This adds a regression test and fix for #18795. I ran the test and confirmed reproduction before implementing the fix.

The underlying bug here happens only on Windows, and only when exercising the PEP 514 Python installation registration pathway (which the integration tests disable by default, since it involves global mutable state that leaks between tests). The bug itself is just an imprecision in how we compute the "tag" for the Python entry -- we weren't including the variant (the `t` in `3.14t`), so two distinct installs (`3.14` and `3.14t`) would end up with the same registry tag. For an end user, this surfaces as  Python installation entries missing when running `uv python list`.

One thing to note about the test here is that it _does_ exercise the Windows registry pathway, which means that it intentionally bypasses the guardrail around global mutations in the integration tests. This is "fine" in the sense that there are on other tests observing that state at the moment, but I think it's a risk in terms of isolation (in the sense that devs who run our integration tests will actually observe global changes to their Python installations, plus any failure in the test means we won't clean up our global changes). Two options there:

- I could try and harden/isolate the registry mutation pathways a bit more, e.g. we could add `UV_DEV_WINDOWS_REGISTRY_COMPANY_KEY` or something like that to do some more test-level isolation of HKCU writes. This still modifies global state, but at least it'll be more namespaced.
- I could remove the integration test entirely, now that we've confirmed that the fix itself works. This leaves us without coverage, but given that the fix itself is ~2 lines that might be acceptable.

Fixes #18795.

## Test Plan

This PR includes a regression test.

### CODE REVIEW

**Comment by woodruffw** [comment]
Another thing to note: I'm not sure how this interacts with _existing_ installations -- this fixes the "from scratch" pathway, but there are probably users out there already who have both GIL and freethreaded variants installed and marked in the registry. I'm going to look more into that.

Edit: I _think_ what happens is that users will still see the stale registry/tag state until they explicitly upgrade or reinstall one of the variants. We could probably "fix" that by doing our orphaned registry entry removal on `uv python install`, but I'm not sure if that's worth it.

File: crates/uv/tests/it/python_install.rs [hunk 1]
```diff
@@ -1226,6 +1226,94 @@ fn python_install_freethreaded() {
...
 
+/// Test that installing both GIL and free-threaded variants of the same Python version
+/// doesn't cause managed installation entries to disappear from `uv python list`
+/// on Windows when registry discovery is enabled.
+///
+/// Regression test for <https://github.com/astral-sh/uv/issues/18795>.
+///
+/// IMPORTANT: this test writes to the shared `HKCU` registry. The trailing uninstall is
+/// best-effort cleanup; panics will leak entries. This is fine for now since this is the only
+/// test exercising the registry pathway, but adding more will probably require isolation.
```
Comment (zanieb) [inline crates/uv/tests/it/python_install.rs:1237]: Just checking, we have no other tests which touch the registry?

File: crates/uv-python/src/windows_registry.rs [hunk 2]
```diff
@@ -200,7 +200,18 @@ fn write_registry_entry(
 }
 
 fn registry_python_tag(key: &PythonInstallationKey) -> String {
-    format!("{}{}", key.implementation().pretty(), key.version())
+    // Include the variant's executable suffix (e.g., "t" for freethreaded) in the
+    // registry tag so that GIL and freethreaded installations of the same version
+    // get distinct registry entries. This suffix can be empty.
+    //
+    // See: https://github.com/astral-sh/uv/issues/18795
+    let variant_suffix = key.variant().executable_suffix();
```
Comment (zanieb) [inline crates/uv-python/src/windows_registry.rs:208]: This will also include `d` for debug installations. Is that desirable? (I think probably)

**Comment by zanieb** [comment]
@konstin is the owner of the Windows registry writes, fyi.

**Comment by zanieb** [comment]
> This is "fine" in the sense that there are no other tests observing that state at the moment

Why aren't other tests observing the state?

File: crates/uv/tests/it/python_install.rs (hunk 1 above)
Comment (woodruffw) [reply crates/uv/tests/it/python_install.rs:1237]: Yep, this is the only one FWICT. `TestContext::add_shared_env` disables the registry pathway:

https://github.com/astral-sh/uv/blob/9c0eec664d58281c532e91318a9ed5935b4b7602/crates/uv-test/src/lib.rs#L1239-L1241

File: crates/uv-python/src/windows_registry.rs (hunk 2 above)
Comment (woodruffw) [reply crates/uv-python/src/windows_registry.rs:208]: Yeah, I think so as well. My understanding is that without the variant in the tag we lose the mapping in the registry itself (e.g. when listing), so we should always include it.

File: crates/uv/tests/it/python_install.rs (hunk 1 above)
Comment (zanieb) [reply crates/uv/tests/it/python_install.rs:1237]: That's for writes, not reads though, right?

File: crates/uv-python/src/windows_registry.rs (hunk 2 above)
Comment (zanieb) [reply crates/uv-python/src/windows_registry.rs:208]: It might be worth making it clear in the comment that this isn't limited to free-threading

**Comment by woodruffw** [comment]
> Why aren't other tests observing the state?

The combination of https://github.com/astral-sh/uv/pull/19012#pullrequestreview-4121762728 and `UV_TEST_PYTHON_PATH` means that all other tests bypass the registry read pathway by default:

https://github.com/astral-sh/uv/blob/9c0eec664d58281c532e91318a9ed5935b4b7602/crates/uv-test/src/lib.rs#L1235

(So IIUC `UV_PYTHON_INSTALL_REGISTRY` controls the write path but separately none of our tests observe this global state because of `UV_TEST_PYTHON_PATH`. Which feels kind of brittle to me...)

**Comment by zanieb** [comment]
I think it'd make sense to add a `test-windows-registry` feature flag (it can still be on by default)

We'd also need to force the tests to run serially if we ever add more. Alas.

Can we use something like `UV_TEST_WINDOWS_REGISTRY_PREFIX` and prepend a unique identifier which we then require on all reads and writes? (We don't need to implement it in this pull request, just discussing)

File: crates/uv/tests/it/python_install.rs (hunk 1 above)
Comment (woodruffw) [reply crates/uv/tests/it/python_install.rs:1237]: Yep, that's writes only. https://github.com/astral-sh/uv/pull/19012#issuecomment-4261010583 describes the read path.

**Comment by woodruffw** [comment]
> I think it'd make sense to add a `test-windows-registry` feature flag (it can still be on by default)

SG, will do 🙂 

> Can we use something like `UV_TEST_WINDOWS_REGISTRY_PREFIX` and prepend a unique identifier which we then require on all reads and writes? (We don't need to implement it in this pull request, just discussing)

Yeah, I think so! This is what I meant with the first option in the PR comment:

> I could try and harden/isolate the registry mutation pathways a bit more, e.g. we could add UV_DEV_WINDOWS_REGISTRY_COMPANY_KEY or something like that to do some more test-level isolation of HKCU writes. This still modifies global state, but at least it'll be more namespaced.

I can look into that with a follow-up PR, I think it's a good idea regardless (because at some point we'll probably want more coverage on these routes anyways).

**Comment by konstin** [comment]
I've so far avoided any tests that (intentionally) modify registry. The risk is that we permanently modify a developer machine, as there's no temp dir root or virtual filesystem for the registry. It's helpful if we can run it in CI, but I wouldn't run this test by default on developer machines.

The fix itself looks good.

**Comment by woodruffw** [comment]
Agreed, I'll tweak this so that we only run `test-windows-registry` tests in CI.

**Comment by woodruffw** [comment]
Done, PTAL!

**Review by konstin — APPROVED** [review]
