### PR TITLE
Respect visitation order for proxy packages

### LINKED ISSUE #10425: `uv pip install --require-hashes` fails when (transitive) dependencies aren't pinned to latest version
uv version 0.5.16

## Description

When I `uv pip install --require-hashes -r requirements.txt` I get:

```log
⠙ urllib3==2.3.0
error: In `--require-hashes` mode, all requirements must be pinned upfront with `==`, but found: `urllib3`
```

But my `requirements.txt` does specify a version and hashes for `urllib3`:

```txt
urllib3==2.2.3 ; python_version >= "3.8" \
    --hash=sha256:ca899ca043dcb1bafa3e262d73aa25c465bfb49e0bd9dd5d59f1d0acba2f8fac \
    --hash=sha256:e7d814a81dad81e6caf2ec9fdedb284ecc9c73076b62654547cc64ccdcae26e9
```

This doesn't happen if I have a `requirements.txt` that pins to `urllib3==2.3.0`, which is the latest version.

## Hypothesis

The dependency solver is trying to pull in the latest version of `urllib3` rather than the version pinned in `requirements.txt`, and (obviously) not finding pinning (or hashes) for that version.

## How I got here (reproduction)

I start out with a `pyproject.toml`:

```toml
[project]
name = "test-require-hashes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests>=2.32.3",
]
```

Then generate a [poetry.lock](https://gist.github.com/cpswan/bed14d6fe28a0aef29698e23cb3d43d8#file-poetry-lock) file with `poetry lock`. Inside that I can see:

```txt
[[package]]
name = "requests"
version = "2.32.3"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.8"
groups = ["main"]
files = [
    {file = "requests-2.32.3-py3-none-any.whl", hash = "sha256:70761cfe03c773ceb22aa2f671b4757976145175cdfca038c02654d061d6dcc6"},
    {file = "requests-2.32.3.tar.gz", hash = "sha256:55365417734eb18255590a9ff9eb97e9e1da868d4ccd6402399eaf68af20a760"},
]
```

NB I'm using poetry 2.0.0 here as it respects PEP 621. I've also recreated this with poetry 1.8.2, but the pyproject.toml needs to use the old style [tool.poetry] rather than [project].

Then generate a [requirements.txt](https://gist.github.com/cpswan/bed14d6fe28a0aef29698e23cb3d43d8#file-requirements-txt) from the poetry.lock with `poetry export --output requirements.txt`, which contains:

```txt
urllib3==2.2.3 ; python_version >= "3.8" \
    --hash=sha256:ca899ca043dcb1bafa3e262d73aa25c465bfb49e0bd9dd5d59f1d0acba2f8fac \
    --hash=sha256:e7d814a81dad81e6caf2ec9fdedb284ecc9c73076b62654547cc64ccdcae26e9
```

Finally ask uv to install from that requirements.txt with --require-hashes `uv pip install --require-hashes -r requirements.txt`

### Python 3.8 is deprecated

Yes, I know, if I specify `requires-python = ">=3.9"` then I get a poetry.lock and requirements.txt that use urllib3==2.3.0

Whilst using 3.8 seems to be what surfaced this issue for me I don't think it's the fundamental cause.

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This PR reverts https://github.com/astral-sh/uv/pull/10441 and applies a different fix for https://github.com/astral-sh/uv/issues/10425.

In #10441, I changed prioritization to visit proxies eagerly. I think this is actually wrong, since it means we prioritize proxy packages above _everything_ else. And while a proxy only depends on itself, it does mean we're selecting a _version_ for the proxy package earlier than anything else. So, if you look at #10828, we end up choosing a version for `async-timeout` before we choose a version for `langchain`, despite the latter being a first-party dependency. (`async-timeout` has a marker on it, so it has a proxy package, so we solve for it first.)

To fix #10425, we instead need to make sure we visit proxies in the order we see them. I think the virtual tiebreaker for proxies is reversed? We want to visit the package we see first, first.

So, in short: this reverts #10441, then corrects the ordering for visiting proxies.

Closes https://github.com/astral-sh/uv/issues/10828.

### CODE REVIEW

File: crates/uv-resolver/src/dependency_provider.rs [hunk 1]
```diff
@@ -17,8 +17,8 @@ impl DependencyProvider for UvDependencyProvider {
     type V = Version;
     type VS = Range<Version>;
     type M = UnavailableReason;
-    /// Main priority and tiebreak for virtual packages
-    type Priority = (Option<PubGrubPriority>, u32);
+    /// Main priority and tiebreak for virtual packages.
+    type Priority = (Option<PubGrubPriority>, Option<PubGrubTiebreaker>);
```
Comment (konstin) [inline crates/uv-resolver/src/dependency_provider.rs:21]: See #10853

**Comment by konstin** [comment]
> To fix https://github.com/astral-sh/uv/issues/10425, we instead need to make sure we visit proxies in the order we see them. I think the virtual tiebreaker for proxies is reversed? We want to visit the package we see first, first.

Would it fix https://github.com/astral-sh/uv/issues/10425 if we visited the virtual packages inside the package-batch first?

Like:

* A{foo}
* A{bar}
* A <- This one is last
* B <- has no virtual packages
* C{python_version}
* C{extra}
* C <- this one is last

**Review by konstin — APPROVED** [review]
See #10853 for a follow-up

**Comment by charliermarsh** [comment]
@konstin -- I actually don't think that would be sufficient. Imagine:

```
foo==1
bar==1
```

We resolve `foo`, which depends on `bar ; sys_platform == "darwin"`. We'd then prioritize the `bar ; sys_platform == "darwin"` proxy over the base package, and we'd select a version of `bar` that didn't meet the `bar==1` requirement.

**Comment by charliermarsh** [comment]
I think a separate thing we could do, to make the order here less critical, is change these hash-mismatch errors to incompatibilities, so we backtrack rather than fail hard just for _trying_ an incompatible package.
