### PR TITLE
Disable transparent Python upgrades in projects when a patch version is requested via `.python-version`

### LINKED ISSUE #19100: uv python pin does not successfully pin you to a patch version
### Summary

If you use `uv python pin 3.x.y` to pin to the latest patch version installed on the system, `uv sync` wrongly creates a venv pointing at the mutable 3.x symlink, not at 3.x.y directly, meaning that an unrelated action triggering a download of a newer 3.x.z will cause the venv to do a transparent upgrade to 3.x.z, contrary to the pin.

```
$ uv self version
uv 0.11.7 (x86_64-unknown-linux-gnu)
$ uv python list '>=3.14.3,<3.15-gnu'
cpython-3.14.4-linux-x86_64-gnu    <download available>
cpython-3.14.3-linux-x86_64-gnu    .local/share/uv/python/cpython-3.14-linux-x86_64-gnu/bin/python3.14
$ uv init pinme
Initialized project `pinme` at `/home/ubuntu/pinme`
$ cd pinme
$ uv python pin 3.14.3
Updated `.python-version` from `3.14` -> `3.14.3`
$ uv sync
Using CPython 3.14.3
Creating virtual environment at: .venv
Resolved 1 package in 2ms
Checked in 0.00ms
$ .venv/bin/python -V
Python 3.14.3
$ uvx python3.14.4 -c True
[triggers a download]
$ .venv/bin/python -V
Python 3.14.4
$ readlink .venv/bin/python
/home/ubuntu/.local/share/uv/python/cpython-3.14-linux-x86_64-gnu/bin/python3.14
$ head -n1 .venv/pyvenv.cfg 
home = /home/ubuntu/.local/share/uv/python/cpython-3.14-linux-x86_64-gnu/bin
```

Interestingly, uv _now_ realizes that the venv is incorrect and recreates it (hence using .venv/bin/python directly above):

```
$ uv run python -V
Using CPython 3.14.3
Removed virtual environment at: .venv
Creating virtual environment at: .venv
Python 3.14.3
$ readlink .venv/bin/python
/home/ubuntu/.local/share/uv/python/cpython-3.14.3-linux-x86_64-gnu/bin/python3.14
$ head -n1 .venv/pyvenv.cfg 
home = /home/ubuntu/.local/share/uv/python/cpython-3.14.3-linux-x86_64-gnu/bin
```

I believe this is a regression between 0.11.6 and 0.11.7, almost certainly surfaced by 9aee91cf00ff03f23f89e0353e53be3131ce11a1 (though the bug is probably somewhere else), cc @zanieb.

### Platform

Linux, but also reproduces on Windows

### Version

0.11.7

### Python version

_No response_

### PR DESCRIPTION
**Pull request by zanieb**
Fixes #19100

This was an underlying bug surfaced outside of preview by https://github.com/astral-sh/uv/pull/18961

We were not computing the resolved Python version request, so we were not taking into account `.python-version` values.

### CODE REVIEW

File: crates/uv/src/commands/project/mod.rs [hunk 1]
```diff
@@ -1422,7 +1422,23 @@ impl ProjectEnvironment {
...
+            workspace.install_path().as_ref(),
+            no_config,
+        )
+        .await
+        .ok()
+        .and_then(|workspace_python| workspace_python.python_request);
+
+        let upgradeable = resolved_request
             .as_ref()
             .is_none_or(|request| !request.includes_patch());
```
Comment (zanieb) [inline crates/uv/src/commands/project/mod.rs]: This seems problematic, I think we'll need to refactor to avoid repeating this logic and inference.

Comment (zanieb) [reply crates/uv/src/commands/project/mod.rs]: See https://github.com/astral-sh/uv/pull/19103

File: crates/uv/src/commands/project/mod.rs [hunk 2]
```diff
@@ -1412,7 +1412,23 @@ impl ProjectEnvironment {
...
+            Some(workspace),
+            groups,
+            workspace.install_path().as_ref(),
+            no_config,
+        )
+        .await
+        .ok()
+        .and_then(|workspace_python| workspace_python.python_request);
+
+        let upgradeable = resolved_request
```
Comment (zanieb) [inline crates/uv/src/commands/project/mod.rs]:
```suggestion
        let workspace_python = WorkspacePython::from_request(
            python.clone(),
            Some(workspace),
            groups,
            workspace.install_path().as_ref(),
            no_config,
        )
        .await
        .ok()
        .and_then(|workspace_python| workspace_python.python_request);

        let upgradeable = workspace_python
```

File: crates/uv/src/commands/project/mod.rs [hunk 3]
```diff
@@ -1412,10 +1412,9 @@ impl ProjectEnvironment {
             })
             .ok();
 
-        let upgradeable = python
-            .as_ref()
-            .is_none_or(|request| !request.includes_patch());
-
+        // Resolve the effective Python request, taking into account `--python`,
+        // `.python-version`, and `requires-python`, so that a patch version pinned via
+        // `.python-version` prevents the environment from being marked upgradeable.
```
Comment (zanieb) [inline crates/uv/src/commands/project/mod.rs]:
```suggestion
```

File: crates/uv/tests/it/python_upgrade.rs [hunk 4]
```diff
@@ -838,3 +838,89 @@ fn python_upgrade_build_version() {
...
+        r#"
+        [project]
+        name = "project"
+        version = "0.1.0"
+        requires-python = ">=3.10"
+        "#,
+    )?;
+
+    // Install an earlier patch version
+    uv_snapshot!(context.filters(), context.python_install().arg("3.10.17"), @r"
```
Comment (konstin) [inline crates/uv/tests/it/python_upgrade.rs:868]: Is it possible to reuse a version here to avoid downloading and installing another version?

Comment (zanieb) [reply crates/uv/tests/it/python_upgrade.rs:868]: What do you mean by reuse? It requires a managed install operation to cover the transparent upgrade behavior.
