### PR TITLE
Error on lockfiles with incoherent wheel versions

### LINKED ISSUE #12164: `uv sync --locked` does not detect incorrect `uv.lock`
### Summary

Discovered from a bug of dependabot: 
https://github.com/dependabot/dependabot-core/issues/10478#issuecomment-2723709984

To reproduce
1. select any package in uv.lock
2. change its version to any valid semver 
    + edit the `package.version` field directly in `uv.lock`
3. run `uv sync --locked`

The installed package is still the previous installed version. It mismatches with what the lock file specified.

There is no warning or error for this case. `uv` continues sliently.

### Platform

Linux 6.8.0-55-generic x86_64 GNU/Linux

### Version

uv 0.6.6

### Python version

Python 3.13.2

### PR DESCRIPTION
**Pull request by konstin**
Reject lockfiles where the package version and the wheel versions are incoherent. This implicitly checks that all wheel files have the same version.

It does not check for the source dist version, since a source dist may not contain a version in the filename and attempting to deserialize source dist filenames we may not need is a performance overhead for something that's already slow in `uv run`.

Fixes #12164

### CODE REVIEW

File: crates/uv-resolver/src/lock/mod.rs [hunk 1]
```diff
@@ -2871,6 +2871,19 @@ impl PackageWire {
...
+        // Consistency check
+        if let Some(version) = &self.id.version {
+            for wheel in &self.wheels {
+                if version != &wheel.filename.version {
+                    return Err(LockError::from(LockErrorKind::InconsistentVersions {
+                        name: self.id.name,
+                    }));
+                }
+            }
+            // We can't check the source dist version since it does not need to contain the version
```
Comment (jtfmumm) [inline crates/uv-resolver/src/lock/mod.rs:2883]: We should always have at least one wheel enabling us to catch the inconsistency?

File: crates/uv/tests/it/sync.rs [hunk 2]
```diff
@@ -8473,3 +8473,97 @@ fn prune_cache_url_subdirectory() -> Result<()> {
...
+    success: false
+    exit_code: 2
+    ----- stdout -----
+
+    ----- stderr -----
+    error: Failed to parse `uv.lock`
+      Caused by: Locked package and file versions are inconsistent for `iniconfig`
+    ");
+
+    // Without `--locked`, we could fail or recreate the lockfile, currently, we fail.
```
Comment (jtfmumm) [inline crates/uv/tests/it/sync.rs:8557]: Would a user find this surprising? I think I'd assume uv will create a correct lockfile when running `uv lock`. And it might not be clear to a user what action they should take next if they see this error.

I guess it partially depends on what "If a lockfile is present, its contents will be used as preferences for the resolution" from the docs for `uv lock` means. Does that mean we try to use those preferences, but override them if necessary?

File: crates/uv-resolver/src/lock/mod.rs (hunk 1 above)
Comment (konstin) [reply crates/uv-resolver/src/lock/mod.rs:2883]: Not necessarily, for example:

```toml
dependencies = [
    "sniffio",
]

[tool.uv.sources]
sniffio = { path = "sniffio.tar.gz" }
```

`uv.lock`:

```toml
[[package]]
name = "sniffio"
version = "1.3.1"
source = { path = "sniffio.tar.gz" }
sdist = { hash = "sha256:f4324edc670a0f49750a81b895f35c3adb843cca46f0530f79fc1babb23789dc" }
```

In this case, it's not possible to determine from the lockfile alone whether there is an inconsistency.

File: crates/uv/tests/it/sync.rs (hunk 2 above)
Comment (konstin) [reply crates/uv/tests/it/sync.rs:8557]: Currently, we fail on all kinds of parsing errors with lockfile. For example, an empty `uv.lock` fails:

```
$ uv lock
error: Failed to parse `uv.lock`
  Caused by: TOML parse error at line 1, column 1
  |
1 | 
  | ^
missing field `version`
```

As does a lockfile where I removed the source line:

```
$ uv lock
error: Failed to parse `uv.lock`
  Caused by: TOML parse error at line 16, column 1
   |
16 | [[package]]
   | ^^^^^^^^^^^
missing field `source`
```

We can try to be better about recovering from a broken lockfile, but that's outside of the scope of the PR (uv would never write such a lockfile, and with this change, uv will refuse to sync a broken dependabot PR, failing CI). In cases where the lockfile is not invalid but doesn't fully match in a non-version anymore, e.g., the environments changed, we for example only reuse the versions as preference but not the full lockfile (`ValidatedLock` enumerates the cases).

File: crates/uv-resolver/src/lock/mod.rs (hunk 1 above)
Comment (konstin) [reply crates/uv-resolver/src/lock/mod.rs:2888]: I've added another commit that catches all mismatches between locked source dist version and the built wheel versions at build time. This would enforce stricter guarantees than we require right now, CC @charliermarsh

File: crates/uv/tests/it/sync.rs (hunk 2 above)
Comment (konstin) [reply crates/uv/tests/it/sync.rs:8557]: As an example:

```toml
[[package]]
name = "sniffio"
version = "2.3.4"
source = { url = "https://files.pythonhosted.org/packages/a2/87/a6771e1546d97e7e041b6ae58d80074f81b7d5121207425c964ddf5cfdbd/sniffio-1.3.1.tar.gz" }
sdist = { hash = "sha256:f4324edc670a0f49750a81b895f35c3adb843cca46f0530f79fc1babb23789dc" }
```

With this last commit fails with:

```
  × Failed to download and build `sniffio @
  │ https://files.pythonhosted.org/packages/a2/87/a6771e1546d97e7e041b6ae58d80074f81b7d5121207425c964ddf5cfdbd/sniffio-1.3.1.tar.gz`
  ╰─▶ Package metadata version `1.3.1` does not match given version `2.3.4`
  help: `sniffio` was included because `foo` (v0.1.0) depends on `sniffio`
```

The potential clash could be with git dependencies that use a version-from-git integration.

File: crates/uv-resolver/src/lock/mod.rs (hunk 1 above)
Comment (konstin) [reply crates/uv-resolver/src/lock/mod.rs:2888]: As an example:

```toml
[[package]]
name = "sniffio"
version = "2.3.4"
source = { url = "https://files.pythonhosted.org/packages/a2/87/a6771e1546d97e7e041b6ae58d80074f81b7d5121207425c964ddf5cfdbd/sniffio-1.3.1.tar.gz" }
sdist = { hash = "sha256:f4324edc670a0f49750a81b895f35c3adb843cca46f0530f79fc1babb23789dc" }
```

With this last commit fails with:

```
  × Failed to download and build `sniffio @
  │ https://files.pythonhosted.org/packages/a2/87/a6771e1546d97e7e041b6ae58d80074f81b7d5121207425c964ddf5cfdbd/sniffio-1.3.1.tar.gz`
  ╰─▶ Package metadata version `1.3.1` does not match given version `2.3.4`
  help: `sniffio` was included because `foo` (v0.1.0) depends on `sniffio`
```

The potential clash could be with git dependencies that use a version-from-git integration.

Comment (konstin) [reply crates/uv-resolver/src/lock/mod.rs:2883]: Moved this to a separate PR: https://github.com/astral-sh/uv/pull/12237

**Comment by charliermarsh** [comment]
Does this mean that Dependabot updates will lead to hard uv errors? (I understand that, at least the linked issue, what they're doing today may not be sound.)

**Comment by konstin** [comment]
I think so, at least making PRs with this logic without updating source dist and wheels accordingly will lead to broken lockfiles: https://github.com/dependabot/dependabot-core/blob/1cd6fc59d7dae25d46255550528dd056c97c46d8/uv/lib/dependabot/uv/file_updater/lock_file_updater.rb#L111-L120

**Comment by shauneccles** [comment]
As a user and developer I want uv to explode if dependabot maims my lockfile so I know about it and so I can raise issues with dependabot.

File: crates/uv-resolver/src/lock/mod.rs [hunk 3]
```diff
@@ -2871,6 +2871,19 @@ impl PackageWire {
         requires_python: &RequiresPython,
         unambiguous_package_ids: &FxHashMap<PackageName, PackageId>,
     ) -> Result<Package, LockError> {
+        // Consistency check
+        if let Some(version) = &self.id.version {
+            for wheel in &self.wheels {
+                if version != &wheel.filename.version {
+                    return Err(LockError::from(LockErrorKind::InconsistentVersions {
+                        name: self.id.name,
+                    }));
```
Comment (zanieb) [inline crates/uv-resolver/src/lock/mod.rs:2880]: Can we show the versions in the error here? Like "packaged version {} does not match {} from wheel {}"?

Comment (zanieb) [reply crates/uv-resolver/src/lock/mod.rs:2880]: https://github.com/astral-sh/uv/pull/12249

**Review by zanieb — APPROVED** [review]

**Comment by kleinhenz** [comment]
This seems to have caused some problems with the flash-attn wheels.

```
#pyproject.toml
...

[tool.uv]
environments = ["sys_platform == 'darwin'", "sys_platform == 'linux'"]
constraint-dependencies = ["torch==2.5.1"]

[tool.uv.sources]
flash_attn = [
  { url = "https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.3/flash_attn-2.7.3+cu12torch2.5cxx11abiFalse-cp310-cp310-linux_x86_64.whl", marker = "sys_platform == 'linux' and python_version == '3.10'"},
  { url = "https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.3/flash_attn-2.7.3+cu12torch2.5cxx11abiFalse-cp311-cp311-linux_x86_64.whl", marker = "sys_platform == 'linux' and python_version == '3.11'"},
  { url = "https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.3/flash_attn-2.7.3+cu12torch2.5cxx11abiFalse-cp312-cp312-linux_x86_64.whl", marker = "sys_platform == 'linux' and python_version == '3.12'"},
  { url = "https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.3/flash_attn-2.7.3+cu12torch2.5cxx11abiFalse-cp313-cp313-linux_x86_64.whl", marker = "sys_platform == 'linux' and python_version == '3.13'"}
]
```

Now causes `uv sync` to error with
```
error: Failed to parse `uv.lock`
  Caused by: The entry for package `flash-attn` v2.7.3 has wheel `flash_attn-2.7.3+cu12torch2.5cxx11abifalse-cp310-cp310-linux_x86_64.whl` with inconsistent version: v2.7.3+cu12torch2.5cxx11abifalse
  ```
  
  Not sure if there is a better way to configure usage of these wheels.
