### PR TITLE
Don't panic in `uv export --frozen` when the lockfile is outdated

### LINKED ISSUE #16406: Panic when trying to export a lockfile that has no root
### Summary

When running `uv export --frozen --format requirements-txt --verbose` with a `uv.lock` that has no root, uv crashes with the following message:
```
DEBUG uv 0.9.5 (d5f39331a 2025-10-21)
DEBUG Acquired shared lock for `C:\Users\jj\AppData\Local\uv\cache`
DEBUG Found project root: `C:\Local\tv\266\videomaster-regtool-generator`
DEBUG No workspace root found, using project root

thread 'main2' panicked at C:\a\uv\uv\crates\uv-resolver\src\lock\export\mod.rs:77:18:
could not find root
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
DEBUG Released lock at `C:\Users\jj\AppData\Local\uv\cache\.lock`

thread 'main' panicked at C:\a\uv\uv\crates\uv\src\lib.rs:2407:10:
Tokio executor failed, was there a panic?: Any { .. }
```

I understand that the lockfile is ill-formed, and that an error should be expected, but I think it deserves a better message.

[uv.lock.txt](https://github.com/user-attachments/files/23049618/uv.lock.txt)
(I had to rename it to .txt to upload it).

### Platform

Windows 10 and Ubuntu 22.04

### Version

0.8.22 and 0.9.5

### Python version

Python 3.12.11

### PR DESCRIPTION
**Pull request by konstin**
Provide a good error message when the discovered workspace members mismatch with the locked workspace members in `uv export --frozen`, instead of panicking.

Fixes #16406

### CODE REVIEW

File: crates/uv-resolver/src/lock/export/mod.rs [hunk 1]
```diff
@@ -73,8 +74,12 @@ impl<'lock> ExportableRequirements<'lock> {
...
                 .lock()
                 .find_by_name(root_name)
-                .expect("found too many packages matching root")
-                .expect("could not find root");
+                .map_err(|_| LockErrorKind::MultipleRootPackages {
+                    name: root_name.clone(),
+                })?
+                .ok_or_else(|| LockErrorKind::MissingRootPackage {
+                    name: root_name.clone(),
+                })?;
```
Comment (konstin) [inline crates/uv-resolver/src/lock/export/mod.rs:82]: We now catch this early, but there's no reason to panic with there's different paths to accessing this code.

File: crates/uv/src/commands/project/mod.rs [hunk 2]
```diff
@@ -87,6 +87,11 @@ pub(crate) enum ProjectError {
     )]
     MissingLockfile,
 
+    #[error(
+        "The lockfile at `uv.lock` needs to be updated, but `--frozen` was provided: Missing workspace member `{0}`. To update the lockfile, run `uv lock`."
```
Comment (konstin) [inline crates/uv/src/commands/project/mod.rs:91]: The missing workspace member is only for our debugging, we could also put this in a nested source.

File: crates/uv/src/commands/project/lock.rs [hunk 3]
```diff
@@ -334,6 +334,17 @@ impl<'env> LockOperation<'env> {
...
+                if let LockTarget::Workspace(workspace) = target {
+                    for package_name in workspace.packages().keys() {
+                        existing
+                            .find_by_name(package_name)
+                            .map_err(|_| ProjectError::LockWorkspaceMismatch(package_name.clone()))?
+                            .ok_or_else(|| {
+                                ProjectError::LockWorkspaceMismatch(package_name.clone())
+                            })?;
+                    }
+                }
```
Comment (konstin) [inline crates/uv/src/commands/project/lock.rs:347]: This is technically more strict than the previous check, but it will only fail in cases where the lockfile doesn't match the on-disk workspace structure, while afaik we require the workspace structure to be intact through `VirtualProject::discover` (`uv export --frozen --no-emit-workspace --no-emit-project` panics too)?
