### PR TITLE
less aggressive overlapping markers

### LINKED ISSUE #4640: Universal resolver fails when multiple divergent constraints are provided
Given:

```
requests
requests==2.32.3 ; python_version >= '3.12'
requests==2.32.0 ; python_version < '3.12'
```

Running `uv pip compile requirements.txt --universal` fails with:

```
  × No solution found when resolving dependencies:
  ╰─▶ Because requests{python_version >= '3.12'}==2.32.3 depends on requests==2.32.3 and you require requests{python_version >= '3.12'}==2.32.3, we can conclude that your requirements and requests{python_version < '3.12'}==2.32.0 are
      incompatible.
      And because you require requests{python_version < '3.12'}==2.32.0, we can conclude that the requirements are unsatisfiable.
```

This seems a bit silly, but it's maybe not quite as silly if you view it as constraints. Imagine your `requirements.txt` is:

```
requests
```

And then your `constraints.txt` is:

```
requests==2.32.3 ; python_version >= '3.12'
requests==2.32.0 ; python_version < '3.12'
```

This would also fail.

### LINKED ISSUE #4732: Handle overlapping and incomplete markers when forking
In python, a package can declare conflicting requirements as long as the markers are disjoint, e.g.:
```
numpy==2.0.0; python_version >= "3.11"
numpy==1.26.4; python_version < "3.11"
```
When we see requirements like that, we split the resolution into one for `python_version >= "3.11"` and one for `python_version < "3.11"` and solve each fork individually. This fails when the markers are overlapping or don't cover the entirety of the marker space. For a real-world example, opencv-python 4.10.0.84 used by transformers:

```
numpy >=1.13.3 ; python_version < "3.7"
numpy >=1.21.0 ; python_version <= "3.9" and platform_system == "Darwin" and platform_machine == "arm64"
numpy >=1.21.2 ; python_version >= "3.10"
numpy >=1.21.4 ; python_version >= "3.10" and platform_system == "Darwin"
numpy >=1.23.5 ; python_version >= "3.11"
numpy >=1.26.0 ; python_version >= "3.12"
numpy >=1.19.3 ; python_version >= "3.6" and platform_system == "Linux" and platform_machine == "aarch64"
numpy >=1.17.0 ; python_version >= "3.7"
numpy >=1.17.3 ; python_version >= "3.8"
numpy >=1.19.3 ; python_version >= "3.9"
```

Currently, we solve for the following forks (https://github.com/astral-sh/uv/issues/4687):

```
python_version >= '3.12' and platform_machine == 'aarch64' and platform_system == 'Darwin' and platform_system == 'Linux'
python_version < '3.13' and python_version >= '3.12' and platform_machine == 'aarch64' and platform_system == 'Darwin' and platform_system == 'Linux'
python_version >= '3.13' and platform_machine == 'aarch64' and platform_system == 'Darwin' and platform_system == 'Linux'
python_version == '3.9' and platform_machine == 'arm64' and platform_system == 'Darwin'
```

They are disjoint, but they are also missing a good bit of the marker space for which we never solve.

---

Let's give working with markers some math-y foundations, a visualization as mental model and let's look at two examples.

Lemma: Inflating the requirements by artificially introducing a split. A requirement
```
foo
```
is equivalent to
```
foo; X
foo; not(X)
```
Similarly,
```
foo; Y
```
is equivalent to
```
foo; Y and X
foo; Y and not(X)
```
We can extend this to an arbitrary number of arguments, so if Z¹, Z², ..., Z^n are pairwise disjoint and the union over i in 0..n for Z^i is the base set omega, then
```
foo; Y
```
is equivalent to
```
foo; Y and Z¹
foo; Y and Z²
...
foo; Y and Z^n
```

Now assume we have the following set of partially pairwise overlapping (https://github.com/astral-sh/uv/issues/4640), partially pairwise incomplete (https://github.com/astral-sh/uv/issues/4687) markers:
```
foo¹>2
foo²>3; x>=5
foo³<4; x<7
```
We can now inflate the requirements by artificially introducing a split:
```
foo¹>2; (x>=7)
foo²>3; x>=5 and (x>=7)
foo³<4; x<7 and (x>=7)

foo¹>2; (x<7 and x>=5)
foo²>3; x>=5 and (x<7 and x>=5)
foo³<4; x<7 and (x<7 and x>=5)

foo¹>2; (x<5)
foo²>3; x>=5 and (x<5)
foo³<4; x<7 and (x<5)
```
We see that each group is disjoint, so we can create three forks. Simplifying and Removing empty markers we get:
```
# Fork 1
foo¹>2; x>=7
foo²>3; x>=7

# Fork 2
foo¹>2; x<7 and x>=5
foo²>3; x<7 and x>=5
foo³<4; x<7 and x>=5

# Fork 3
foo¹>2; x<5
foo³<4; x<5
```
We defined a correct way of splitting these markers.

---

Let us switch to another example to develop a model of markers and marker space. Ignoring extras, we can consider the current environment a point in a 10-dimensional marker space defined by PEP 508 (os_name, sys_platform, platform_machine, platform_python_implementation, platform_release, platform_system, platform_version, python_version/python_full_version, implementation_name, implementation_version). The dimensions are of different datatypes and not all points exist (os_name=="posix" and platform_system=="Windows" doesn't make sense). A marker is a slice in that space.

We can visualize a simpler version of the opencv-python 4.10.0.84 requirements:
```
numpy >=1.21.4 ; python_version >= "3.10" and platform_system == "Darwin"
numpy >=1.21.2 ; python_version >= "3.11"
numpy >=1.21.0 ; python_version <= "3.9" and platform_system == "Darwin"
```

image

There is two ways we can transform these requirements with the diagram:
* Merge overlapping: 1 and 2 are overlapping, so there's a fork 1 or 2. There's a fork 3 and a fork for the remaining space not(1 or 2 or 3)
* Split overlapping: 1 and 2 are overlapping so there's a fork 1 \ 2, 2 \ 1 and 1 and 2 . There's a fork 3 and a fork for the remaining space not(1 or 2 or 3)

image

For splitting overlapping, the options are:

* crosses, `python_version >= "3.10" and python_version < "3.11" and platform_system == "Darwin"` with `numpy >=1.21.4`
* stripes, `python_version >= "3.11" and platform_system == "Darwin"` with `numpy >=1.21.2` and `numpy >=1.21.4`
* dots, `python_version >= "3.11" and platform_system != "Darwin"` with `numpy >=1.21.2`

I favor to splitting the overlapping, it's the more general solution, and the one able to handle complex cases like the opencv-python markers (even though we pick a more recent numpy version for them anyway). If we merge overlapping, we need to special case the universal marker (no marker provided) for https://github.com/astral-sh/uv/issues/4640. In either case, we need to implement marker tree negation to support incomplete markers, and proper simplification for negated marker tree to determine if the markers were actually incomplete or did cover the entire markers space, leaving only an empty set.

### PR DESCRIPTION
**Pull request by BurntSushi**
This is like #5733, but implements less aggressive forking. Namely, in
#5733, we would possibly fork any time we say a marker expression, even
if there was only one dependency specification for that package. In
this PR, we only consider forking when there are at least two sibling
dependency specifications for the same package name.

The end result here is that this fixes #4640 but not #4668. It also
doesn't fix some as-yet unreported bugs related to detecting forks in
conflicting transitive dependencies. However, this does have fewer
changes overall in resolutions when compared to the status quo, and
also has a much smaller performance regression in some ad hoc
benchmarks.

Our plan is to compare this PR and #5733 on real world projects to see
how the actual resolutions differ.

Fixes #4640, Closes #4732

### CODE REVIEW

**Comment by BurntSushi** [comment]
On the transformers benchmark detailed in #5733:

```
$ hyperfine -w10 -p 'rm -rf uv.lock' 'uv-main lock' 'uv-overlapping-markers-aggressive lock' 'uv-overlapping-markers-conservative lock'
Benchmark 1: uv-main lock
  Time (mean ± σ):      49.4 ms ±   2.6 ms    [User: 47.3 ms, System: 52.2 ms]
  Range (min … max):    44.1 ms …  55.8 ms    63 runs

Benchmark 2: uv-overlapping-markers-aggressive lock
  Time (mean ± σ):     101.4 ms ±   3.9 ms    [User: 106.9 ms, System: 72.7 ms]
  Range (min … max):    94.8 ms … 109.0 ms    30 runs

Benchmark 3: uv-overlapping-markers-conservative lock
  Time (mean ± σ):      53.6 ms ±   3.2 ms    [User: 51.1 ms, System: 54.8 ms]
  Range (min … max):    47.0 ms …  61.2 ms    54 runs

Summary
  uv-main lock ran
    1.09 ± 0.09 times faster than uv-overlapping-markers-conservative lock
    2.05 ± 0.13 times faster than uv-overlapping-markers-aggressive lock
```

And on Home Assistant:

```
$ hyperfine -w10 -p 'rm -rf uv.lock' 'uv-main lock' 'uv-overlapping-markers-aggressive lock' 'uv-overlapping-markers-conservative lock'
Benchmark 1: uv-main lock
  Time (mean ± σ):     181.6 ms ±   2.7 ms    [User: 145.5 ms, System: 115.4 ms]
  Range (min … max):   176.4 ms … 186.7 ms    16 runs

Benchmark 2: uv-overlapping-markers-aggressive lock
  Time (mean ± σ):     223.4 ms ±   3.8 ms    [User: 184.9 ms, System: 121.8 ms]
  Range (min … max):   219.4 ms … 232.2 ms    13 runs

Benchmark 3: uv-overlapping-markers-conservative lock
  Time (mean ± σ):     180.8 ms ±   2.6 ms    [User: 143.3 ms, System: 115.9 ms]
  Range (min … max):   177.2 ms … 187.5 ms    16 runs

Summary
  uv-overlapping-markers-conservative lock ran
    1.00 ± 0.02 times faster than uv-main lock
    1.24 ± 0.03 times faster than uv-overlapping-markers-aggressive lock
```

Note that `uv-overlapping-markers-{conservative,aggressive}` are both derived from @ibraheemdev's BDD marker work (which isn't on `main` yet). Without the BDD work, `uv-overlapping-markers-aggressive` is slower (3-4x regression from `main` instead of 1-2x).

File: crates/uv/tests/lock.rs [hunk 1]
```diff
@@ -1719,13 +1720,14 @@ fn lock_conditional_dependency_extra() -> Result<()> {
...
-    success: true
-    exit_code: 0
+    success: false
+    exit_code: 2
     ----- stdout -----
 
     ----- stderr -----
     warning: `uv lock` is experimental and may change without warning
     Resolved 7 packages in [TIME]
+    error: The lockfile at `uv.lock` needs to be updated, but `--locked` was provided. To update the lockfile, run `uv lock`.
```
Comment (BurntSushi) [inline crates/uv/tests/lock.rs:1730]: These snapshots look wrong. I haven't investigated yet, but we probably shouldn't merge before fixing these.

**Comment by BurntSushi** [comment]
This does regress the warm resolve for jupyter by about 10%, but I think that's acceptable for a change like this where we improve correctness at the known cost of possibly forking more. Of course, we should investigate further to improve perf and possibly even avoid forking if we can determine it won't be useful, but I think that should be reserved for future work.

**Review by charliermarsh — APPROVED** [review]
