### PR TITLE
Detect hard-float support on aarch64 kernels running armv7 userspace

### LINKED ISSUE #18509: How does uv determine the host CPU capabilities on armv7l?
### Question

I try to run installation tests with `uv` for `armv7l` on GitHub ARM runners. For this, a Debian `armhf` userland is booted as `systemd-nspawn` container, and the `uname` output is altered to return `armv7l` instead of `aarch64` (the GitHub ARM runner architecture).

1. `uv python install 3.14` downloads `cpython-3.14.3-linux-armv7-gnueabi` instead of `cpython-3.14.3-linux-armv7-gnueabihf`, despite hardfloat userland and CPU.
2. `uv venv` keeps pulling `cpython-3.14.3-linux-armv7-gnueabi` even if `cpython-3.14.3-linux-armv7-gnueabihf` was installed explicitly. Which fails with:
    ```
    error: Python interpreter not found at `~/.local/share/uv/python/cpython-3.14.3-linux-armv7-gnueabi/bin/python3.14`
    ```
    Can be avoided by enforcing the `gnueabihf` interpreter with `UV_PYTHON`, which then needs to be unset afterwards, else `uv pip install` won't use the `venv` interpreter.
3. `uv pip install` then works using the `venv`.

This is independent of the Debian version, and I could not replicate it on actual `armv7l` hardware. However, would be great if there was a way to have `uv` functional in `armv7l` containers on `aarch64` hosts as well.

Might also affect setups without container, like Raspberry Pi OS 32-bit on 64-bit RPi models. The Raspberry Pi 4 by default uses the 64-bit kernel even with 32-bit userland, hence not so uncommon there.

### Platform

Debian armhf on aarch64 host

### Version

uv 0.10.10

### PR DESCRIPTION
**Pull request by zanieb**
Pulled out of https://github.com/astral-sh/uv/pull/18517

I don't have aarch64 hardware available locally, but Claude posited: 

> When an armv7 binary runs on an aarch64 kernel (e.g., armv7l containers on aarch64 hosts, or 32-bit Raspberry Pi OS on 64-bit hardware), /proc/cpuinfo reports aarch64-style feature flags instead of armv7 flags. The existing check for "vfp" fails because aarch64 uses "fp" instead.
> 
> Add detection of the aarch64 "fp" feature flag (mandatory on all aarch64 CPUs) as a discrete token, indicating hardware floating-point support. This ensures uv selects the gnueabihf (hard-float) Python variant instead of the gnueabi (soft-float) variant.

I reproduced this in https://github.com/astral-sh/uv/pull/18532

Under QEMU on aarch64 macOS, both the `vfp` and `fp` feature flags are set.

Closes #18509

### CODE REVIEW

File: crates/uv-platform/src/cpuinfo.rs [hunk 1]
```diff
@@ -31,3 +48,44 @@ pub(crate) fn detect_hardware_floating_point_support() -> Result<bool, Error> {
 pub(crate) fn detect_hardware_floating_point_support() -> Result<bool, Error> {
     Ok(false) // Non-Linux or non-ARM systems: hardware floating-point detection is not applicable
 }
+
+#[cfg(test)]
+mod tests {
+    #[cfg(target_os = "linux")]
+    use super::has_hardware_float_features;
```
Comment (zanieb) [inline crates/uv-platform/src/cpuinfo.rs:55]: I could certainly be convinced to just drop these tests
