### PR TITLE
fix(#10717): Omit stdout and stderr sections when empty in errors

### LINKED ISSUE #10717: Omit `stdout` and `stderr` sections when empty in errors
e.g., https://github.com/astral-sh/uv/blob/4d3809cc6b28d71f26a782929b994abfebd7973c/crates/uv-python/src/interpreter.rs#L565-L578

can create some sort of confusing output

    DEBUG uv [VERSION] ([COMMIT] DATE)
    DEBUG Searching for default Python interpreter in virtual environments, managed installations, or search path
    DEBUG Failed to inspect Python interpreter from active virtual environment at `.venv/bin/python3`
    DEBUG Skipping bad interpreter at /Users/zb/.local/share/uv/tests/.tmpdujfqj/temp/.venv/bin/python3 from active virtual environment: Querying Python at `/Users/zb/.local/share/uv/tests/.tmpdujfqj/temp/.venv/bin/python3` failed with exit status exit status: 1
    --- stdout:

    --- stderr:

    ---
    DEBUG Failed to inspect Python interpreter from virtual environment at `.venv/bin/python3`
    DEBUG Skipping bad interpreter at /Users/zb/.local/share/uv/tests/.tmpdujfqj/temp/.venv/bin/python3 from virtual environment: Querying Python at `/Users/zb/.local/share/uv/tests/.tmpdujfqj/temp/.venv/bin/python3` failed with exit status exit status: 1
    --- stdout:

    --- stderr:

    ---
    DEBUG Searching for managed installations at `.`
    DEBUG Found `cpython-3.12.6-macos-aarch64-none` at `/Users/zb/.local/share/uv/tests/.tmpdujfqj/python/3.12/python3` (search path)

### PR DESCRIPTION
**Pull request by styvane**
## Summary

This change closes #10717

### CODE REVIEW

File: crates/uv-python/src/interpreter.rs [hunk 1]
```diff
@@ -550,6 +551,61 @@ impl ExternallyManaged {
...
+            "Querying Python at `{}` did not return the expected data\n{}",
+            self.path.display(),
+            self.err
+        )?;
+        let delim = "---";
+        if !self.stdout.trim().is_empty() {
+            writeln!(f, "{} stdout:\n{}", delim, self.stdout)?;
+        }
+        if !self.stderr.trim().is_empty() {
+            write!(f, "{0} stderr:\n{1}\n{0}", delim, self.stderr)?;
```
Comment (charliermarsh) [inline crates/uv-python/src/interpreter.rs:575]: Is `write` here vs. `writeln` above intentional?

File: crates/uv-python/src/interpreter.rs [hunk 2]
```diff
@@ -550,6 +551,61 @@ impl ExternallyManaged {
...
+    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
+        writeln!(
+            f,
+            "Querying Python at `{}` did not return the expected data\n{}",
+            self.path.display(),
+            self.err
+        )?;
+        let delim = "---";
+        if !self.stdout.trim().is_empty() {
+            writeln!(f, "{} stdout:\n{}", delim, self.stdout)?;
```
Comment (charliermarsh) [inline crates/uv-python/src/interpreter.rs:572]: Is `{}` vs. `{0}` below intentional?

**Review by charliermarsh — COMMENTED** [review]
Thanks!

File: crates/uv-python/src/interpreter.rs (hunk 2 above)
Comment (styvane) [reply crates/uv-python/src/interpreter.rs:572]: This was intentional, I  replaced the positional  argument with a named  argument

File: crates/uv-python/src/interpreter.rs (hunk 1 above)
Comment (styvane) [reply crates/uv-python/src/interpreter.rs]: No, it wasn't fixed now. Thank you

**Review by charliermarsh — APPROVED** [review]
