### PR TITLE
Unify editable and unnamed URL parsing

### LINKED ISSUE #3941: Support PEP 508-style editable requirements
For example, `--editable "mypkg[dist] @ git+https://github.com/username/mypkg"` is supposed to work. That it doesn't work in pip right now is an implementation limitation. See: https://github.com/pypa/pip/issues/1289.

### LINKED ISSUE #3942: Deduplicate unnamed URL and editable URL parsing
I think the requirements here are identical, but we have two totally separate paths for them (and now have some bugs for unnamed URLs that we already fixed for editables).

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This will help prevent bugs like #3934 by unifying the implementations for editables and non-editable unnamed requirements. Specifically, both of these now go through the same parsing paths and use the same struct representations (with the exception that the editable flag is flipped in the first case):

```
-e ./foo/bar
./foo/bar
```

We also now support PEP 508 in editable URLs. It turns out this is just a limitation in pip, so it's correct to support it. For example, this now works:

```
-e black[d] @ file://${PROJECT_ROOT}/scripts/packages/black_editable
```

Closes #3941.

Closes #3942.

### CODE REVIEW

File: crates/pep508-rs/src/unnamed.rs [hunk 1]
```diff
@@ -356,8 +362,31 @@ fn parse_unnamed_url<Url: UnnamedRequirementUrl>(
...
+            if depth == 0 && c.is_whitespace() {
+                break;
+            }
+            if backslash {
+                backslash = false;
+            } else if c == '\\' {
+                backslash = true;
+            } else if c == '[' {
+                depth += 1;
+            } else if c == ']' {
```
Comment (MichaReiser) [inline crates/pep508-rs/src/unnamed.rs:382]: Is it guaranteed that the parentheses are always balanced?

Comment (charliermarsh) [reply crates/pep508-rs/src/unnamed.rs:379]: Good call, thanks.

**Comment by charliermarsh** [comment]
Deleted a few hundred lines of code but added a few hundred in tests and snapshots.
