### PR TITLE
Better error message for missing space before semicolon in requirements

### LINKED ISSUE #1637: Failed to parse `example @ example.whl; sys_platform == 'win32'`
I have a requirements file with a line that tries to install a local .whl file, but only on Windows. When I try to run this, UV gives an error:
```
error: Failed to parse `python_ldap @ wheels/python_ldap-3.4.0-cp311-cp311-win_amd64.whl;   sys_platform == 'win32'`
  Caused by: Expected end of input or ';', found 's'
python_ldap @ wheels/python_ldap-3.4.0-cp311-cp311-win_amd64.whl;   sys_platform == 'win32'
                                                                    ^
```

If I remove the sys_platform part it works. sys_platform does also work if I'm not installing a local package, but I haven't been able to combine the local package syntax with the sys_platform filter.

This was on Windows, UV version 0.1.4. Apologies if I'm doing something wrong here, but I couldn't figure it out.

### PR DESCRIPTION
**Pull request by konstin**
PEP 508 requires a space between a URL and the semicolon separating it from the markers to disambiguate it from a url ending with a semicolon. This is easy to get wrong because the space is not required after a plain name of PEP 440 specifier. The new error message explicitly points out the missing space.

Fixes #1637

### CODE REVIEW

File: crates/pep508-rs/src/lib.rs [hunk 1]
```diff
@@ -976,12 +982,24 @@ fn parse(cursor: &mut Cursor, working_dir: Option<&Path>) -> Result<Requirement,
     // wsp*
     cursor.eat_whitespace();
     if let Some((pos, char)) = cursor.next() {
+        if let Some(VersionOrUrl::Url(url)) = requirement_kind {
+            // Unwrap safety: The `VerbatimUrl` we just parsed has a string source.
+            if url.given().unwrap().ends_with(';') && marker.is_none() {
+                return Err(Pep508Error {
+                    message: Pep508ErrorSource::String("Missing space before ';'".to_string()),
```
Comment (AlexWaygood) [inline crates/pep508-rs/src/lib.rs:989]: This tells you what's gone wrong, but not why we need to issue an error here in the first place. I think if I were a user and I got this message, my immediate question would be, "Well, you obviously understood what I _meant_ here... so why not just do that?"

Maybe something like this? Not sure if there's a more concise way of explaining it:

```suggestion
                    message: Pep508ErrorSource::String("\
Missing space before ';' creates an ambiguous requirement
(Unclear whether the ';' is part of the URL or separates the URL from an environment marker)".to_string()
                    ),
```

**Review by AlexWaygood — COMMENTED** [review]
Nic!

File: crates/pep508-rs/src/lib.rs (hunk 1 above)
Comment (konstin) [reply crates/pep508-rs/src/lib.rs]: The reason itself is somewhat counterintuitive since we allow paths too, which unlike urls can contain spaces which we don't support except for the hack with file urls, and because PEP 508 doesn't require a semicolon after a version number for symmetry.

**Review by AlexWaygood — APPROVED** [review]
