### PR TITLE
Fix schema for PackageExcludeNewer

### LINKED ISSUE #17664: JSON schema for `exclude-newer-package` is slightly off
I noticed this when trying to add the following to a `pyproject.toml`:

```toml
exclude-newer-package = { ty = false, ruff = false, uv = false }
```

yields the following schema error from my IDE:

```
{"ty":false,"ruff":false,"uv":false} is not valid under any of the schemas listed in the 'anyOf' keyword
```

This can be minimized to:

```toml
exclude-newer-package = { ty = false }
```

Yielding:

```
{"ty":false} is not valid under any of the schemas listed in the 'anyOf' keyword
```

This schema error goes away if `false` is quoted instead, e.g.:

```toml
exclude-newer-package = { ty = "false" }
```

However that seems wrong from a TOML typing perspective, plus it earns at runtime:

```
warning: Failed to parse `pyproject.toml` during settings discovery:
  TOML parse error at line 16, column 32
     |
  16 | exclude-newer-package = { ty = "false", ruff = false, uv = false }
     |                                ^^^^^^^
  failed to parse exclude-newer value: `false` could not be parsed as a valid exclude-newer value (expected a date like `2024-01-01`, a timestamp like `2024-01-01T00:00:00Z`, or a duration like `3 days` or `P3D`)
```

I'm _pretty_ sure the underlying problem here is with `PackageExcludeNewer`, which has:

https://github.com/astral-sh/uv/blob/c72a5a2ee55112fed11b7379124f0c5a33536cbb/crates/uv-resolver/src/exclude_newer.rs#L434-L445

However, this type has a manual `Deserialize` implementation, so schemars doesn't see it (I think). Consequently the generated JSON schema is for the Rust layout itself, which isn't accurate:

https://github.com/astral-sh/uv/blob/c72a5a2ee55112fed11b7379124f0c5a33536cbb/uv.schema.json#L1104-L1124

### PR DESCRIPTION
**Pull request by woodruffw**
## Summary

Fixes #17664.

## Test Plan

I'm not sure if there's a great way to test this in-repo. Maybe we could add some schema tests?

### CODE REVIEW

File: crates/uv-resolver/src/exclude_newer.rs [hunk 1]
```diff
@@ -436,14 +436,36 @@ impl std::fmt::Display for ExcludeNewerValue {
...
+            "oneOf": [
+                {
+                    "type": "boolean",
+                    "const": false,
+                    "description": "Disable exclude-newer for this package."
+                },
+                {
+                    "type": "string",
+                    "description": "A date, timestamp, or duration to use as the exclude-newer cutoff for this package."
+                }
```
Comment (woodruffw) [inline crates/uv-resolver/src/exclude_newer.rs]: Realized I can use a subschema from ExcludeNewerValue for this...

File: crates/uv-resolver/src/exclude_newer.rs [hunk 2]
```diff
@@ -804,7 +823,7 @@ impl std::fmt::Display for ExcludeNewer {
 #[cfg(feature = "schemars")]
 impl schemars::JsonSchema for ExcludeNewerValue {
     fn schema_name() -> Cow<'static, str> {
-        Cow::Borrowed("ExcludeNewerTimestamp")
+        Cow::Borrowed("ExcludeNewerValue")
```
Comment (woodruffw) [inline crates/uv-resolver/src/exclude_newer.rs:826]: Note: renamed this since the Rust type itself was renamed (presumably in an earlier refactor).

**Review by zanieb — APPROVED** [review]
