### PR TITLE
Error early for parent path in build backend

### LINKED ISSUE #15702: 🐛 Bug: `uv build` fails with invalid Python module path with no clear error message
## Project Structure

I am working with a Django project where:

- Not using **uv** as project management
- Using **uv** only for backend build

```

electo_premium/
    client/
    newspaper/
    payments/
    pyproject.toml
    manage.py
    __init__.py   # necessary for uv build

````

**Note:** If you are wondering why I am building the whole project as a wheel:  

To use **Apache Airflow**, I need to place my Django source code inside the virtual environment's `site-packages/` folder on the AWS Airflow server so that my Django code is also accessible in AWS Airflow.

For example, this import should work at aws airflow environment:  

```python
from electo_premium.newspaper.models import NewsLetter
```

## pyproject.toml

```toml
# pyproject.toml - content

[build-system]
requires = ["uv_build>=0.8.12,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "electo_premium"
module-root = "../"  # Go one step backward (Not sure if going backward is even possible)
````

## Command Run

At the same directory where `manage.py` exists:

```bash
uv build
```

## Actual Output

```text
Building source distribution (uv build backend)...
Building wheel from source distribution (uv build backend)...
  × Failed to build `/home/trootech/Production Projects/electo/electo_premium`
  ╰─▶ Expected a Python module at: `/home/trootech/.cache/uv/sdists-v9/.tmpR0ugJW/electo_premium-1.0.0/../electo_premium/__init__.py`
```

## ❌ Problem

The error message seems **invalid/weird** — it is looking for the module at a path containing `/home/trootech/.cache/uv/sdists-v9/.tmpR0ugJW/electo_premium-1.0.0/../electo_premium/__init__.py`, which doesn’t look correct.

## ✅ Expected Behavior

`uv build` should correctly locate the `__init__.py` inside the project and build the package without path resolution errors.

---

### 📝 Notes

* The `__init__.py` file **does exist** inside `electo_premium/`.
* The error message suggests that path resolution may be going one step too far (`../`) during build.

### Platform

Linux 6.8.0-45-generic x86_64 GNU/Linux

### Version

uv 0.8.15

### Python version

Python 3.12.7

### PR DESCRIPTION
**Pull request by konstin**
Paths referencing above the directory of the `pyproject.toml`, such as `module-root = ".."`, are not supported by the build backend. The check that should catch was not working properly, so the source distribution built successfully and only the wheel build failed. We now error early. The same fix is applied to data includes.

Fix #15702

### CODE REVIEW

**Review by zanieb — APPROVED** [review]

File: crates/uv-build-backend/src/lib.rs [hunk 1]
```diff
@@ -66,6 +66,9 @@ pub enum Error {
     /// Either an absolute path or a parent path through `..`.
     #[error("Module root must be inside the project: `{}`", _0.user_display())]
     InvalidModuleRoot(PathBuf),
+    /// Either an absolute path or a parent path through `..`.
+    #[error("The path for the data directory {} must be inside the project: `{}`", name, path.user_display())]
```
Comment (zanieb) [inline crates/uv-build-backend/src/lib.rs:70]: I think we tend to omit the backticks following a `:`

Comment (konstin) [reply crates/uv-build-backend/src/lib.rs:70]: I'll change it consistently in a separate PR

**Comment by DhavalGojiya** [comment]
Thank you for all your hard work, @konstin.
