### PR TITLE
Make cache errors non-fatal in Planner::build

### LINKED ISSUE #12274: uv sync fails due to invalid cache
### Summary

It started happening right after upgrading from 0.6.5 to 0.6.6. 

In our environment, `~/.cache/uv` is cached between CI runs. My theory is that for some time uv 0.6.5 ran alternating with 0.6.6 on different branches sharing the same cache, as the issue did not happen when 0.6.6 was first introduced.

The error itself is very similar to the one fixed in https://github.com/astral-sh/uv/pull/11105, but it comes from a different place:

```
$ uv sync --frozen --no-dev --extra xyz
error: Failed to determine installation plan
Caused by: Failed to deserialize cache entry
Caused by: array had incorrect length, expected 4
```

After a cursory glance at the code of `Planner.build()`, it looks like caching didn't get the same treatment in `{Http,Local}ArchivePointer::read_from()` as `SourceDistributionBuilder::url_metadata()` got in https://github.com/astral-sh/uv/pull/11105

### Platform

Debian 12 (bookworm)

### Version

uv 0.6.6

### Python version

CPython 3.11.2

### PR DESCRIPTION
**Pull request by Gankra**
Same basic approach as #11105, including a cache version bump.

Fixes #12274

### CODE REVIEW

File: crates/uv-installer/src/plan.rs [hunk 1]
```diff
@@ -97,17 +97,20 @@ impl<'a> Planner<'a> {
...
+                            Ok(RequirementSatisfaction::Satisfied) => {
                                 debug!("Requirement already installed: {installed}");
                                 continue;
                             }
-                            RequirementSatisfaction::OutOfDate => {
+                            Ok(RequirementSatisfaction::OutOfDate) => {
                                 debug!("Requirement installed, but not fresh: {installed}");
                             }
+                            Err(err) => {
+                                debug!("Failed to deserialize cached requirements for: {installed} ({err})");
```
Comment (charliermarsh) [inline crates/uv-installer/src/plan.rs:112]: We might want this to be `warn!`

Comment (charliermarsh) [reply crates/uv-installer/src/plan.rs:112]: I guess this can fail for other reasons though. Should it be more discriminate or no?

File: crates/uv-installer/src/plan.rs [hunk 2]
```diff
@@ -230,28 +240,41 @@ impl<'a> Planner<'a> {
...
+
+                                            debug!("Path wheel requirement already cached: {cached_dist}");
+                                            cached.push(CachedDist::Url(cached_dist));
+                                            continue;
+                                        }
+                                        debug!("Cached path wheel requirement does not match expected hash policy for: {wheel}");
+                                    }
+                                }
+                                Err(err) => {
+                                    debug!("failed to get timestamp for wheel {wheel} ({err})");
```
Comment (charliermarsh) [inline crates/uv-installer/src/plan.rs:270]: Nit: caps

File: crates/uv-installer/src/plan.rs (hunk 1 above)
Comment (Gankra) [reply crates/uv-installer/src/plan.rs:112]: At least in the current implementation, it actually is all CacheInfo calls that make this fallible. warn feels too aggressive for "oops the cache was invalid"?

Comment (charliermarsh) [reply crates/uv-installer/src/plan.rs:112]: But that's probably out-of-scope.

Comment (charliermarsh) [reply crates/uv-installer/src/plan.rs:112]: Should we move this into `RequirementSatisfaction::check`? If it's already non-fatal for other kinds of errors, maybe it shouldn't return `Result` at all and we should just ignore these errors within that method.

Comment (Gankra) [reply crates/uv-installer/src/plan.rs:112]: That sounds like a good idea... hmm interesting SitePackages::satisfies_requirements also `?`s this method and it probably shouldn't..?
