### PR TITLE
Control pip timeout duration via environment variable

### LINKED ISSUE #1549: Operation Timeout on Pip Install
On an internet connection with slow downloads a `uv pip install` often seems to lead to a timeout.

Here is an example error message:

```
20.82 Resolved 163 packages in 20.61s                                                                                                                        
320.0 error: Failed to download distributions                                                                                                                
320.0   Caused by: Failed to fetch wheel: scikit-image==0.21.0                                                                                               
320.0   Caused by: Failed to extract source distribution: request or response body error: operation timed out                                                
320.0   Caused by: request or response body error: operation timed out
320.0   Caused by: operation timed out
```

I am running `uv==0.1.2`.

Is there a way to increase the timeout to allow for slower downloads?

### PR DESCRIPTION
**Pull request by Di-Is**
## Summary

Add the environment variable `UV_REQUEST_TIMEOUT` to allow control over pip timeouts.

Closes #1549 

## Test Plan

I built uv in the repository top Dockerfile, set the timeout to 3 seconds, and ran `uv pip install torch`.
I measured the execution time with the time command and confirmed that the process finished at a value close to the timeout we set.

```bash
root@037c69228cdc:~# time UV_REQUEST_TIMEOUT=3 /uv pip install torch
Resolved 22 packages in 25ms
error: Failed to download distributions
  Caused by: Failed to fetch wheel: nvidia-cusolver-cu12==11.4.5.107
  Caused by: Failed to extract source distribution
  Caused by: request or response body error: operation timed out
  Caused by: operation timed out

real    0m3.064s
user    0m0.225s
sys     0m0.240s
```

### CODE REVIEW

File: crates/uv-client/src/registry_client.rs [hunk 1]
```diff
@@ -78,11 +79,15 @@ impl RegistryClientBuilder {
 
     pub fn build(self) -> RegistryClient {
         let client_raw = {
+            let timeout: u64 = env::var("UV_REQUEST_TIMEOUT")
+                .ok()
+                .and_then(|v| v.parse::<u64>().ok())
+                .unwrap_or(300);
```
[the remark this answers is not in the document]
Comment (zanieb) [reply crates/uv-client/src/registry_client.rs:85]: Can we log the timeout we're going to use e.g. with `debug!`?

**Review by zanieb — COMMENTED** [review]
Thanks for contributing! I have a couple minor questions.

File: crates/uv-client/src/registry_client.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (Di-Is) [reply crates/uv-client/src/registry_client.rs]: > Will we silently ignore invalid values here? Should we warn if it can't be parsed?
> Can we log the timeout we're going to use e.g. with `debug!`?

Thanks for the review.
Yes, I think it would be more user-friendly if you suggested it.
I have fixed the implementation and would appreciate a check.

File: crates/uv-client/src/registry_client.rs [hunk 2]
```diff
@@ -79,10 +79,21 @@ impl RegistryClientBuilder {
...
-                .and_then(|v| v.parse::<u64>().ok())
-                .unwrap_or(300);
+            // Get pip timeout from env var
+            let default_timeout = 5 * 60;
+            let timeout: u64 = match env::var("UV_REQUEST_TIMEOUT") {
+                Ok(value) => {
+                    match value.parse::<u64>() {
+                        Ok(parsed) => parsed,
+                        Err(_) => {
+                            eprintln!("Warning: UV_REQUEST_TIMEOUT is an invalid value. Using default value.");
```
Comment (zanieb) [inline crates/uv-client/src/registry_client.rs:89]: We have a `warn_user_once!` macro that we should use instead here.

Comment (zanieb) [reply crates/uv-client/src/registry_client.rs:89]: Would it make sense to use `.map_err` instead of a `match` here?

Comment (zanieb) [reply crates/uv-client/src/registry_client.rs:89]: I'd also probably be a little clearer here, maybe:

> Ignoring invalid value for UV_REQUEST_TIMEOUT. Expected integer number of seconds, got "{value}".

File: crates/uv-client/src/registry_client.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (Di-Is) [reply crates/uv-client/src/registry_client.rs]: The following is how the implemented logs are generated.

```bash
root@484f49cfa3cf:~# /uv pip install torch -v 
 uv::requirements::from_source source=torch
    0.002100s DEBUG uv_interpreter::virtual_env Found a virtualenv named .venv at: /root/.venv
    0.002159s DEBUG uv_interpreter::interpreter Detecting markers for: /root/.venv/bin/python
    0.021205s DEBUG uv::commands::pip_install Using Python 3.10.12 environment at /root/.venv/bin/python
    0.021605s DEBUG uv_client::registry_client Pip request timeout is 300.
...
root@484f49cfa3cf:~# UV_REQUEST_TIMEOUT=a /uv pip install torch
Warning: UV_REQUEST_TIMEOUT is an invalid value. Using default value.
Resolved 22 packages in 891ms
████░░░░░░░░░░░░░░░░ [5/22] jinja2==3.1.3
```

File: crates/uv-client/src/registry_client.rs [hunk 3]
```diff
@@ -78,11 +79,26 @@ impl RegistryClientBuilder {
...
+                            default_timeout
+                        }
+                    }
+                }
+                Err(_) => default_timeout,
+            };
+            debug!("Pip request timeout is {}.", timeout);
```
Comment (zanieb) [inline crates/uv-client/src/registry_client.rs:96]: We should probably not say "Pip" this is our general registry client 
```suggestion
            debug!("Using registry request timeout of {}s", timeout);
```

**Comment by Di-Is** [comment]
@zanieb
Sorry, I deleted some commits because I had the wrong user to push.
I have re-committed it and would appreciate it if you could check it.

**Review by zanieb — APPROVED** [review]
Thanks!
