### PR TITLE
Respect allow insecure host in publish

### LINKED ISSUE #8423: `uv publish` doesn't respect the `--allow-insecure-host` flag
It seems like `uv publish` doesn't respect the `--allow-insecure-host` flag

### uv command
```shell
uv publish --publish-url https://localhost --allow-insecure-host "localhost" --verbose --username="test" --password="test"
```
output:
```
DEBUG uv 0.4.25
warning: `uv publish` is experimental and may change without warning
Publishing 2 files https://localhost/
DEBUG Using request timeout of 900s
Uploading sigmatcher-1.3.1-py3-none-any.whl (14.1KiB)
DEBUG Using username/password basic auth
DEBUG Transient request failure for https://localhost/, retrying: error sending request for url (https://localhost/)
  Caused by: client error (Connect)
  Caused by: invalid peer certificate: UnknownIssuer
warning: Transient request failure for https://localhost/, retrying
DEBUG Using username/password basic auth
DEBUG Transient request failure for https://localhost/, retrying: error sending request for url (https://localhost/)
  Caused by: client error (Connect)
  Caused by: invalid peer certificate: UnknownIssuer
warning: Transient request failure for https://localhost/, retrying
DEBUG Using username/password basic auth
error: Failed to publish `dist/sigmatcher-1.3.1-py3-none-any.whl` to https://localhost/
  Caused by: Failed to send POST request
  Caused by: error sending request for url (https://localhost/)
  Caused by: client error (Connect)
  Caused by: invalid peer certificate: UnknownIssuer
```

### mock server
I used the following steps to create a mock https server with self signed certs that can reproduce the issue.

1. generate the cert using:
```sh
openssl genrsa  -out server.key 2048
openssl req -new -key server.key -out server.csr -subj "/CN=localhost"
openssl x509 -req -days 1024 -in server.csr -signkey server.key -out server.crt
cat server.crt server.key > server.pem
```
2. run this python script:
```python
from http.server import HTTPServer, BaseHTTPRequestHandler
import ssl


httpd = HTTPServer(('localhost', 443), BaseHTTPRequestHandler)

context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
context.load_cert_chain('server.pem', 'server.key')

httpd.socket = context.wrap_socket(httpd.socket, server_side=True)

httpd.serve_forever()
```

### PR DESCRIPTION
**Pull request by konstin**
Switch to respecting the allow insecure host setting in all places where we use the client.

Fixes #8423
Part of #6985
Doesn't touch #6983

### CODE REVIEW

**Review by zanieb — APPROVED** [review]

File: crates/uv-client/src/base_client.rs [hunk 1]
```diff
@@ -350,16 +350,6 @@ enum Security {
...
 impl BaseClient {
-    /// The underlying [`ClientWithMiddleware`] for secure requests.
-    pub fn client(&self) -> ClientWithMiddleware {
-        self.client.clone()
-    }
-
-    /// The underlying [`Client`] without middleware.
-    pub fn raw_client(&self) -> Client {
-        self.raw_client.clone()
-    }
```
Comment (zanieb) [inline crates/uv-client/src/base_client.rs:361]: Is this going to break a downstream consumer?

Comment (konstin) [reply crates/uv-client/src/base_client.rs:361]: Who would be affected? I can't find anything

```
$ git log -S "fn raw_client"
commit e7ae0f50d218aede8d7283d8cf414e8f7782fbba (origin/main, origin/HEAD, main)
Author: konsti <konstin@mailbox.org>
Date:   Tue Oct 22 13:36:18 2024 +0200

    Respect allow insecure host in publish (#8440)

commit 205bf8cabef5c931203df15bca5e524dbfaac08a
Author: konsti <konstin@mailbox.org>
Date:   Tue Sep 24 18:07:20 2024 +0200

    Implement trusted publishing (#7548)
    
    Co-authored-by: Charlie Marsh <charlie.r.marsh@gmail.com>
```
