### PR TITLE
Query interpreter to determine correct `virtualenv` paths

### LINKED ISSUE #2095: virtualenvs should base `site-packages` and other directories on `sysconfig` paths
Right now, we assume a specific structure for the virtualenvs that we create, and it's necessary (I think?) that this structure matches the `sysconfig.get_paths()` returned by the interpreter in the virtual environment later. The paths seem to be correct for CPython, but they're not quite right for PyPy, and could be wrong _in general_ for unusual distros.

If you look at [virtualenv](https://github.com/pypa/virtualenv/blob/5cd543fdf8047600ff2737babec4a635ad74d169/src/virtualenv/discovery/py_info.py#L119C14-L119C28), my understanding is that it does something like...

- Call `sysconfig.get_path()` without expanding variables.
- Grab the value for each variable.
- [Override specific variables to the current working directory](https://github.com/pypa/virtualenv/blob/5cd543fdf8047600ff2737babec4a635ad74d169/src/virtualenv/discovery/py_info.py#L161).

### LINKED ISSUE #2153: For some python implementations uv expects a different `site-packages` path than it creates
`uv` version: 0.1.13, installed from `pip`.

Below is a snippet from a `ubuntu:22.04` based docker container where I'm unable to use `uv` to install into its virtualenv. I'm installing `pip` in the log below but this doesn't seem to be related to the package being installed.

```
USER@0aa98759ed66:~$ python
Python 3.8.12 (remotes/origin/release_2.3.5:4b858b5062, Sep 25 2022, 18:56:33)
[Pyston 2.3.5, GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

USER@0aa98759ed66:~$ which python
/.pyenv/versions/pyston-2.3.5/bin/python

USER@0aa98759ed66:~$ uv venv
Using Python 3.8.12 interpreter at: /.pyenv/versions/pyston-2.3.5/bin/python
Creating virtualenv at: .venv
Activate with: source .venv/bin/activate

USER@0aa98759ed66:~$ ls .venv/lib/
python3.8

USER@0aa98759ed66:~$ uv pip install pip --verbose
 uv::requirements::from_source source=pip
    0.001656s DEBUG uv_interpreter::python_environment Found a virtualenv named .venv at: /home/USER/.venv
    0.001719s DEBUG uv_interpreter::interpreter Cached interpreter info for Python 3.8.12, skipping probing: /home/USER/.venv/bin/python
    0.001726s DEBUG uv::commands::pip_install Using Python 3.8.12 environment at /home/USER/.venv/bin/python
error: Failed to list installed packages
  Caused by: failed to read directory `/home/USER/.venv/lib/python3.8-pyston2.3/site-packages`
  Caused by: No such file or directory (os error 2)

```

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This PR migrates our virtualenv creation from a setup that assumes prior knowledge of the correct paths, to a technique borrowed from `virtualenv` whereby we use `sysconfig` and `distutils` to determine the paths. The general trick is to grab the expected paths with `sysconfig`, then make them all relative, then make them absolute for a given directory.

Closes #2095.
Closes #2153.

### CODE REVIEW

File: crates/uv-interpreter/src/interpreter.rs [hunk 1]
```diff
@@ -390,21 +406,9 @@ impl Interpreter {
...
-    /// Return the name of the Python directory used to build the path to the
-    /// `site-packages` directory.
-    ///
-    /// If one could not be determined, then `python` is returned.
-    pub fn site_packages_python(&self) -> &str {
-        if self.implementation_name() == "pypy" {
-            "pypy"
-        } else {
-            "python"
-        }
```
Comment (charliermarsh) [inline crates/uv-interpreter/src/interpreter.rs:407]: E.g., this is no longer necessary.
